### ISSUE TITLE
Fontawesome + Oqtane question

### ISSUE THREAD

**Issue by tanekim77** [oqtane/oqtane.framework#1007]
I am seeing that Page class has an Icon property, and it specifies an Open Iconic name.

If I want to use icon that is not available in Open Iconic, is there a way to do so?

Is there way for me to include extra property like public string FontAwesomeIcon {get; set;} in Page class without modifying Page.cs? In this way, when I am creating a custom theme, I can use whatever icon that is available to display, either from Page.FontAwesomeIcon or from Page.Icon.

**Comment by sbwalker** [comment]
Currently Oqtane supports Open Iconic. We will not be distributing any additional icon libraries as part of the framework as it goes against our Philosophy ( https://www.oqtane.org/Resources/Blog/PostId/538/oqtane-philosophy ) related to third party dependencies. The Page property for Icon should probably not be tightly coupled to Open Iconic so that it is possible to use other icon libraries. This will require modifications to the framework.

**Comment by sbwalker** [comment]
#1009 removes the hard dependency on Open Iconic and allows you to use other icon libraries
