### ISSUE TITLE
Localization: Po file support

### ISSUE THREAD

**Issue by tanekim77** [oqtane/oqtane.framework#1014]
I am seeing that there a word "Localizer" is used for IStringLocalizer, and used like @ Localizer["Hello"]

I would recommend to use the word "S" instead, so that it is used like @ S["Hello"]

based on the convention by OrchardCMS framework.

The reason being is that it's not only more succinct but also opens up for other possibilities for the users. One major benefit would be that it will allow users to use amazing tools like PoExtractor that will scan all codes and extract relevant localization candidates.

To learn more about it, here is the link https://github.com/lukaskabrt/PoExtractor

**Comment by hishamco** [comment]
@tanekim77 I worked for both Orchard Core & Oqtane, each one has it's own characteristics, regarding the `S` or `T` which already used in Orchard Core it had been driven from Orchard 1, I already discussed that with @sbwalker when I impemented the localization, `Localizer` is more readable

Regarding the PO nothing prevent you from doing that in case that you don't like RESX files. In case of PoExtractor which I contibuted to it too ;) it's great for PO, that's why I suggested to implement a new tool for us [here](https://github.com/oqtane/oqtane.translations/discussions/1)

**Comment by tanekim77** [comment]
@hishamco That's awesome, thanks!

**Comment by hishamco** [comment]
You are welcome anytime
