### ISSUE TITLE
svg open iconic support

### ISSUE THREAD

**Issue by tanekim77** [oqtane/oqtane.framework#1020]
Currently, Page.cs => Icon property contains string like "oi oi-home", which is for bootstrap font icon version.`<span class="oi oi-home"></span>`. But in some pages, I need to use svg version of that icon, which need to be in a form like 
`<svg viewBox="0 0 8 8"><use xlink:href="#home"></use></svg>
`
 which does not contain "oi oi-" prefix.  Wouldn't it be better if Page.Icon contains icon name only without "oi oi-" prefix so that it can be used for other purposes, like for svg version of that icon?

**Comment by sbwalker** [comment]
PR #1009 removed the hard-wired dependency of Page.Icon from the Open Iconic library. It now allows you to specify the full icon class name to be used with the standard ```<i>``` tag. For example if you wanted to use Font Awesome icons rather than Open Iconic icons you could specify "fa fa-camera-retro" to get a camera icon ( you would obviously need to include the Font Awesome icon library in your solution as well for this to work ). The navigation menu components support the standard icon class specification. SVG icons are not supported by the navigation components.
