### ISSUE TITLE
Deleting Module Issue

### ISSUE THREAD

**Issue by PhilipMur** [oqtane/oqtane.framework#1087]
My steps to recreate the issue.
>>login
>>admin dashboard
>>Module management
>>Create a module using the module creator
>>Add new module >> Developer Module >> Module Creator
>>close the oqtane server
>>open the new created module in visual studio and build it
>>close the new created project thats opened in visual studio
>>restart the oqtane server once again
>>login
>>admin dashboard
>>Module management
>>find the module
>>try delete it

issue experienced
The server hangs and visual studio hangs crashes and reports an issue to microsoft.

I can see in the logs that its trying to delete it from another instance of SQL server (USERNULL) i have running but when i install the Oqtane server i chose the localDB and also i verified it in the appsettings.json file

Also i can browse the localDB that Oqtane installed and i can create users OK Create new modules OK etc and i can see then in the localDB.

`{
  "ConnectionStrings": {
    "DefaultConnection": "Data Source=(LocalDb)\\MSSQLLocalDB;AttachDbFilename=|DataDirectory|\\Oqtane-202101291423.mdf;Initial Catalog=Oqtane-202101291423;Integrated Security=SSPI;"
  },
  "Runtime": "Server",
  "Installation": {
    "DefaultAlias": "",
    "HostPassword": "",
    "HostEmail": "",
    "SiteTemplate": "",
    "DefaultTheme": "",
    "DefaultLayout": "",
    "DefaultContainer": ""
  },
  "Localization": {
    "DefaultCulture": "",
    "SupportedCultures": []
  }
}`

![Screenshot (1531)](https://user-images.githubusercontent.com/27295232/106619476-8bb79300-6568-11eb-8c08-11717955ecaf.png)
![Screenshot (1530)](https://user-images.githubusercontent.com/27295232/106619504-92460a80-6568-11eb-94f0-3dcf7c536b50.png)
![Screenshot (1521)](https://user-images.githubusercontent.com/27295232/106619624-b1449c80-6568-11eb-81b0-b12efcdf2efd.png)

**Comment by PhilipMur** [comment]
Sorry forgot to attached the logs screenshot from Octane
here it is.
![Screenshot (1532)](https://user-images.githubusercontent.com/27295232/106620207-3e87f100-6569-11eb-8e6f-6452018b6091.png)

**Comment by PhilipMur** [comment]
Just to add to the weird issue when i browse the data in the dbo.ModuleDefinition i can see the newly created Modules and created a new user and that gets added OK to the local.db.

**Comment by leigh-pointer** [comment]
Can you check the entry in the Tenant table.  The connection string need to be the same as what is in your config file.

**Comment by PhilipMur** [comment]
They are the same

This is from the appsettings.json file.

Data Source=(LocalDb)\\MSSQLLocalDB;AttachDbFilename=|DataDirectory|\\Oqtane-202101291423.mdf;Initial Catalog=Oqtane-202101291423;Integrated Security=SSPI;

This is from the dbo.Tenant

Data Source=(LocalDb)\MSSQLLocalDB;AttachDbFilename=|DataDirectory|\Oqtane-202101291423.mdf;Initial Catalog=Oqtane-202101291423;Integrated Security=SSPI;


![Screenshot (1534)](https://user-images.githubusercontent.com/27295232/106632058-42217500-6575-11eb-8199-ef6c0fc66531.png)

**Comment by PhilipMur** [comment]
Modules still showing up after just trying to delete them.

Can someone else try to replicate before i have no hair left 😓 , Thanks

In case the issue is only isolated to me.


![Screenshot (1537)](https://user-images.githubusercontent.com/27295232/106634291-8f9ee180-6577-11eb-936b-4cfe40956258.png)

**Comment by leigh-pointer** [comment]
If you have used the module creator to create your module Im sure the framework will not delete it and every time the framework is run the module will be picked up and installed.

**Comment by PhilipMur** [comment]
Why does it cause a hang and throw an error?

What's its purpose if it cannot delete?

**Comment by sbwalker** [comment]
This issue is not isolated to you... but its quite a bit more complicated than it appears on the surface...

Based on the screen shots and behavior reported, I am going to assume you are using the official 2.0.0 release version and not the latest version in the dev branch.

When you delete a module there are number of tasks which need to be executed in order to fully remove it from the system:

1. It needs to iterate through all tenants and execute the Uninstall script for the module to remove its tables, etc... from the database
2. It needs to delete all static file resources and assemblies related to the module from the file system.
3. It needs to delete the module definition from the database
4. It needs to restart the web application to remove the module from the app domain

For item 2 above, the system needs to know how to find the static file resources. The only way it can do this is by utilizing an assets.json file which is dynamically created when a module is installed from a Nuget package and contains a list of all files that were deployed. However when you create a module using the Module Creator and compile it in Debug mode, it does not actually create/deploy a Nuget package - it simply copies the DLLs to the Oqtane /bin folder. As a result, no assets.json file is created - which means that when you try to delete the module, none of the static file resources are removed. This also means that when you restart the Oqtane application it automatically re-installs the module because the DLL is still in the /bin folder. There are a few possible solutions... 1. The system could notify the user that the module was not successfully deleted, 2. the system could try to guess the names of the files/folders that need to be deleted - but since there is no naming convention which is enforced in the system it would be reliable and would likely leave orphaned files. My preference is option 1. In addition, when compiling modules you could put Visual Studio in Release mode which will automatically package the module as a Nuget and deploy it to Oqtane - which would create the assets.json file.

For item 4 above, when the application is restarted it terminates debugging in Visual Studio. This is standard behavior which cannot be controlled. Enhancements have been added to the dev branch to make the restart experience more user friendly - basically rather than restarting the application abruptly it now warns the user that they need to restart the app for the changes to take affect and provides a Restart option in the System Settings UI.

**Comment by PhilipMur** [comment]
Hello Shaun,

Yes i am using the official 2.0.0 release version.

I have tried it in release mode and all works as expected.

In debug mode i found all the .dll files i from the no longer used modules and remove them manually and this works as expected also.

Just on item number 4.
Will this prompt be also put in place when creating a module and importing/ installing a module as it has the same effect?

You can close this issue when you want to.

Great work all you developers done on this project, its the way forward.

Thanks for your help @sbwalker and @leigh-pointer

**Comment by sbwalker** [comment]
Yes, all areas which were triggering an abrupt restart have been replaced with a friendly user experience. Thank you for raising the module deletion issue - it definitely could use some improvement to make it more intuitive.

**Comment by sbwalker** [comment]
@PhilipMur see PR #1088 - I was able to significantly improve the module/theme deletion user experience. They no longer require an application restart. In addition, the system will attempt to remove module assets even if an assets.json file does not exist.

**Comment by PhilipMur** [comment]
Very nice addition.
