### ISSUE TITLE
Web Assembly Issue

### ISSUE THREAD

**Issue by PhilipMur** [oqtane/oqtane.framework#1103]
Hello,

If i have the runtime set to "Runtime": "Server" in the appsettings.json file and in the admin control panel, change the site settings to Progressive Web Application Settings and set to Enabled,
I now can install the application via the web browser for the server technology but i can also do this for "Runtime": "WebAssembly"

I thought that web assembly was the model used for progressive web apps ?

Also i cannot enter the admin control panel when i have the runtime set to "Runtime": "WebAssembly" (see screenshot) on first login and you have to reload the entire page manually to get this working again.
Tested in debug, release and installed the app and still all have to be reloaded manually to get the admin control panel to appear when the runtime is set to Web Assembly.

To Recreate the issue.
>>Set the runtime to "Runtime": "WebAssembly" in the appsettings.json file
>>Run the server
>>Login
>>Try to access the admin control panel
>>The admin panel is not visible
>>Manually reload the web page and the admin control panel will now be visible
>>To see the issue again
>>Logout
>>Log back in
>>Try to access the admin control panel
>>Admin panel is not visible once again until a total page reload

![Screenshot (1552)](https://user-images.githubusercontent.com/27295232/107669400-991bfe00-6c89-11eb-9e26-ba8d1e02fd3e.png)

**Comment by sbwalker** [comment]
Just to clarify, WebAssembly and Progressive Web Applications (PWA) have nothing to do with one another - they are completely different technology concepts.

WebAssembly is a new type of code that can be run in modern web browsers — it is a low-level assembly-like language with a compact binary format that runs with near-native performance. Blazor WebAssembly allows you to write full-stack web apps in C# which can run natively in a web browser.

A PWA is an app built with standard web technologies that provides functionality that rivals an actual native mobile app. Using a "service worker" you can turn almost any website into a PWA.

Microsoft included PWA support in its most recent Blazor WebAssembly template - which may have created your confusion. The reality is that the Microsoft Blazor Server template could also be easily enhanced to provide PWA capabilities as well.

I am not able to reproduce the problem you are seeing with the Control Panel when running on WebAssembly. What browser are you using?

**Comment by PhilipMur** [comment]
Thanks for clearing up the Web Assembly question and you are right about where i got mixed up over the Visual Studio Web Assembly Template.

I can reproduce the same issue when the runtime is set to Web Assembly and i have PWA enabled in Oqtane on the following browsers.

Microsoft Edge Version 88.0.705.63 (Official build) (64-bit)
Google Chrome Version 88.0.4324.150 (Official Build) (64-bit)
Firefox Version 85.0.2 (32-bit)
Firefox Developer edition Version 86.0b9 (64-bit)

If I duplicate tab or reload the page the admin panel is visible again once the button is clicked.

**Comment by PhilipMur** [comment]
I found what is causing the issue, its missing a class "app-controlpanel"

>>class="controls ml-md-auto" >> class="controls-group" >> class="app-controlpanel" is missing until its reloaded.

see my screenshot one where its missing and its visible or the other screenshot where i duplicated the tab.

![Screenshot (1557)](https://user-images.githubusercontent.com/27295232/107800062-380e2c00-6d56-11eb-8b61-f4510587e484.png)

![Screenshot (1556)](https://user-images.githubusercontent.com/27295232/107800084-3f353a00-6d56-11eb-9372-0ddb0ccbe16a.png)

**Comment by sbwalker** [comment]
I am using Firefox Developer Edition and I cannot reproduce the problem locally. That being said, I would tend to believe the reason the app-controlpanel class is not being injected is related to the red error message in your web console. The error message says that the call to retrieve the languages for the site is unauthorized ( error 401 ).

**Comment by sbwalker** [comment]
Investigating further, I see the following declaration for the LanguageController GET methods:

        [HttpGet]
        [Authorize(Roles = RoleNames.Registered)]
        public IEnumerable<Language> Get(string siteid) => _languages.GetLanguages(int.Parse(siteid));

        [HttpGet("{id}")]
        [Authorize(Roles = RoleNames.Registered)]
        public Language Get(int id) => _languages.GetLanguage(id);

The Authorize attribute is saying that only users who are authenticated and members of the Registered Users role are authorized to call these APIs. This is not correct. These methods need to be accessible to unauthorized users as well. So this is a bug. Tagging @hishamco so he is aware of this localization issue.

**Comment by PhilipMur** [comment]
A picture tells a thousand words 😂 @sbwalker
I'm glad i attached them now. 

I will remove the authorize from the language controller in a bit and I will report back.

**Comment by PhilipMur** [comment]
I commented out the Authorization attributes and this gets rid of the red 401 for the localisation support but my problem still exists for the non loading of that class to maximise the app-control panel.

That class doesn't exist for me untill I reload.

**Comment by PhilipMur** [comment]
Hello Shaun,

I solved the issue by changing the following in the code.

Oqtane.Client >> Modules >> Admin >>Login >> Index.razor

Go to line 128 and change 
( NavigationManager.NavigateTo(NavigateUrl(_returnUrl, "reload")); )
to
( NavigationManager.NavigateTo(NavigateUrl(_returnUrl, "reload"), true); )

Forcing the reload does the job for me, an easy fix for once.

**Comment by sbwalker** [comment]
I do not feel comfortable making the above code change unless I am able to reliably reproduce the problem you reported. I am trying to understand the differences between my environment and yours. Perhaps the difference is the way you are starting up the application? I am running the application from within Visual Studio - running it on IIS Express. How are you starting up the application?

**Comment by leigh-pointer** [comment]
@PhilipMur try rather than commenting out the the Authorization attributes change the RoleNames.Registered to RoleNames.Everyone

**Comment by PhilipMur** [comment]
@sbwalker iam using Visual studio 2019 Community edition and launching it within Visual Studio using IIS and the startup browser is chrome but I test on a few browsers.
The only way I can prove it's happening at this stage is to record my screen and upload the video which I'm happy to do. 

I will try a published version tomorrow in an iis instance to see if the problem travels with the it or is it visual studio environment and I will report back. 

Is there someone else that can take a fresh copy of the Oqtane server and try recreate the issue with the Web assembly runtime?

@leigh-pointer yes that will work too but a policy for a localisation Get request is probably not needed anyway,
On another topic can you recreate the above issue?

**Comment by sbwalker** [comment]
I believe it is happening based on your screen shots... I just cannot reproduce it myself. The problem seems to be related to the auth cookie not being set properly after login when running on WebAssembly. The framework does contain logic to set the auth cookie on the client. The reason why a browser refresh seems to resolve the problem is because it forces a full application restart on the client ( ie. downloading DLLs and executing startup logic ) which should not be required.

**Comment by PhilipMur** [comment]
Are you using https or http to test?

I'm using http, as i never got around to install a test ssl certificate yet.

**Comment by leigh-pointer** [comment]
@PhilipMur I cant reproduce the issue here.  I have just merged all the latest updates to my fork and still I have no issues.

**Comment by PhilipMur** [comment]
I'm slowly going insane.
All the browsers I have can't all have the same issue with Web assembly loading after login. 

I'm going to take another look to see what's happening.

**Comment by PhilipMur** [comment]
Here is an mp4 that i just recorded.

[2021-02-13 09-20-59.zip](https://github.com/oqtane/oqtane.framework/files/5975398/2021-02-13.09-20-59.zip)

**Comment by PhilipMur** [comment]
OK can anyone reproduce this @sbwalker @leigh-pointer 
I think its part of the same issue where a force reload might be needed or an async event is not been awaited before the site Navigator is been called to reload but something is not been done before the reload is called, for me anyway.

1. Run the application
2. Login
3. Go to the admin control panel and select anyone of the admin controls
4. Logout
5. Edit page and admin control panel still visible with limited functionality.


https://user-images.githubusercontent.com/27295232/107847961-dbf3e800-6de7-11eb-9280-eb084eda00a3.mp4

**Comment by leigh-pointer** [comment]
@PhilipMur  I have reproduce the error! nothing more but thought for your sanity it might be a nice to know.

**Comment by PhilipMur** [comment]
I wonder if what i have encountered is a race condition for the login event?

Maybe you guys have better performing PCs than me or visa versa?

**Comment by PhilipMur** [comment]
Ok so i grabbed my laptop and done a fresh install of Visual studio 2019 community edition and download the repo from github as a zip file and ran the project and i can 100% reproduce the issues, all of them.

**Steps to reproduce.**

1. Install Visual studio 2019 Community
2. Download the Oqtane repo from github as a zip file
3. unzip the project
3. Open the project in Visual studio 2019
4. Rebuild the project
5. Run the project and install Oqtane
6. Login as host and enable PWA in the Site setting menu in the admin control panel.
7. Close the project
8. Open the appsetting.json file and change the "Runtime":"Server" to "Runtime": "WebAssembly"
9. Rebuild the project
10. Login as host
11. Now try to access the admin control panel
12. For me it doesn't open and the class "app-controlpanel" doesnt exist like i mentioned before.

My laptop doesn't have much processing power by the way but my development desktop does.

I'm wondering now is it a race condition of some sorts with your hardware being better or is it a case where your development platform is different than mine.

**Comment by sbwalker** [comment]
I assume when say that you downloaded the code from Guthub, you are referring to the 'dev' branch and not the 'master' branch? The 'dev' branch will have the problem described earlier in this thread where the call to get the Languages will fail for unauthenticated users with a 401 error. This has not been fixed in the repo yet and could cause unexpected issues. Either way, I thin you are correct that there could be a race condition issue. The code which handles login for WebAssembly raises a NotifyAuthenticationChanged() event and immediately does a NavigateTo(). The NotifyAuthenticationChanged() event needs to call the server from the client in order to populate the auth cookie with roles, etc... However NavigateTo() runs on the client and will be executed immediately - which means that the NotifyAuthenticationChanged() may not be finished yet due to latency. I think the login logic needs to wait for the NotifyAuthenticationChanged() event to complete before redirecting. The reason why a full browser refresh solves this problem is because it executes the application startup logic and populates the cookie - but this is not the right solution.

**Comment by PhilipMur** [comment]
I wish its was that simple, but i just applied a task.delay to NotifyAuthenticationChanged then another delay then called NotifyAuthenticationChanged once again but it doesn't change my situation.

I already applied the fix for the language get request 401 issue.

![Screenshot (6)](https://user-images.githubusercontent.com/27295232/107888497-76e1e480-6f04-11eb-919f-cb7d40d670f7.png)

**Comment by PhilipMur** [comment]
OK i have found another issue.

**Steps to reproduce**

1. Login as host
2. Select the private / secure content in the navbar
3. wait until the secure content is displayed
4. Logout
5. The admin controls and authorized only content buttons are still displayed in the navbar.

Im convinced the issue lies in how the content is added and removed from the navbar and all the issues are linked to this.

A work around is let the client download all content and have them hidden until Authorized to view them as API calls will still block access base on a users role and authorization /authorized etc.. if that doesn't open up security issues.

But like i said I am not well read on Blazor or Oqtane framework for that matter.

**Comment by sbwalker** [comment]
#1110 resolves the issue with unauthenticated users being able to retrieve the list of languages. I am not able to reproduce the issue you described above where the secure content is displayed after I logout.

**Comment by PhilipMur** [comment]
It seems I'm all alone on this issue.
I will just force a refresh on my end untill I know how to fix it, I know this will affect performance. 

I can give access to my laptop as its new and I don't have anything on it if you want to see the issue yourself or you can close the issue as it seems its only happening for me.

I can understand that it's impossible to fix a problem you cannot see yourself. 

Thanks for looking in to it, at least you seen and fixed other issue along the way.

**Comment by sbwalker** [comment]
I would like to track this down as @leigh-pointer mentioned above that he was able to reproduce it as well.

**Comment by sbwalker** [comment]
Can you open your browser tools and look in the web console for messages, and look in the network traffic for any requests which are resulting in errors.

**Comment by PhilipMur** [comment]
Console window open beside the server.


https://user-images.githubusercontent.com/27295232/107933364-8ef24c00-6f76-11eb-9f4a-e899d26c1d58.mp4

**Comment by PhilipMur** [comment]
Here is the Network traffic.

https://user-images.githubusercontent.com/27295232/107951431-3cbe2480-6f90-11eb-9614-62ffa186b5bb.mp4

**Comment by sbwalker** [comment]
Good news! I was finally able to reproduce the problem... and I have a solution. So here is the explanation...

After watching your videos I noticed that when you started up Oqtane you were always unauthenticated initially... but in my local environment, I was usually still authenticated because I had not logged out at the end of my previous session. Once I started up the framework in an unauthenticated state I was able to reproduce the problem.

I then noticed that after successful login, authorization was working fine - except for the Control Panel behavior. The app-controlpanel class which you identified earlier was missing. It was not just the class but all of the html markup for the Control Panel is only injected if the Control Panel components meets specific conditions: the list of module definitions are fully loaded from the database, and the user is authorized to edit the page. The second condition was clearly true but the first seemed to be causing the problem - the list of modules was empty. But why? The answer is actually quite straightforward... its related to the Blazor life cycle events. The current Control Panel has the following event:

    protected override async Task OnInitializedAsync()

This event contains some conditional logic to load various entities, including the list of module definitions, based on the permissions of the current user. However this life cycle event is only executed the very first time a component is instantiated for the lifetime of the application. So if the user was already authenticated as host during startup, this component would successfully load the list of module definitions. But if the user was unauthenticated during startup ( the standard scenario ), the component would not load the list of module definitions because they are not authorized. And the problem is that once the user logs in as host, this life cycle method is not re-executed ( because the component is already initialized ). The solution is to  use a different life cycle method rather than OnInitializedAsync:

    protected override async Task OnParametersSetAsync()

This life cycle event is executed during initial component initialization as well as when the component needs to be refreshed due to state changes. A user login is an example of a state change. I changed the event in my local environment and it resolved the problem.

The life cycle events are one of the aspects of Blazor which is confusing to many developers. The OnInitialized event should only be used to execute initialization logic or load state which remains constant for the entire life of the application. In all other cases, the OnParametersSet event is the more appropriate option.

**Comment by PhilipMur** [comment]
Yes I am genuinely happy that you found this issue but its too late i already pulled out all my hair ha ha ha, only joking.

This is great news, hopefully i get an honorable mention and thanks very much for the explanation it helps a lot, i still got my training wheels on for Blazor and Oqtane so any knowledge like this is great.

Well i think its time for a coffee with a we drop of whiskey for celebration.

**Comment by PhilipMur** [comment]
Tested and is working as expected Now. Thanks
