### ISSUE TITLE
Replace ModuleMessage with Toast

### ISSUE THREAD

**Issue by erw13n** [oqtane/oqtane.framework#1119]
First of all, thank you @sbwalker for creating another awesome stuff :) (I'm very exciting)

I just start using Oqtane recently, 
On Site Settings, I didn't notice that it have been Saved not until I scroll the page up.
Due the page to long, the message been hidden until you scroll up.

I modify core control ModuleMessage to show it as Toast.

I'm wonder, is there any way to replace ModuleMessage with our custom Component without modifying core control, that will be part of custom module or theme ?

**Comment by hishamco** [comment]
I think the scrolling issue could be resolved by showing the alert on the top of the page even if the page scolling, I can a push a PR for this if sound looks good to all

Backing to your question the current `ModuleMessage` show/hide an alert div based on some conditions, if you want to replace I think you can trigger the show event of the toast when the `Message` is set

**Comment by sbwalker** [comment]
The way I would prefer to solve this user experience issue is to organize the Site Settings form into Tabs or collapsible Sections so that the form is rendered in a shorter format and the standard module message is visible upon Save. There is no need to introduce a toast or z-index solution which would be inconsistent with the rest of the UX.

**Comment by erw13n** [comment]
Indeed, message not only use for warning/success, but also as info related to the module, which doesn't make sense to make it Toast.
