### ISSUE TITLE
Multiple Layouts and Containers  in a Theme package.

### ISSUE THREAD

**Issue by leigh-pointer** [oqtane/oqtane.framework#1180]
I have created theme project which is a package of multiple themes, layouts and containers.
When I edit a page to apply one of the themes the layouts and the containers of the theme package are repeated by (n) of themes.

On investigation the issue is found in the `LoadThemesFromAssembly (Oqtane.Repository.ThemeRepository)` where by the Load is conducted in a loop and the Layouts and container are add for every theme found.

**Comment by leigh-pointer** [comment]
I am creating a PR for this issue.

**Comment by sbwalker** [comment]
The load behavior is by design. Can you please elaborate on your issue in more detail... perhaps provide some screen shots to explain what you are trying to achieve.

**Comment by leigh-pointer** [comment]
This is the Page Edit page and here you see two themes that reside in the same theme assembly.
![image](https://user-images.githubusercontent.com/9447612/111078103-45087180-84f4-11eb-9d00-da170e48f3b7.png)

Because the themes are loaded in a loop from the assembly the layouts and the containers are loaded twice.

Layouts
![image](https://user-images.githubusercontent.com/9447612/111078231-bb0cd880-84f4-11eb-9c47-54a6b7d66638.png)

Containers
![image](https://user-images.githubusercontent.com/9447612/111078273-e55e9600-84f4-11eb-95d3-2020b57094b8.png)

The load behavior as it stands first loads a theme then all the layouts and containers, and on the next theme iteration loads the layout and containers in the assembly again,

**Comment by sbwalker** [comment]
An assembly can contain multiple themes. A theme needs to have a distinct namespace to associate its various assets together. A theme can have multiple theme files, container files, and (optionally) layout files. Oqtane.Client is a good example of this as it contains 2 themes - the default Oqtane theme and through default Blazor theme. Each theme contains various assets, and they are loaded properly because they follow the conventions. 

Is it possible that you did not group your assets with a distinct namespace?

**Comment by leigh-pointer** [comment]
@sbwalker Ok understand, I have adopted the conventions and things are up and running. thank you.
