### ISSUE TITLE
GetFolderAsync method always adds "/" after the folderPath

### ISSUE THREAD

**Issue by lthoa** [oqtane/oqtane.framework#1197]
**.NET 5.0**
System.IO.Path.DirectorySeparatorChar => return /
System.IO.Path.AltDirectorySeparatorChar => return /

So the GetFolderAsync method always adds "/" after the folderPath:

public async Task<Folder> GetFolderAsync(int siteId, [NotNull] string folderPath)
        {
            if (!(folderPath.EndsWith(System.IO.Path.DirectorySeparatorChar) || folderPath.EndsWith(System.IO.Path.AltDirectorySeparatorChar)))
            {
                folderPath = Utilities.PathCombine(folderPath, System.IO.Path.DirectorySeparatorChar.ToString());
            }

            var path = WebUtility.UrlEncode(folderPath);

            return await GetJsonAsync<Folder>($"{ApiUrl}/{siteId}/{path}");
        }

**Comment by sbwalker** [comment]
I am not sure if I understand the issue you are reporting. .NET Core is cross platform so you can run Oqtane on Windows, Linux, or Mac. Each of those environments has different characteristics when it comes to the file system. In particular DirectorySeparatorChar and AltDirectorySeparatorChar will be different. The code you included above is supposed to handle these differences and ensure the path is in a consistent format - you will notice that the Folder table has a Path field which stores values in the form "folder1\folder\". So in order to match correctly, the value must be in the correct form.

There have been other threads which have discussed the fact that all cross platform environments support the format "folder1/folder2/" so it may be better if Oqtane used this format consistently throughout in order to make it simpler and avoid cross platform conversion logic. This is obviously a significant change and would need to be handled with care in order to not cause a negative impact to existing installations.

**Comment by lthoa** [comment]
This problem from Net5.0. You can see below:

**Same code:**
![image](https://user-images.githubusercontent.com/6874322/112824161-66508c80-90b4-11eb-9485-a57ff64f855f.png)

**Netstandard2.1 result:**
![image](https://user-images.githubusercontent.com/6874322/112825057-7fa60880-90b5-11eb-85ce-90c6fb21e889.png)

**Net5.0 result:**
![image](https://user-images.githubusercontent.com/6874322/112824341-9d26a280-90b4-11eb-8024-7794ce33e841.png)

**Comment by sbwalker** [comment]
My apologies, I am still confused... are you reporting an issue you are experiencing in Oqtane? If so, can you share the steps to reproduce the issue and the error message which is produced? The screen shots above are not from Oqtane - they are from a default Blazor application created from a template. Oqtane 2.0 runs on .NET 5 - not .NET Standard.

**Comment by lthoa** [comment]
Sorry for taking up your time.

In Oqtane when I want to get directory information I call GetFolderAsync (int siteId, [NotNull] string folderPath) method in FolderService.cs. For example: GetFolderAsync (1, "Logos \\"). Before that I created the Logos folder.

In the GetFolderAsync method there is the following code:
if (! (folderPath.EndsWith (System.IO.Path.DirectorySeparatorChar) || folderPath.EndsWith (System.IO.Path.AltDirectorySeparatorChar)))
{
                folderPath = Utilities.PathCombine (folderPath, System.IO.Path.DirectorySeparatorChar.ToString ());
}

The purpose is to check if the folderPath string has a '\\' or '/' character. If not, add a '/' character at the end of folderPath.

Net5.0's error is that it always returns the same '/' when calling System.IO.Path.DirectorySeparatorChar or System.IO.Path.AltDirectorySeparatorChar causing the command
if (! (folderPath.EndsWith (System.IO.Path.DirectorySeparatorChar) || folderPath.EndsWith (System.IO.Path.AltDirectorySeparatorChar))) {
} false when we call GetFolderAsync (1, "Logos \\") while it should be true.

If replaced with
if (! (folderPath.EndsWith ("\\") || folderPath.EndsWith ("/"))) {} then GetFolderAsync (1, "Logos \\") will return true.

Now hope you understand, this is a Net5.0 problem leading to a logic error in Oqtane.

**Comment by sbwalker** [comment]
Thank you for explaining... this Github issue provides some more context about the breaking change:

https://github.com/dotnet/runtime/issues/44744

The one thing which is still not clear to me is whether this is only a problem when running on WebAssembly or if it is a problem when running on Server as well?

**Comment by lthoa** [comment]
This problem when running on WebAssembly only.

**Comment by sbwalker** [comment]
This problem does not manifest itself anywhere in the core framework because the GetFolderAsync(int, string) method is not currently used by the admin UI - it was added for developers who are creating custom modules ( although the recommended approach in general would be to use the FileManager UI control to allow a user to choose a folder for which they have the necessary permissions rather than introduce hard-coded folders ). 

I believe the simple solution here is to avoid doing any file path manipulation in the Client - as the behavior will differ depending on whether the Client is running on Blazor Server or Blazor WebAssembly.  Path manipulation should always be done on the server. I will migrate the logic from GeFolderAsync to the Folder Controller method.
