### ISSUE TITLE
ModuleCreator - Creating module in production Enviroment

### ISSUE THREAD

**Issue by leigh-pointer** [oqtane/oqtane.framework#1211]
Module was not created and log shows this error.

```
System.NullReferenceException: Object reference not set to an instance of an object.
   at Oqtane.Modules.Admin.ModuleCreator.Index.CreateModule() in C:\Users\Shaun.Walker\source\repos\sbwalker\oqtane.framework\Oqtane.Client\Modules\Admin\ModuleCreator\Index.razor:line 123
```

**Comment by sbwalker** [comment]
Which version of Oqtane are you running in production? Did you use the Internal or External module template?

**Comment by leigh-pointer** [comment]
@sbwalker it oqtane 2.0.1 (Oqtane.Client, Version=2.0.1.0,)  and was both External and Internal templates

**Comment by sbwalker** [comment]
The Module Creator was not intended to be used in production. The External template scaffolds the assets in a folder which is outside of the Oqtane root folder - and production hosting environments will explicitly forbid this. The Internal template scaffolds the assets within the Oqtane root folder however they would need to be compiled into the Oqtane assemblies in order to make them active - which is also not possible in a production hosting environment.  

Why are you trying to use the Module Creator in production?

**Comment by leigh-pointer** [comment]
>Why are you trying to use the Module Creator in production?

Basically exploring the functionality in production.

**Comment by sbwalker** [comment]
Ok, the only thing I can suggest is that we add a message to the top of the Module Creator module which says "The Module Creator Is Not Intended To Be Used In Production Environments"

**Comment by leigh-pointer** [comment]
Would it not be better to hide the functionality altogether.

**Comment by sbwalker** [comment]
There is no identifier to know if you are running in production or development. Developers use host file entries to point domain names to their development environment.
