### ISSUE TITLE
Selected Page Layout not honored

### ISSUE THREAD

**Issue by ADefWebserver** [oqtane/oqtane.framework#125]
To reproduce:

1) Log in as Host and create a new page
2) Select "horizontal layout"
3) When viewing the page, click the pencil icon to see the layout, it will say Top Pane / Bottom Pane and the database will be set to **Left;Right**
4) Change the layout to "vertical layout"
5) When viewing the page, click the pencil icon to see the layout, it will say Top Pane / Bottom Pane and the database will be set to **Top;Bottom**

**Comment by sbwalker** [comment]
This issue is resolved in the latest PR. It actually highlighted an architectural problem with the earlier approach being used for panes where the list of panes was being persisted to the Pages table for convenience however this created the potential for the list of panes to no longer match a theme if it was modifed. The new approach gets the list of panes from the theme dynamically.
