### ISSUE TITLE
Ui Bug (Minor): tab switching needs two clicks after editing a field

### ISSUE THREAD

**Issue by iJungleboy** [oqtane/oqtane.framework#1305]
If I want to add a page I see this:

![image](https://user-images.githubusercontent.com/5321186/116776980-fc892100-aa6b-11eb-9ab7-1131ba4a220e.png)

If I now click on permissions it works, the tabs switch. 

But if I edit the name of the page and click on permissions, nothing happens. I have to click a second time for permissions to show. 

If I leave the field first (tab away) and then click on  permissions, it works. 

Not sure if this is a Blazor issue or Oqtane, but my guess is it has something to do with validation of the field which somehow prevents the tab switch until a validation cycle has completed

**Comment by sbwalker** [comment]
This is actually a more challenging problem than it appears... it does not have anything to do with validation - it is related to Blazor component rendering when the state has changed. @leigh-pointer's solution seems to address the symptoms rather than the cause, but it may be viable solution - I will test various scenarios.

**Comment by sbwalker** [comment]
I found the root cause and addressed in #1310. It was related to the collection of TabPanels being initialized and rebuilt on every re-render of the component. There are only a few scenarios where this is necessary so I introduced a new property specifically for those scenarios. It seems to be working as expected now... please test.

**Comment by leigh-pointer** [comment]
@sbwalker I have test and the issue is resolved.

**Comment by iJungleboy** [comment]
Awesomeness! 🎉
