### ISSUE TITLE
UseOqtaneDatabase() with databaseType Throws an exception

### ISSUE THREAD

**Issue by hishamco** [oqtane/oqtane.framework#1317]
While I'm working on #1238 I notice that the `UseOqtaneDatabase()` throws an exception because databaseType in my case `LocalDB` returns null in the line

```csharp
var database = Activator.CreateInstance(type) as IOqtaneDatabase;
```

This is happend because the type is `null` I think the solution is to look through the oqtane assemblies for `IOqtaneDatabase` assemblies to get the proper type

/cc @cnurse

**Comment by hishamco** [comment]
I already did something like 

```csharp
var assemblies = AppDomain.CurrentDomain.GetOqtaneAssemblies();
var databaseTypes = assemblies.Where(a => a.GetInterfaces<IOqtaneDatabase>().Any()).SelectMany(a => a.GetTypes());
```

**Comment by sbwalker** [comment]
@leigh-pointer @hishamco do you have a DatabaseType defined in your appsettings.json file:

```
{
  "Database": {
    "DatabaseType": "LocalDB"
  },
```

**Comment by leigh-pointer** [comment]
My type is SqlServer

**Comment by sbwalker** [comment]
Are you trying to do an interactive installation where the ConnectionString is blank to start?

**Comment by leigh-pointer** [comment]
No this install has been running for a few weeks now.  This is the first time i have installed a custom module.  

So everything is running fine.  I installed the sat lang package which went as expected.
I then added the lang resources to the solutions 
rebuilt
Installed my module and added an instance to a page.
When the module tries to get data from db error

![image](https://user-images.githubusercontent.com/9447612/117299534-f08ccd00-ae78-11eb-84c3-e618d8099495.png)

**Comment by sbwalker** [comment]
Thank you for the context - it was impossible to understand how to reproduce the issue from the original post. I thought this was an issue related to installing Oqtane. However it is actually an external module compatibility issue. The goal was to ensure that the multi database changes in 2.1 do not break any external modules so we will need to investigate this further. @cnurse

**Comment by sbwalker** [comment]
@leigh-pointer did your external module use the Module Creator template as its basis?

**Comment by leigh-pointer** [comment]
Yes, nothing has strayed from the standards only functionality build upon.

I can run this test with a standard click and build from the template if it helps?

**Comment by hishamco** [comment]
> @leigh-pointer @hishamco do you have a DatabaseType defined in your appsettings.json file:

Yes

**Comment by hishamco** [comment]
Same exact error that @leigh-pointer was shown above, the origin for the bug because the Type will returns `null` because they are in different assemblies

**Comment by sbwalker** [comment]
@hishamco you are correct that the exception is being thrown because the type does not exist in the external module assembly. The standard approach in Oqtane is to always use fully qualified type names so that the system knows which assembly the type belongs to. So I think the proper solution is that the typename should be fully qualified ie. rather than "LocalDB" it should be "Oqtane.Repository.Databases.LocalDbDatabase, Oqtane.Database.SqlServer". Does this make sense @cnurse ?

I also noticed that the naming of the various databases is inconsistent - is this on purpose:

![image](https://user-images.githubusercontent.com/4840590/117450577-680d3b80-af0f-11eb-887f-e47f8452bd4d.png)

**Comment by hishamco** [comment]
I didn't have a deep look to hos @cnurse maps the database types to the actual `IOqtaneDatabase` types, for me I fix the issue but I'm waiting for @cnurse to explain everything before I submit a PR. Frankly I don't wanna break anything he did before ;)

**Comment by sbwalker** [comment]
This is why I did not submit a PR yet either... although I believe the right solution is to use fully qualified type names ( so that it is explicit and consistent with the rest of Oqtane ).

**Comment by hishamco** [comment]
>  I believe the right solution is to use fully qualified type names

Exactly, if I'm presume this happening after moving SQL Server into another project, I'm 100% sure there's something wrong with other database while they are already in a separated projects

Waiting for Charles ...

**Comment by cnurse** [comment]
Sorry - I have been "offline" for a few days (babysitting grandson :) ) - I will look into this.  The naming consistency issue is un-intended, and I think it was due to files being moved around and namespaces not being updated.

**Comment by cnurse** [comment]
@sbwalker is correct.  The issue is due to the fact that these external modules are not "aware" that there are multiple databases.  The DBType field was just using the name of the provider as defined in its Name property.  This can be seen from the alternate call in DbContextBase

![image](https://user-images.githubusercontent.com/1753708/117886303-d3cf0b80-b263-11eb-811f-bf298093b671.png)

With Modules that are not aware of multiple databases the Databases collection is null, so they fall down to the else clause, which "incorrectly" assumes that _databaseType is actually a valid Type name.

As Shaun correctly mentions the Name property of the database as well as the DBType field in both appsettings.json and the tenant record should be the fully-qualified typename.  In this way the

**Comment by cnurse** [comment]
I have submitted a PR for this issue (PR #1342 )
