### ISSUE TITLE
Edit Bug: Can't have empty module title

### ISSUE THREAD

**Issue by iJungleboy** [oqtane/oqtane.framework#1319]
If you edit a module settings to clear the title, the UI works and the page shows the module without a title. 

A full refresh will actually show the title again. 

So I guess there is a bug somewhere saying if the title is saved as empty, it doesn't actually save it. 

Goal: Empty title should be possible.

**Comment by sbwalker** [comment]
A module title is mandatory ( the PageModule database table field for Title is non-nullable ). Whether or not the title of a module is displayed in the UI is a completely different use case - it is determined by the Container ( the default Container in the Oqtane Theme has an option so that the user can specify if the title should be displayed ).

**Comment by iJungleboy** [comment]
That's fine with me - but then the edit-UI shouldn' allow me to save an empty title and result in a updated page with an empty title.

As of now that's what happens, until I hit refresh when the title reappears.
