### ISSUE TITLE
Errors in New Module templates

### ISSUE THREAD

**Issue by leigh-pointer** [oqtane/oqtane.framework#1415]
When selecting Framework version 2.0.2 module created is not compatible with 2.1.0

**Comment by sbwalker** [comment]
the new module template relies on features in 2.1.0

**Comment by sbwalker** [comment]
You do raise a good point in this issue though as the Module Creator UI allows you to select from a list of versions - not all of which are compatible with the template. It seems there needs to be a way for a template to indicate the minimum version it supports. The simplest solution would be to specify it as part of the template folder name

**Comment by leigh-pointer** [comment]
@sbwalker was think about that myself. I think for simplicity, the best way would be to use the folder name.

**Comment by sbwalker** [comment]
@leigh-pointer see #1425 which adds support for a template.json file for a module or theme template - this enhancement provides a number of benefits including friendlier naming of templates in UI, specifying minimum framework version compatibility, indicating if a template is External or Internal, and providing the server root location so that the Client no longer needs to reference System.IO or SystemInfo service.
