### ISSUE TITLE
Module creator - choose where to create files

### ISSUE THREAD

**Issue by rodrigoratan** [oqtane/oqtane.framework#1539]
![image](https://user-images.githubusercontent.com/964066/124656201-44b32e00-de77-11eb-98bb-b24806edebf6.png)

My oqtane installation is at C:\inetpub\vhosts\ratan.com.br\oqtane.ratan.com.br , I know it's supposed to run in "development environment" but this site is just a test, it's not 'production'.. When I try to create a module it wants to save at 
C:\Inetpub\vhosts\Ratan.MyFirstModule outside of my 'ratan.com.br' that is the parent folder of the website... It would be nice have the option to choose where to save...

**Comment by sbwalker** [comment]
The default module template is named "external" because it is intended to be physically separate from the Oqtane framework installation - which is why it is created at the same folder level as the Oqtane framework and not within the Oqtane framework parent folder. The Module Creator relies on a folder structure convention in order to generate the correct relative paths within the various assets which are created.

**Comment by rodrigoratan** [comment]
ok, I understand, I was thinking in a option to save it anywhere else and have the option to download it, but it's Ok as it is now too... thanks!
