### ISSUE TITLE
Unable to create new user; 

### ISSUE THREAD

**Issue by leigh-pointer** [oqtane/oqtane.framework#1557]
fails in the `Task<User> CreateUser(User user)`

**Comment by sbwalker** [comment]
Is this during install or after the framework has been installed? Have you looked in the Event Log - is there an error recorded? This might be related to the user.SiteId not being set before CreateUser is called.

**Comment by leigh-pointer** [comment]
@sbwalker after the framework is installed.

User Management.
One issue appear the validity of the email address.  leigh.pointer@studio-elf.ga didnt work where as outlook.com did.

Register new user, using a valid email "outlook" 
![image](https://user-images.githubusercontent.com/9447612/125815015-aa2f56e3-1b72-485d-8926-7f0d48624f28.png)

**Comment by sbwalker** [comment]
I am unable to reproduce this problem. I successfully registered a user locally using the username and email address you included above in your screenshot. This would lead me to believe that the problem is with some other data used to create the user - most likely the password. Oqtane relies on the .NET Core Identity rules for password validation - which are defined in the ConfigureOqtaneIdentityOptions() method:

                options.Password.RequireDigit = false;
                options.Password.RequiredLength = 6;
                options.Password.RequireNonAlphanumeric = false;
                options.Password.RequireUppercase = false;
                options.Password.RequireLowercase = false;

Did you use a password which was 6 characters or larger?

**Comment by nicpitsch** [comment]
I can confirm one problem regarding the validity of the email address: the new user registration fails if the e-mail contains a hyphen (-).

**Comment by sbwalker** [comment]
So this issue appears to be related to default behavior in .NET Core Identity:

https://stackoverflow.com/questions/26726750/identity-email-with-dash-in-asp-net-identity
