### ISSUE TITLE
Installation should not default username

### ISSUE THREAD

**Issue by mitchelsellers** [oqtane/oqtane.framework#1568]
Looking at things from a security focus the system should not force a common username for all installations.  By doing this it makes the possibility of exploitation easier giving 1/2 of the needed solution to a malicious actor. 

I'm willing to contribute the needed changes to make this configurable as part of the installation process, just want to be sure that it is agreed upon.

**Comment by sbwalker** [comment]
The reason why the host username is static currently is because the UserController AddUser API relies on it to determine if the system is allowed to create the user account anonymously during tenant creation. This is a tricky scenario as in all normal cases the AdUser API must be restricted to authorized users - but there is this one specific use case during the initial installation where the user is not authorized ( because no users exist yet ) and the system needs to be able to recognize the scenario and allow the creation of the user. This challenge is related is to the client/server architecture - as the front-end and back-end and independent. In order to find an alternate solution you would need to ensure you are running the system on Blazor WebAssembly to ensure you are testing a true client/server environment. This will also impact the Add Site/New Tenant functionality as it requires the user to authenticate the host user account before allowing the creation of a new tenant ( and it currently relies on a static username as well ). I guess what I am saying is that on the surface this appears that it should be a simple item to enable - but it is a "tip of the iceberg" type of problem.

**Comment by thabaum** [comment]
Could there be a popup page when the initial first host login occurs to force changing the username to something other than default?

**Comment by sbwalker** [comment]
The system currently does not have the ability to change a username.

**Comment by thabaum** [comment]
I believe the ability to change usernames would be a good feature to have in my opinion.
Possible work around.

Create a new user upon first login and disable the initial host.

**Comment by thabaum** [comment]
From a security view I do agree however not having this feature ability.  It would have to be limited to roles and only be able to apply things to roles it has power to use such.  Possible a custom module.

Also for developers you would not be in need to worry about if running on localhost so maybe a switch option asking if production or development (Localhost) but if switched to production a recommendation to do certain steps to do above as a security precaution.

**Comment by JustCallMeAD** [comment]
> there is this one specific use case during the initial installation where the user is not authorized ( because no users exist yet )

Why not just check to see if the database or any users exist? If there is no database or users, then the first user created must be the host user and can be created anonymously.

> This will also impact the Add Site/New Tenant functionality as it requires the user to authenticate the host user account before allowing the creation of a new tenant ( and it currently relies on a static username as well )

Instead of checking for the static "host" username you could check to see if the user creating the site/tenant is in the host users role.

**Comment by sbwalker** [comment]
this is fixed in #1592 and all install/site creation scenarios have been tested
