### ISSUE TITLE
Logout is not working for Multiple Sites / Tenants

### ISSUE THREAD

**Issue by Sharafudeen** [oqtane/oqtane.framework#1576]
Hi,

**Issue:**
I've two sites. One is default Oqtane **_localhost:44357_** and another site with alias of **_localhost:44357/helpdesk_**.
Since Oqtane using same Host user for both sites, I'm trying to logout from 1st site and it is not logged out of another site in a different browser window or tab. I've to refresh page for another site to logout. I understood this is because of Oqtane is Blazor/SPA framework?!

**Expectation:**
It should be logged out of all sites if the host user is same.

**Comment by sbwalker** [comment]
Logout is in fact working fine - the auth cookie is being removed for the user... however the UI in the second browser instance is not automatically refreshed when this happens. This is the standard behavior in most web applications and it has nothing to do with Oqtane, Blazor, or authentication. If I was managing the page settings for the Home page in one browser instance and then opened the page settings for the Home page in  second browser instance... and I made a modification in the first browser instance and selected Save, the information in the second browser instance would not automatically be updated - the user would need to manually refresh the second browser instance to see the changes. This is by design. It is certainly possible to create a system where updates are reflected in real-time across all active UIs - however the overhead and performance impact of this capability is very significant which is why it is not generally used unless an application absolutely requires it.

**Comment by Sharafudeen** [comment]
@sbwalker I don't know my suggestion may be good practice.. Can login information for the users will be in SignalR? If the user login or logout and it will refresh all connected clients (browsers)?

**Comment by sbwalker** [comment]
I would prefer to not pursue a modification to enable real-time updates for all connected clients as it would impact the overarching performance goals which are outlined in the Oqtane philosophy https://www.oqtane.org/Resources/Blog/PostId/538/oqtane-philosophy

**Comment by Sharafudeen** [comment]
@sbwalker Thanks for sharing the details. I really love Oqtane's project structure and core features and it's principles. I've analysed most of the multi-tenant or SaSS frameworks in the internet and I've found no-one can beat Oqtane's core features and principles. I hope Oqtane will be dominated these decades.
