### ISSUE TITLE
PostgreSQL installation error

### ISSUE THREAD

**Issue by Kemaletdin** [oqtane/oqtane.framework#1659]
Hi,

I just tried to install Octane 2.2 on my macOS with VS 2019 .NET 5 and PostgreSQL 10

I get this error after clicking "Install Now"

42804: column "is_clickable" is of type boolean but expression is of type integer

thanks

**Comment by sbwalker** [comment]
this was reported previously in #1603 and a PR was submitted to resolve the issue - however the PR broke the installation for other databases ( ie. SQL Server ) so the commit had to be rolled back. So this is still an open issue related to how to deal with the boolean type across multiple database platforms in generic manner.

**Comment by sbwalker** [comment]
I believe this is resolved in #1671. I added a new RewriteValue method which can be overridden in a database provider to provide custom behavior. I updated the PostgreSQL provide to utilize new method. In order to test this you will need to build the Oqtane.Databases.sln in Release mode ( so that it creates the new database provider packages and installs them ). This issue also exposed that there was no automated way to upgrade the database providers for each release - and this has been fixed as well.
