### ISSUE TITLE
Error running Oqtane (with Blog module)

### ISSUE THREAD

**Issue by bryfa** [oqtane/oqtane.framework#1672]
![image](https://user-images.githubusercontent.com/8579202/133883609-f63d1120-9846-4db1-be1b-5239fc32735c.png)

**Comment by bryfa** [comment]
The error log seems to have no errors.

**Comment by bryfa** [comment]
It happened after installing the blog and after updating my server. Tried to do a clean install, it shows the initial database setup screen. So I think this has to do with inner workings or module config and Oqtane

**Comment by bryfa** [comment]
Seems that the server settings works so it has to do with Blazor config, will try to install the hosting bundle again

**Comment by bryfa** [comment]
Ok it has to do with the Blog module. Added a new installment of Oqtane and installed the blog module. After that I get the message above.. Any help would be great on how to remove it properly.

**Comment by sbwalker** [comment]
which version of Oqtane? which version of the Blog module? Which hosting model?

**Comment by bryfa** [comment]
Latest versions 5.0.10 and when running I choose the Blog module on the import install page..

**Comment by bryfa** [comment]
Also tried to install the bootswatch themes. Same error as above. I am using SqlServer (Exrpess)

**Comment by sbwalker** [comment]
I was actually wanting to know the version of Oqtane - are you using the 2.2.0 release or the latest code from the Dev branch? And which Blazor hosting model - Server (default) or WebAssembly?

**Comment by bryfa** [comment]
WebAssembly

**Comment by sbwalker** [comment]
Sorry for all of the question but its impossible to track down issues unless they can be reproduced locally - and this usually requires matching the exact configuration of the environment where the issue is occurring. So just to be 100% clear - you downloaded the 2.2.0 release binaries from the right-hand option displayed below - you did NOT download a zip from the left-hand option ( ie. the Dev branch )?

![image](https://user-images.githubusercontent.com/4840590/134174214-39bdb8bb-8d31-4e86-a47d-808798c16b07.png)

**Comment by bryfa** [comment]
https://github.com/oqtane/oqtane.framework/releases

**Comment by sbwalker** [comment]
I am able to reproduce... and the behavior is interesting. When running Oqtane on WebAssembly within Visual Studio and in Debug mode, the Blog module works fine. However when running Oqtane on WebAssembly on IIS using a Published Release build, the Blog module causes the error. The error message seems to be indicating that the app is trying to use reflection to load some types and a dependency is missing - ie. a DLL has not been loaded into the browser's app domain. My gut feeling is that this is related to .NET 5 and assembly trimming. From the Microsoft docs: "Trimming is utilized when publishing an application. It removes IL that is not statically reachable. Apps that use reflection or other patterns that create dynamic dependencies may be broken by trimming.". More research will be necessary to track this down.

**Comment by sbwalker** [comment]
@bryfa after a lot of investigation and testing, I can confirm this is related to the linker in .NET 5. I have checked in a change which resolves the issue. In order to test it, you will need to use the release.cmd in the Oqtane.Package folder to create a new Install.zip package - and then deploy that package.

**Comment by sbwalker** [comment]
This is a great link to learn about trimming: https://devblogs.microsoft.com/dotnet/app-trimming-in-net-5/

**Comment by bryfa** [comment]
Ok will do that asap and will look into the link! Thanx for the help.
