### ISSUE TITLE
Make a Deploy to Azure Button

### ISSUE THREAD

**Issue by ADefWebserver** [oqtane/oqtane.framework#168]
[![Deploy to Azure](https://azuredeploy.net/deploybutton.png)](https://azuredeploy.net/)

Create an **azuredeploy.json** that can be placed in the **README.md** file of the [oqtane/oqtane.framework](https://github.com/oqtane/oqtane.framework) **GitHub** site to allow users to easily deploy **Oqtane** to **Azure** and install it.

- [Latest Deploy To Azure Docs 2-7-2020](https://docs.microsoft.com/en-us/azure/azure-resource-manager/templates/deploy-to-azure-button)
- [Deploy to Azure Button for Azure Websites](https://azure.microsoft.com/is-is/blog/deploy-to-azure-button-for-azure-websites-2/)
- [Azure Resource Manager documentation](https://docs.microsoft.com/en-us/azure/azure-resource-manager/)
- [Azure Editor on portal.azure.com (for creating custom templates)](https://portal.azure.com/#create/Microsoft.Template)
- - [Deploy a app service plan and a basic Windows web app](https://github.com/Azure/azure-quickstart-templates/tree/master/101-webapp-basic-windows)
- - [Azure Resource Manager QuickStart Templates](https://github.com/Azure/azure-quickstart-templates)

**Comment by hishamco** [comment]
Any plan to implement this?

**Comment by ADefWebserver** [comment]
I have this working in Blazor Blogs. https://blazorblogs.azurewebsites.net/ViewBlogPost/1008 waiting for the go ahead from @sbwalker because as with most things there are "issues". 

Oqtane would need to be adjusted to recognize when the database connection works but the database is not set up. Thees are changes that @sbwalker may not want to make because there can be security implications.

**Comment by ADefWebserver** [comment]
Here are the "Issues" I think that need to be resolved to move forward on this effort:

You can see how I addressed these issues with Blazor-Blogs at this link: https://github.com/ADefWebserver/Blazor-Blogs/tree/master/BlazorBlogsLibrary/Pages/InstallUpgrade

**1. We can move forward now with creating a tutorial like this: [Installing Blazor-Blogs on Microsoft Azure (Manual Method)](https://blazorblogs.azurewebsites.net/ViewBlogPost/1007)**

-  a) We need to do this anyway, even if we have a "Deploy To Azure Button"
-  b) Basically it is just a "Blog Post"
-  c) I can work on this, just let me know

**2. For the "Deploy To Azure Button" to work with Oqtane, we need to address the following 'challenges' I encountered with [developing it for Blazor-Blogs](https://blazorblogs.azurewebsites.net/ViewBlogPost/1008)**
-  a) The Azure ARM template will write the database connection string to the Azure App Service configuration, not the appsettings.json file. The Oqtane application _startup code_ and the _Installation Wizard_ need to be checked to ensure that they still operate as expected.
-  b) The Installation Wizard cannot expect the user to know the location of the database and the username and password for the database. The Azure ARM template will create the database and put this in the Azure App Service configuration. The Installation Wizard will need to detect it there, when it exists. 

**3. Creating the Administrator account is 'problematic' because it can't be created until the database is set-up, but, there 'could' be errors setting up the database.**
-  a) In Blazor-Blogs I basically ended up having code that first detected that the database was set up or not, and ran the scripts to create it, then directed the Installation Wizard to re-start and detect if everything was set-up but the administrator account was not created (and then allowed you to create it). This required a significant re-architecting of the code for the application.

**Comment by ADefWebserver** [comment]
I tried to create installation directions 
[InstallingOqtane.docx](https://github.com/oqtane/oqtane.framework/files/4670945/InstallingOqtane.docx)

1. The install .zip package will not install on Azure
2. Even if publish to Azure directly from Visual Studio it comes up as a blank page :(

I could look into this further but it could take a few days. I would not want to start on this without the go ahead because this may require major re-working to resolve.

Let me know, Thanks!

**Comment by R-Lamberson** [comment]
@ADefWebserver I was able to get it to deploy into Azure - using the standard application service, however using an azure devops deployment pipeline.  I used dotnetcli for the build commands instead of msbuild and I was able to get most of it work.  The UI is loading up but I am still seeing some wonkiness because the content is out of sync between what was my local setup and the server

**Comment by sbwalker** [comment]
@R-Lamberson are you able to provide any more info? The goal we need to achieve is to be able to install the standard Oqtane installation package https://github.com/oqtane/oqtane.framework/releases/tag/v1.0.0

**Comment by sbwalker** [comment]
I am going to create a new issue as this item is focused on a Deploy to Azure button - whereas the short term goal is to simply be able to deploy the install package to Azure. And perhaps by putting it at the top of the list it will get more attention ;)

**Comment by R-Lamberson** [comment]
@sbwalker got it, so what I am trying to achieve is a setting up a hosted development environment so that I have the CI/CD pushing the github repo's latest updates to that so that may be a bit different from the overall goal.  What I am seeing is broken image links for images that I added in my local dev environment and are now disconnected since the content did not deploy, also when I attempt to go to the admin dashboard - I get the settings flyout sidebar but when I click on Admin Dashboard it goes nowhere - and I see this in the javascript console - _There was an unhandled exception on the current circuit, so this circuit will be terminated. For more details turn on detailed exceptions by setting 'DetailedErrors: true' in 'appSettings.Development.json' or set 'CircuitOptions.DetailedErrors'   I just found that so I will turn it on and see what details it provides

**Comment by ADefWebserver** [comment]
@R-Lamberson Can you join the discussion at: https://github.com/oqtane/oqtane.framework/issues/545
Thanks!

**Comment by sbwalker** [comment]
@ADefWebserver I think @R-Lamberson is working on a totally unrelated use case and it may be best to either create a new issue or discuss here - #545 is not related to CI/CD deployment.

**Comment by sbwalker** [comment]
@R-Lamberson when you add content to a local installation, it is being stored in the local database as well as the local file system. It would be up to you to determine how to synchronize this content with your remote Oqtane installation - it is outside the scope of the Oqtane framework. You will need to to use some type of third party solution I believe to synchronize data between databases, and perhaps a different solution to synchronize the files in the /Content folder.

**Comment by R-Lamberson** [comment]
@sbwalker I am sharing the db between the local environment and the hosted environment - given that I shouldn't have to sync the content correct?

**Comment by sbwalker** [comment]
when you upload files they are not stored in the database - they are stored on the file system in the /Content folder. So you will need to sync these files between environments. And if you install third party modules/themes they will be installed as DLLs in the /bin and static assets under /wwwroot - so you would need to manually sync these files as well because they are not statically linked to the Oqtane.Server project and therefore will likely not be included in a standard Publish process

**Comment by ADefWebserver** [comment]
> ...when I attempt to go to the admin dashboard - I get the settings flyout sidebar but when I click on Admin Dashboard it goes nowhere - and I see this in the javascript console - _There was an unhandled exception on the current circuit, so this circuit will be terminated. For more details turn on detailed exceptions by setting 'DetailedErrors: true' in 'appSettings.Development.json' or set 'CircuitOptions.DetailedErrors' I just found that so I will turn it on and see what details it provides

@R-Lamberson I reproduced that here: https://github.com/oqtane/oqtane.framework/issues/546

**Comment by ADefWebserver** [comment]
Created PR: https://github.com/oqtane/oqtane.framework/pull/657

**Comment by ADefWebserver** [comment]
I attached directions to use the Deploy to Azure button with Oqtane
[Oqtane Deploy to Azure.docx](https://github.com/oqtane/oqtane.framework/files/4956136/Oqtane.Deploy.to.Azure.docx)
