### ISSUE TITLE
User Management Tab needs clicking to render UI when language is not default.

### ISSUE THREAD

**Issue by leigh-pointer** [oqtane/oqtane.framework#1690]
In the User Management section the ui is not rendered until the tab is clicked.  This appears only to happen when the language is not the default.

![image](https://user-images.githubusercontent.com/9447612/134758858-cb2bf7d4-a71d-4926-a77c-f208f148cb92.png)

![image](https://user-images.githubusercontent.com/9447612/134758908-4824af46-f734-4109-a90d-b36c89e778dd.png)

**Comment by sbwalker** [comment]
This is because the TabStrip and TabPanel controls rely on the Name parameter value to set the default tab... and it appears that the localization logic is modifying the Name parameter value. The proper solution would be to not modify the Name parameter and use a local variable instead to assign the localized Name and display in the UI.

**Comment by leigh-pointer** [comment]
I will fix it

**Comment by sbwalker** [comment]
fixed in #1701
