### ISSUE TITLE
Modules will not Save or Delete data.

### ISSUE THREAD

**Issue by leigh-pointer** [oqtane/oqtane.framework#1691]
There seems to be a issue with saving of data and deleting module item entries.

I tested this on my modules in the framework and from swagger and also using the internal HTML module to verify its global and not down external modules.

![image](https://user-images.githubusercontent.com/9447612/134767197-83da0a82-0bd9-4f15-a279-5563b0f8b2ea.png)

**Comment by sbwalker** [comment]
@leigh-pointer thank you for reporting this issue. This is indeed a regression bug... caused by the refactoring done to fix #1640. The root problem is that the HTML module ( and external modules created with the Module Creator template ) have an additional layer of security in their Controllers - they use [ValidateAntiForgeryToken] in their Add/Update/Delete methods. This is dependent upon the AntiForgeryToken header being set at application startup. The startup logic is complex due to the very specific order in which various events need to occur to satisfy installation, pre-rendering, initialization requirements.

**Comment by sbwalker** [comment]
@leigh-pointer this regression issue is impactful enough that it will require a 2.3.1 ( as there is no way to replace the 2.3.0 packages on Nuget.org ).
