### ISSUE TITLE
Error when install framwork on SQL db

### ISSUE THREAD

**Issue by beolafsen** [oqtane/oqtane.framework#1746]
Tried to install Oqtane on a SQL server. Have done that on the same sql server before - but now I got this error:
(OK installation on LocaleDB)

**_A connection was successfully established with the server, but then an error occurred during the login process. (provider: SSL Provider, error: 0 - The certificate chain was issued by an untrusted entity_**

![image](https://user-images.githubusercontent.com/76835718/139521211-169c7802-1403-4bdf-9f74-c3003c6acdf1.png)

**Comment by sbwalker** [comment]
Microsoft seems to have introduced some breaking changes in .NET 6 related to enabling “Encrypt” by default. I was unable to install Oqtane on LocalDB on .NET 6 until I added Encrypt=false to the connection string. Here is a related thread:

https://github.com/dotnet/SqlClient/pull/1312

It appears there is a new version of SqlClient available v4.0.0-preview3.21293.2 - perhaps this will resolve the issue.

**Comment by sbwalker** [comment]
Oqtane has been upgraded to latest SqlClient v4.0.0-preview3.21293.2 - please try again. It is possible that Encrypt=false may still need to be added in order to get this to work.

**Comment by sbwalker** [comment]
On Aug 25, 2021 Microsoft included this item in the release notes for Microsoft.Data.SqlClient 4.0.0-preview1.21237.2:

"Encrypt default value set to true

The default value of the Encrypt connection setting has been changed from false to true. With the growing use of cloud databases and the need to ensure those connections are secure, it's time for this backwards-compatibility-breaking change."

Currently Oqtane does not provide an explicit value for encryption in the connection string - which means it now defaults to true on .NET 6 and if your database server is not configured to support encryption it will likely result in errors. I believe the solution is to add an option to the SQL Server configuration component so that the user can specify if they wish to use encryption. This option would not be required for LocalDB as it does not support encryption.

**Comment by sbwalker** [comment]
problem should now be resolved - get the latest code and try an installation on SQL Server and specify False for the new Encryption option that was added to the installation UI.

**Comment by beolafsen** [comment]
It works fine now'

**Comment by sbwalker** [comment]
Microsoft recommended also adding a SQL Server config option for Trust Server Certificate - which is described here:

https://docs.microsoft.com/en-us/sql/relational-databases/native-client/features/using-encryption-without-validation?view=sql-server-ver15

So I will add this as well.
