### ISSUE TITLE
Improve Server-Side Connection between Client and Server

### ISSUE THREAD

**Issue by iJungleboy** [oqtane/oqtane.framework#1843]
I have a complex request, but I believe it's crucial to the success of Oqtane, as I've seen various cases where these problems already caused issues getting started. 

## Background

Blazor is modeled to separate the client from the server, and have full .net capabilities in the client. In the WASM world (.net on the browser) the idea is that this would apply:

1. The browser runs .net as WASM - for example on mysite.org
2. Requests to the server happen through WebAPIs - also on mysite.org

But in most cases today the real world is server-side client. So this happens:

1. The browser runs JavaScript and simulates full functionality on mysite.org
2. When .net code is run, an interop layer asks the server to do the work - through websockets on mysite.org
3. The server then has a standalone process running the client .net code. This will do the work just like the WASM browser would
4. When the client (running on the server) needs anything from the real backend this happens through another http-connection. So a process on the server (running on mysite.org) will do an http-request to mysite.org. 
5. These two processes (client and server) are completely disconnected and must communicate through http with each other

Now a real-life hosting setup has a few problems because...

* A typical hosting setup has a server behind a firewall
* The IP for mysite.org will usually point to the firewall which proxies the request to the server
* Note that it could also point to a cloudflare or anything. The important thing is, the real IP rarely points to the exact server, but to some outside endpoint - _often far away from the real server_

## Problems

* The simulated client on the server must talk to the backend, but the round-trip distance through the external endpoint is sometimes very long
* It also requires that the web-server can actually communicate with the outside world (since the HTTP call is like a call to another server), which is often not the case in secure environments
* It also requires that the web-server can do a DNS lookup to mysite.org and get the correct IP - this too is not always given

## Recommendation

1. I believe that the c# client should know if it's running on client or server
2. And if it's running on the server, it should take a shortcut to communicate with the backend - something which preserves the architecture / separation of application parts, but doesn't need external DNS & IPs etc.

## Possible Challenges

1. Since the backend is running on an IIS or similar, it could be configured to listen to a specific host name. It could be the same host name as is published, but it could also be a different one. For example, the firewall may listen to mysite.org, but forward the request to server.mysite.org because that resolves to the internal IP
2. Assuming that the request will do something like call `localhost` it should probably include some common headers like the `X-Forwarded-Host` etc. [docs](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Forwarded). The backend should of course realize this, and take the forwarded-host as the host for identifying the `Alias` used.

**Comment by sbwalker** [comment]
Basically you are describing the fact that Oqtane currently supports both Blazor hosting models by forcing the framework to act in a client/server manner regardless of whether you are running on the client (Blazor WebAssembly) or server (Blazor Server). The reason why this approach was taken is because it simplifies the framework architecture and makes the code more maintainable. It also ensures a consistent code path for execution of every request regardless of the hosting model. The downside is that in some web server environments, additional configuration is needed to ensure the server is able to call itself via http requests. On the surface thus seems like a problem which is much easier to solve using basic documentation than modifying the framework.

I would also offer my own opinion that although Blazor Server usage is very strong currently, it may be an anomaly due to the fact that Blazor WebAssembly only reached the LTS milestone just under a month ago (.NET 6) - and enterprise organizations are hesitant to adopt technology which is not at an LTS stage of maturity. The premise for Blazor from the very beginning was to create an alternative to the popular JavaScript-based SPA frameworks - so I would tend to believe Blazor WebAssembly will become the more dominant hosting model over time.

All that being said, I have explored the technical problem you explained above in the past... and there is a fairly clean architectural pattern which could be used to solve it. Let me share some high level concepts for a Blazor solution:

Client.Project
  /Components
    MyComponent.razor
  /Services
    MyService.cs
  Startup.cs
Server.Project
  /Controllers
    MyController.cs
  /Repositories
    MyRespository.cs
  /Services
    MyService.cs
  Startup.cs
Shared.Project
  /Models
    MyModel.cs
  /Interfaces
    IMyService.cs

Note that there are some differences above in comparison to Oqtane and I will explain them. Basically, in this approach there is a service interface which is defined in the Shared project. This is the contract which a service needs to implement. In the Client project there is an implementation of the service which leverages HttpClient to call the Controller API endpoints (this is how Oqtane works today). However in the Server project there is also an implementation of the service which calls the repository directly (ie. no HttpClient as this service runs on the server). The Client project components would utilize the service interface and dependency injection to obtain a reference to the appropriate service at runtime. If you are running on Blazor Server then the Server project startup is executed and it would contain service registrations for the Server services. The components would run on the server so they would use the Server services. If you are running on Blazor WebAssembly then the Client project startup is executed and it would contain service registrations for the Client services. The components would run in the client browser so they would use the Client services.

In order to adopt this approach a new Service layer would need to be introduced on the Server. This would likely require a LOT of code changes as logic which is currently embedded in the Controllers would need to by migrated so that the Controllers become simple pass-through stub methods. It should also be noted that the current architecture enforces security by forcing all activities through the Controller layer and leveraging standard API attribute security techniques. In this new architecture, if you are running on Blazor Server then you are effectively bypassing API controllers - so the security relies solely on the restrictions codified in the user interface components. So this is where it gets challenging from a maintainability and testing perspective, as you now have 2 very distinct code execution paths which can behave differently depending on the hosting model. Other items to deal with are the different threading models for Blazor Server vs Blazor WebAssembly. For example, this impacts EF Core in regards to DBContext, as you can no longer use Scoped registrations - they must be Transient. I am sure there are other challenges with this architectural approach as well - which is why it was decided to follow the current model.
