### ISSUE TITLE
Oqtane.org Forums

### ISSUE THREAD

**Issue by mikecasas** [oqtane/oqtane.framework#187]
Did something on the Oqtane site change?  I can't access the community/forums page. It says I don't have the access to view the page.

**Comment by fileman** [comment]
I haved problem with verify account link, past wednesday 8/1 I've writed at suppor email but no response at now, I wait patiently

**Comment by knight1219** [comment]
Same thing for me as well. Just signed up and says I don't have access

**Comment by sbwalker** [comment]
The forums on oqtane.org were shut down recently because of the ongoing issues with spam. In addition, the forums were not being utilized effectively - most conversations have been occurring in the GitHub issues area. A suggestion was made recently to created a Gitter room and this will be the place for more realtime collaboration in the future.

**Comment by sbwalker** [comment]
The Gitter room has been created: https://gitter.im/oqtane/community
