### ISSUE TITLE
VisitorController reporting error

### ISSUE THREAD

**Issue by leigh-pointer** [oqtane/oqtane.framework#1899]
When clicking Details the page generates an error: 
Unauthorized Visitor Get Attempt {VisitorId}

The ip is know to me as 208.115.199.20 and is a site alive service monitor.

Maybe to have an option to filter out by ip what gets logged would fix this.

**Comment by sbwalker** [comment]
The error has nothing to do with the IP of the visitor recorded - it is an API security error. I assume you are logged in as an Admin? Do all of the fields for the Visitor record related to the specific VisitorId appear to be populated with proper data in the database?

**Comment by sbwalker** [comment]
And are you running the latest code from the dev branch? I believe there was a recent modification to this API method.

**Comment by sbwalker** [comment]
@leigh-pointer I believe this permissions issue was fixed in this PR last week https://github.com/oqtane/oqtane.framework/commit/6a2ff369eaf5337cafecc156e5f0e871d8640afb#diff-278d0df215766c7358fdf1302abd05b68d6a134c1de9d237360b93791c8c4cac

In regards to your other suggestion, I think the Visitor service offers many opportunities for developers to create advanced analytics dashboards. For example, you could easily translate IP addresses to actual locations using GeoIP, you could translate User Agent strings to device/browser/version, and you could use graphs to visualize the distribution of visitors based on a a variety of criteria.

**Comment by leigh-pointer** [comment]
> And are you running the latest code from the dev branch?
No, the errors were coming from production 3.0.1
