### ISSUE TITLE
Authentication for Swagger or Postman

### ISSUE THREAD

**Issue by CebiConRepo** [oqtane/oqtane.framework#1922]
Hi there,
I've been trying to access the API for a while. It doesn't matter if I use Swagger or Postman it doesn't work. I get the message 403 Forbidden. In the future, I would like to access data via a Windows client. What should I do? How do I authenticate myself via Postman or Swagger in order to test the API's? Maybe someone has an example for me?

![Swagger UI - localhost](https://user-images.githubusercontent.com/36736217/148795652-b8cf8358-42f0-4382-ab51-115584688af5.png)
![Postman](https://user-images.githubusercontent.com/36736217/148795665-1c56d7e1-3cf6-4d44-821b-f29edbd2703c.jpg)

**Comment by sbwalker** [comment]
API access in Oqtane requires appropriate authententication and authorization. In order to use Swagger you first need to login to the application as a privileged user so that you have an auth cookie. Then you will be able to execute methods in Swagger (you can access Swagger using Admin Dashboard, System Info, Options tab). Postman is a different story - you would need to set the headers manually with a valid auth token captured from your browser session. Note that the Oqtane roadmap includes support for token based authentication / authorization via OAuth2 / OpenID Connect in the next major release - which will make this easier.
