### ISSUE TITLE
Missing Delete ModuleDefinition settings 

### ISSUE THREAD

**Issue by leigh-pointer** [oqtane/oqtane.framework#1966]
When deleting a module from the framework, any Settings for the moduleDefinitions should be deleted for each tenant as well

**Comment by lanthonyneville** [comment]
This sounds like the issue I found today ....

If the Delete button is clicked under Module Management, the assemblies are deleted from the server, however the record remains in ModuleDefinition, and also related records in Module and PageModule. This leads to an "object ref" error on startup (if the module was on a page), no doubt because it cannot instantiate a module definition matching the data in the DB. Deleting the records from the 3 tables resolves the startup error.

**Comment by leigh-pointer** [comment]
@lanthonyneville I am going to create a new issue for the related records in Module and PageModule.

**Comment by lanthonyneville** [comment]
> @lanthonyneville I am going to create a new issue for the related records in Module and PageModule.

Thanks @leigh-pointer !

**Comment by leigh-pointer** [comment]
Fix merged #2601
