### ISSUE TITLE
Feat: Enable Custom Headers on PreRender

### ISSUE THREAD

**Issue by iJungleboy** [oqtane/oqtane.framework#1967]
As of now, adding headers requires JS Interop.

But many headers - like redirects, open-graph etc. need to be in the pre-render. 

AFAIK the _hosts.cshtml has a variable to add such headers, but I believe the modules can never "report" them to be included in pre-render. 

Wish:
1. A PreRender Service or something
2. which does nothing in normal render mode
3. but if it is pre-rendering, will have things to set which would affect the final page output - like a `Headers` tag or something

**Comment by sbwalker** [comment]
@iJungleboy I totally agree that the framework should be enhanced in this area. But its not really a "pre-render" scenario - its more of a server/client scenario. What I mean is that when any client (browser or bot) makes its initial server-side request to an Oqtane site, the html markup which is returned should contain the full set of content for that page - including head elements. Once the first page had been rendered, subsequent requests are serviced by the client-side router which means page content needs to be managed client-side. So there are 2 distinct workloads which need to be managed within the framework - server and client. In recent versions of Oqtane, you will notice that the page Title was enhanced so that it is updated in both workloads - both server-side in _host.cshtml and client-side via JS Interop. 

In .NET 6 Microsoft added support for managing head elements in Blazor - https://docs.microsoft.com/en-us/aspnet/core/blazor/components/control-head-content?view=aspnetcore-6.0. Unfortunately, the implementation requires the usage of a layout page. Previously, there has never been any requirement to use a layout page in Blazor - it was an optional component which could be used to manage the layout of content on a page. And layout pages are only supported if you use the standard Blazor router. Oqtane does not use the standard router, it uses a custom router - therefore it does not use layout pages. As a result the feature from Microsoft is not usable in Oqtane.

So getting back to the topic of meta elements in the head... they can be managed in a similar manner as the page title. The question is how to integrate them into the framework. For consistency with other Oqtane concepts, it would make sense to include properties in the Site and Page entities. These properties could then be used to inject the meta elements server-side and client-side. This all seems fairly straightforward. The bigger question is if the meta elements should be defined in a granular manner or a generic manner.

In general, the meta elements in HTML have evolved over time, and we can expect them to continue to evolve. The meta elements are very loosely defined and serve as an extensibility point for new use cases. For example, meta elements like keywords and description have been used since the beginning of the HTML specification - however other meta elements have been introduced by Facebook and Twitter in recent years. And we can expect more meta elements to emerge in the future. So in order to future proof the support for meta elements it may make sense to manage them in a generic manner.

Essentially what I am referring to to have a single "meta" property and allow the administrator to enter the actual meta markup exactly as they would expect it to be represented in the page head:

```
    <meta name="description" content="Mozilla is the not-for-profit behind the lightning fast Firefox browser. We put people over profit to give everyone more power online.">
    <meta property="og:type" content="website">
    <meta property="og:site_name" content="Mozilla">
    <meta property="og:locale" content="en_US">
    <meta property="og:url" content="https://www.mozilla.org/en-US/">
    <meta property="og:image" content="https://www.mozilla.org/media/img/mozorg/mozilla-256.4720741d4108.jpg">
    <meta property="og:title" content="Internet for people, not profit">
    <meta property="og:description" content="Mozilla is the not-for-profit behind the lightning fast Firefox browser. We put people over profit to give everyone more power online.">
    <meta property="fb:page_id" content="262134952380">
    <meta name="twitter:card" content="summary">
    <meta name="twitter:site" content="@mozilla">
    <meta name="twitter:domain" content="mozilla.org">
    <meta name="twitter:app:name:googleplay" content="Firefox">
    <meta name="twitter:app:id:googleplay" content="org.mozilla.firefox">
    <meta name="twitter:app:name:iphone" content="Firefox">
    <meta name="twitter:app:id:iphone" content="989804926">
    <meta name="twitter:app:name:ipad" content="Firefox">
    <meta name="twitter:app:id:ipad" content="989804926">
```

This provides the maximum flexibility and future proof design. However it also requires some technical knowledge on the part of the administrator - which should be fine considering the persona which Oqtane is intended to service (ie. developers rather than end users).

**Comment by iJungleboy** [comment]
I totally agree, and believe it should be very generic. Possibly with some kind of ID (why may not be in the HTML) to avoid duplicate additions. Something like

```
   [Inject]
   public IHeaderService HeaderService {get;set;}

  // ...
  HeaderService.Add("my-component-twitter", "<meta name="twitter:card" content="summary">
    <meta name="twitter:site" content="@mozilla">
    <meta name="twitter:domain" content="mozilla.org">
    <meta name="twitter:app:name:googleplay" content="Firefox">
    <meta name="twitter:app:id:googleplay" content="org.mozilla.firefox">
    <meta name="twitter:app:name:iphone" content="Firefox">
    <meta name="twitter:app:id:iphone" content="989804926">
    <meta name="twitter:app:name:ipad" content="Firefox">
    <meta name="twitter:app:id:ipad" content="989804926">");
    // ...

**Comment by sbwalker** [comment]
A new service would not be required - the Meta property would be added to the Page entity and then the PageService methods can be used to manage the new property. An additional  benefit of this approach is that the Page entity is already included in PageState so it can be easily accessed in any module/theme without requiring additional service calls - and the value will be synchronized across other clients when it changes. From a UI perspective it will be accessed through Add/Edit Page - similar to the page title.

**Comment by iJungleboy** [comment]
That sounds great. I'm not sure if I would only use "Meta" since the header may need other headers as well. But in principle the PageService sounds just perfect.

**Comment by sbwalker** [comment]
@iJungleboy actually I was only referring to meta elements. Other head elements require a different approach. For example, scripts and stylesheets are already handled via the Resources collection as part of Themes and Modules. Title is already a property of the Page object. Favicon is already a property on the Site object. PWA support is also already a property on the Site object. The only gap at the moment is support for meta elements.

**Comment by iJungleboy** [comment]
I believe that's almost correct.

An Issue we had was that the Resources are picked up when the object is created. This turned out to be too early for our use case, where different situations determined resources (JS/CSS) at a much later time. At this time, the resources were already processed so we had to use Interops to inject them to the page. I could be wrong though, possibly this was 2.0 behavior and Oqtane 3 may have changed this. 

So I guess you're right, but it would be good if the resources were not picked up so early.

**Comment by sbwalker** [comment]
Added in #1984
