### ISSUE TITLE
jquery plugins stop working when navigating through pages

### ISSUE THREAD

**Issue by sasanrepo** [oqtane/oqtane.framework#1981]
I have used jquery libraries like sliders in html modules. When I open the website with jquery slider in it for the first time it works fine but the problem occures when I navigate between pages and then return to the page with jquery, jquery sliders stop working.
<br />
<img src="https://www.jalakaran.com/temp/err1.png" width="500px" />
<br />
<img src="https://www.jalakaran.com/temp/err2.png" width="500px" />

**Comment by sbwalker** [comment]
Oqtane uses Blazor and Blazor requires JavaScript to be used via JS Interop - https://docs.microsoft.com/en-us/aspnet/core/blazor/javascript-interoperability/?view=aspnetcore-6.0. If you try to use JavaScript (or jQuery) in the traditional manner it may appear to work on the initial page load, however it will not behave as expected on subsequent page interactions because at that point the application is running as a client-side SPA. You will need to become familiar with Blazor JS Interop techniques. Please note that as part of the migration to Bootstrap 5, Oqtane no longer has a dependency on jQuery - only on the native JavaScript library included in Bootstrap 5.

**Comment by artmedia** [comment]
Thanks, Shaun.
This example is usefull
