### ISSUE TITLE
class StartUp : IClientStartup not getting called for External Modules

### ISSUE THREAD

**Issue by leigh-pointer** [oqtane/oqtane.framework#1986]
Running 3.0.2 the service is called
Current code base does not call the Service.
This has happened with the last commit "Commits on Jan 29, 2022"
was applied.

The code executes fine when the hosting model Runtime is "Blazor WebAssembly"

**Comment by sbwalker** [comment]
The code was removed because the startup logic was dependent on the Blazor hosting model specified in appsettings - and the Blazor hosting model is no longer an app-wide setting in Oqtane, it is specified per Site. This means that the logic in 3.0.2 was actually broken - ie. if you had a Site configured for Blazor Server in your installation and another for Blazor WebAssembly, the execution of IClientStartup was dependent on the appsetting during Server startup - which is not correct. In a Blazor Server application the only Startup which is actually executed is in the Oqtane.Server project ( in WebAssembly there are is a Startup in both the Client and Server which are executed because they are in fact 2 distinct applications running in 2 separate environments ). After more investigation, I believe the proper way to deal with this issue is to retain the call to IClientStartup in the Server startup - but simply not make it dependent on the appsetting. Essentially this means that regardless of the hosting model you are using, the Client services would be registered on the Server - however for sites running on WebAssembly they would never be utilized on the Server - as those sites would rely on the Client service container.

**Comment by sbwalker** [comment]
In case my answer above was unclear, I believe a fix is needed in the core framework to address this item. You should not have to do any refactoring to your modules. Thank you for raising the issue.

**Comment by leigh-pointer** [comment]
Then of course im willing to help.
________________________________
