### ISSUE TITLE
Root site can be deleted

### ISSUE THREAD

**Issue by chlupac** [oqtane/oqtane.framework#202]
Result is white screen, unrecoverable.

**Comment by sbwalker** [comment]
So you are saying the framework should prevent you from deleting a site if it is the only site in the installation- makes sense.

**Comment by chlupac** [comment]
yes, exactly.

**Comment by hishamco** [comment]
I will create a PR for this one

**Comment by hishamco** [comment]
@chlupac can you keep this open, it will be closed automatically when the PR is merged

**Comment by sbwalker** [comment]
The implementation used for validating this use case was not correct. Based on the multi-tenancy model it is not possible to simply check if there is a single Site in a database. If you are using the isolated tenancy model it is totally acceptable to have no Sites in a database. I added validation logic in #249 so that you cannot delete the site you are currently administrating. This should solve the problem.

**Comment by chlupac** [comment]
You are right. Problem was in deleting current site.
