### ISSUE TITLE
Security!  Settings controller is open

### ISSUE THREAD

**Issue by chlupac** [oqtane/oqtane.framework#205]
It allows discover SMTP settings, password and sensitive user data

        // GET: api/<controller>
        [HttpGet]
        public IEnumerable<Setting> Get(string entityname, int entityid)
        {
            return Settings.GetSettings(entityname, entityid);
        }

        // GET api/<controller>/5
        [HttpGet("{id}")]
        public Setting Get(int id)
        {
            return Settings.GetSetting(id);
        }

**Comment by chlupac** [comment]
I recommend separation of user profile from site settings.  Advantage is possibility of foreign keys to user table and to profile definition.
Site settings should be accessible only for admins and system. 
Module settings should not contain sensitive data or we need to find another way how to secure it.

**Comment by sbwalker** [comment]
The SettingsController does need some addition auth logic for the Get methods. There is already a private IsAuthorized method for this purpose - but it is only implemented for Post,Put,Delete at the moment - it needs to be implemented for Get as well. There are numerous benefits to having centralized Settings service - so I am not in favor of separating them by domain/entity - especially at the database level. For sensitive data I believe an encryption/decryption capability should be added so that the data is obscured when it is at rest.

**Comment by ADefWebserver** [comment]
Could we have a separate GetSettings call, that required an Administrator accunt, that exposed the passwords?

**Comment by sbwalker** [comment]
Note that user passwords are NOT stored in the Settings table - they are stored in the Identity area. The Notification service relies on SMTP configuration ( including potentially an SMTP password ) which is stored in the Settings table - related to a Site. In this case the Get method in the Controller should restrict access to the Administrator. So this takes care of the access issue. However the values are still stored in plain text in the Settings table itself - which is why I was suggesting an encryption capability for some values.

**Comment by sbwalker** [comment]
I am going to do a general review of all of the Controllers to ensure all methods have the correct Authorization. This will likely result in some changes to the API surface area. For example, there are currently a variety of Get() methods for entities which do not require a parameter.These methods are not used by the framework and should be removed as almost all Get() methods require some type of scoping parameter to identify which entities are being selected and to provide security context. The only reason why a Get() method without a parameter was introduced in the first place is because it was part of a Controller template.

**Comment by chlupac** [comment]
Centralized settings service is great, i like it, but IMHO do not store user profiles here, please.

**Comment by sbwalker** [comment]
PR #208 is the start of the API security review refactoring.

**Comment by sbwalker** [comment]
@chlupac Can you please explain why you do not believe user profile values should be stored in the Settings service? Currently demographic info such as name, address, etc... are stored there - and it is dynamic based on whatever Profile fields are defined for a site. It is also possible to store arbitrary personalization settings related to a user in this location.

**Comment by hishamco** [comment]
> Could we have a separate GetSettings call, that required an Administrator account, that exposed the passwords?

Disagree, coz the password still plain text

>  which is why I was suggesting an encryption capability for some values.

Totally agree

**Comment by sbwalker** [comment]
#214 completes the security changes

**Comment by sbwalker** [comment]
A new item should be opened for encrypting items in the Settings repository
