### ISSUE TITLE
File Upload Failed {Error} .json file

### ISSUE THREAD

**Issue by leigh-pointer** [oqtane/oqtane.framework#2052]
File Upload Failed Length cannot be less than zero. (Parameter 'length')

System.ArgumentOutOfRangeException: Length cannot be less than zero. (Parameter 'length')
   at System.String.Substring(Int32 startIndex, Int32 length)
   at Oqtane.Services.FileService.UploadFilesAsync(String folder, String[] files, String id) in C:\Users\Shaun.Walker\source\repos\sbwalker\oqtane.framework\Oqtane.Client\Services\FileService.cs:line 115
   at Oqtane.Services.FileService.UploadFilesAsync(Int32 folderId, String[] files, String id) in C:\Users\Shaun.Walker\source\repos\sbwalker\oqtane.framework\Oqtane.Client\Services\FileService.cs:line 77
   at Oqtane.Modules.Controls.FileManager.UploadFile() in C:\Users\Shaun.Walker\source\repos\sbwalker\oqtane.framework\Oqtane.Client\Modules\Controls\FileManager.razor:line 323

Are we not allowing .json files to be uploaded? I managed to upload .pdf ok but .json not ?

**Comment by leigh-pointer** [comment]
So this answer is no.  Can this extension be added and/or should we look into making this Const configurable?
`public const string UploadableFiles = "jpg,jpeg,jpe,gif,bmp,png,ico,webp,mov,wmv,avi,mp4,mp3,doc,docx,xls,xlsx,ppt,pptx,pdf,txt,zip,nupkg,csv";`

**Comment by sbwalker** [comment]
If you want to make them configurable, they would need to be managed at the Host level (the Admin level poses too much risk). So the option would need to be added to the System Info UI (on the tab where you can enter various fields). There are 2 options on where to store this setting - either in appsettings.json (like the other settings in System Info) or in the Settings table in the database (using EntityName = EntityNames.Host). My original goal was to try to keep appsettings.json as small as possible - however over time I have discovered that many .NET Core services depend on appsettings.json and there is no easy way to get configuration from a database, so appsettings.json is starting to grow. And since the other settings in System Info are stored in appsettings.json then perhaps it is best for the UploadableFiles to be stored there as well for consistency. I also noticed that Admin/Files/Add.razor relies on the UploadableFiles constant - which is going to be a problem if it becomes a configurable setting as it will not be available in the client in this security context. So tge validation logic in Add,razor would need to be removed and handled on the server (which is the preferable approach anyways). 

The much easier approach for now is to add the other file extensions to the constant - but this is not the best long term option.  I am also wondering if htm, html, css should be considered valid. In general this feature is trying to prevent users from uploading files which may contain malicious payload that could affect their installation.

I will leave it up to you.

**Comment by leigh-pointer** [comment]
@sbwalker ok clear direction.  I will PR constants and action the softer approach.
