### ISSUE TITLE
Unable to create site from job by hitting "api/installation" api 

### ISSUE THREAD

**Issue by NishchayChauhan251980** [oqtane/oqtane.framework#2066]
Hey everyone from few days i am trying to create a siye by hitting api "api/installation because i am not getting identity username as admin in httpcontextaccessor .So please if anyone can guide me .I am open for helping hands.

**Comment by sbwalker** [comment]
Are you saying that you are trying to install Oqtane using the standard approach (ie. via the Install Wizard) and you are getting an error? If you are using the latest code from the Dev branch then it is possible there may be issues as it is currently receiving some major enhancements - see this thread https://github.com/oqtane/oqtane.framework/discussions/2061

**Comment by NishchayChauhan251980** [comment]
actually i am using that repos from last 2 months and it is working great but when i am hitting post api in installation controller i am not getting any user in http context accessor .So can you suggest me a way so that i can get identity user from http context accessor

**Comment by leigh-pointer** [comment]
@NishchayChauhan251980 have you disabled WebDAV? It must be disabled for Iqtane to save data through the api.

**Comment by sbwalker** [comment]
@NishchayChauhan251980 It is hard to understand what you are trying to do based on the sparse details provided - but I am guessing that rather than installing the framework interactively via the Install Wizard, you are trying to automate the install by manually calling the Installation API.  If this is the case then please keep in mind that the Installation API has very strict rules about how it can be called. It needs to be a POST request and it needs to contain a valid InstallConfig model. In addition, the ConnectionString in appsettings.json must be blank (for a new install scenario) OR the logged in user must have host permissions (when adding a new site in an existing installation). Which of these is your scenario?

**Comment by NishchayChauhan251980** [comment]
"the logged in user must have host permissions (when adding a new site in an existing installation)." This one is my scenerio i am doing this by using jobs

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by sbwalker** [comment]
@NishchayChauhan251980 so you are trying to call the Installation API from within a scheduled job? This is not going to be possible. My suggestion is that instead of calling the Installation API from your job you should bypass it and simply call the DatabaseManager class directly (since the scheduled job is running on the server and requires no client interaction).

**Comment by NishchayChauhan251980** [comment]
then it will create the site but i will be unable to hit the url generated

**Comment by NishchayChauhan251980** [comment]
and if i will be calling databasemanager class directly then it will dispose

**Comment by sbwalker** [comment]
I can't really provide any more advice as you have not explained what you are trying to accomplish.

**Comment by NishchayChauhan251980** [comment]
just tell me if there is any way to authorize my api call that i can get admin credentials in httpcontext 
in optane or a way to obtain authentication token in oqtane
