### ISSUE TITLE
Is possibile to implement MongoDB repository?

### ISSUE THREAD

**Issue by mircotamburini** [oqtane/oqtane.framework#2147]

**Comment by leigh-pointer** [comment]
@mircotamburini  MongoDB stores data records as BSON documents.  Oqtane is built on a SQL relational structure.  Currently Oqtane supports a number of DB storage systems ; LocalDB, SQL Server, SQLite, MYSQL and PostgreSQL.

**Comment by sbwalker** [comment]
@leigh-pointer is correct - it would not be possible to create a NoSQL database provider for Oqtane because the framework uses a relational database approach for structuring data and relies on concepts like foreign keys, cascading deletes, etc... However, if you wanted to create a custom Oqtane module which stored its own data in a NoSQL database, this would definitely be possible.

**Comment by mircotamburini** [comment]
ok
