### ISSUE TITLE
Update Database on a custom Module

### ISSUE THREAD

**Issue by elgransan** [oqtane/oqtane.framework#2148]
If I add a new database migration in my custom Module, which is the way that the database get updated? 

Because, the only way I found is deleting the entire module (and all the database tables and migration table) but then the only way I found to add the module again is compiling the nuget package and importing it, I'm not sure if I'm doing well or there is a better/easy/fast way while I'm developing.

Thanks

**Comment by sbwalker** [comment]
Each time you create a new migration for your module, you are creating a new "version" of your module. As a result you need to update the version properties in the IModule interface (usually implemented in a file called ModuleInfo.cs in your Client project):

```
        public ModuleDefinition ModuleDefinition => new ModuleDefinition
        {
            Name = "Your Module",
            Description = "Your Module",
            Version = "1.0.1",
            ReleaseVersions = "1.0.0,1.0.1",
            ServerManagerType = "Fully Qualified Type Name Of Manager Class In Server Project"
        };
```

When the framework starts up it uses this class to determine if a module has been updated and requires a migration. It does this by comparing the current module version stored in the database with the module version info specified above. Currently it uses the ReleaseVersions property for this purpose as this property provides the full context of every known release version for a module (ie. in case there were a number of intermediary versions between the currently installed version and the latest version). So you need to make sure the ReleaseVersions property is accurate.

Note: the reason why the framework cannot simply rely on EF Core migration versioning is because not all modules use EF Core migrations. Some modules use SQL scripts. And sometimes there is a need to execute version specific logic which can be included in the IInstallable module implementation. To handle all of these different use cases, an independent versioning strategy was required.

Note: in Oqtane 3.1.1 some logic has been added so that the framework is more "intelligent" and can determine that if ReleaseVersions was not specified or ReleaseVersions is less than Version, then it should use Version instead of ReleaseVersions when executing the startup migration logic. This should streamline the majority of upgrade scenarios while still providing the granular control when required.

**Comment by elgransan** [comment]
Thank you, I understand. When you say "make sure the ReleaseVersions property is accurate" means that the migration version must match the version with this file? With the Migration attribute or the migration file name?

**Comment by sbwalker** [comment]
If the initial version of your module has an EF Core migration:

[Migration("YourModule.01.00.00")]

Then the ModuleInfo.cs should contain:

Version = "1.0.0",
ReleaseVersions = "1.0.0"

Then you enhance your module and add another EF Core migration:

[Migration("YourModule.01.00.01")]

The ModuleInfo.cs should be updated to contain:

Version = "1.0.1",
ReleaseVersions = "1.0.0,1.0.1"

And this pattern would be followed for each major enhancement to your module.

**Comment by sbwalker** [comment]
@elgransan the 3.1.1 release includes an enhancement for module developers who are using EF Core migrations where they can ignore the ReleaseVersions property in the IModule interface and simply increment the Version attribute ie.

If the initial version of your module has an EF Core migration:

[Migration("YourModule.01.00.00")]

Then the ModuleInfo.cs should contain:

Version = "1.0.0"

Then you enhance your module and add another EF Core migration:

[Migration("YourModule.01.00.01")]

The ModuleInfo.cs should be updated to contain:

Version = "1.0.1"

Note that you do not need to specify ReleaseVersions as the framework will recognize that the Version in the module's ModuleInfo.cs is higher than the currently installed module version - so it will execute the EF Core Migration logic - which will execute all migrations which have a migration id greater than what is recorded in the __EFMigrationsHistory table for the module.

**Comment by elgransan** [comment]
Thank you Shaun it's very useful when you are building a big module and you have to generate several releases until get a stable one.
