### ISSUE TITLE
Oqtane Template Website

### ISSUE THREAD

**Issue by michalss** [oqtane/oqtane.framework#2156]
Hello,

I have to say this is very nice project and so great written. My question is about your website https://www.oqtane.org/. Totally love your components and how this website is structured and made. is there any chance to release the source code with dummy data please, ofc if its made from Oqtane on the first place ?  My idea is that basically your can deploy any nice looking web instantly with a small effort. I know you can say it is lazy to ask, but not everyone is css/html designer and just want to simply and quickly deploy some info site. 

Regards
Mike

**Comment by leigh-pointer** [comment]
Hi @michalss your question is answered here https://github.com/oqtane/oqtane.framework/discussions/1964#discussioncomment-2078467

**Comment by sbwalker** [comment]
Yes, https://www.oqtane.org/ is running Oqtane... there is more information in the link that @leigh-pointer posted above. However I do have a question... if your goal is to simply and quickly deploy a website then I am curious why you would want to use Oqtane rather than one of the many Site Builders that are available?

**Comment by michalss** [comment]
Well simple answer, love blazor and love oqtane and c#. :) Anyway thx closing it down..
