### ISSUE TITLE
Unable to Upload Files

### ISSUE THREAD

**Issue by leigh-pointer** [oqtane/oqtane.framework#2172]
Event Log
Level = Error
Feature = Controls
Function = Create

![image](https://user-images.githubusercontent.com/9447612/166723970-9820cf4d-d5bf-4da4-ae02-cc368685dbb1.png)

The Package installs when copied to the Packages Folder.

**Comment by sbwalker** [comment]
Thank you for reporting this issue... after investigation it is actually a broader issue affecting all file uploads. It is related to the antiforgery filter introduced in 3.1.1 and the fact that asynchronous file uploads are invoked via a JavaScript Interop method rather than HttpClient. There are a couple ways to resolve this issue... I will investigate further.

**Comment by elgransan** [comment]
I can confirm is working now with the last commit, thank you
