### ISSUE TITLE
IMHO: Possibillity to turn-off swagger on production 

### ISSUE THREAD

**Issue by chlupac** [oqtane/oqtane.framework#218]
https://security.stackexchange.com/questions/211638/swagger-on-production-apis

**Comment by ADefWebserver** [comment]
I think as long as we follow [Microsoft guidelines ](https://docs.microsoft.com/en-us/aspnet/core/tutorials/web-api-help-pages-using-swagger?view=aspnetcore-3.1) we are balancing features with any possible risk. 

Also, I am not sure that response to the question in that link is serious. It contained this:

> ...for example, if your API document includes a query parameter named "exclude_data_we_stole_from_the_fbi", you may attract attention from the FBI for stealing their data

**Comment by sbwalker** [comment]
Since Oqtane is an open source framework, the APIs for the core framework will be known regardless of whether Swagger is enabled in production or not. If you are referring to the ability to disable Swagger for your custom module APIs, currently the Swagger implementation in Oqtane does not support custom modules so it does not expose those APIs in any environment.
