### ISSUE TITLE
Adding a new site fails

### ISSUE THREAD

**Issue by dkoeder** [oqtane/oqtane.framework#2192]
Adding a new site fails due to user.LastIPAddress being null and User.LastIpAddress field in DB not nullable. My workaround was to add user.LastIPAddress = SiteState.RemoteIPAddress to the user that is created on line 307 of Oqtane.Client\Modules\Admin\Sites\Add.razor. My knowledge of the code is too small to know if this is right or not.

**Comment by sbwalker** [comment]
Thank you for reporting this issue. It was caused by the fix in PR #2179 which previously used HttpContext.Connection.RemoteIpAddress but now relies on the IP Address being passed from the client (as HttpContext.Connection.RemoteIpAddress does not work properly on Blazor Server). Your solution is correct that Add.Razor needs to pass the IP Address. Please go ahead and submit a PR for this change.
