### ISSUE TITLE
Strange behavior uploading using module updater

### ISSUE THREAD

**Issue by elgransan** [oqtane/oqtane.framework#2221]
I'm working on a module (about 2Mb the nuget package), and I'm doing partial uploads to show progress to my client, but several times I'm having troubles with the module uploader (the site is on Azure App Service)

Any idea what's wrong with this? If you take a deep look you can see the file is changing on the progress bar for an older package.

![uploadoqtane2](https://user-images.githubusercontent.com/9949584/170593325-779a7562-8cd8-4174-b244-f4f479d1cfca.gif)

I can see this on Azure Kudu

![image](https://user-images.githubusercontent.com/9949584/170593607-eb337acb-380e-4565-b402-201afaf31cb8.png)

**Comment by elgransan** [comment]
I kept thinking about this problem, maybe not allowing multiple file uploads solve it, isn't it?

**Comment by sbwalker** [comment]
No, the multiple file upload capability is a native feature of the HTML5 input file element... this issue is related to the component lifetime. In a traditional server application there are constant page refreshes which constantly reset the state of components. In a single page application the client is never refreshed so the state of components is retained for an entire browser session. As a result it is up to the developer to manage the state explicitly. The file upload component needs to ensure the list of files are reset after each upload operation. I thought the component was already doing this but perhaps there is a missing use case. I was traveling fit work this week so I have not had time to investigate further.

**Comment by sbwalker** [comment]
@elgransan the logic does exist in interop.js to reset the fileinput element, however I believe an error is happening which is short circuiting the method so that the reset never occurs. In your screen shot you posted it does indicate that an error occurs during the upload ("File Upload Failed"). Are you able to share the detailed error message from the Event Log related to this failure?

**Comment by elgransan** [comment]
It didn't says too much:

Level: Error
Feature: Controls
Function: Create
Category: Oqtane.Modules.Controls.FileManager, Oqtane.Client, Version=3.1.2.0, Culture=neutral, PublicKeyToken=null
Page: Module Management
Module: Module Management
Template: File Upload Failed For {Files}
Message: File Upload Failed For TMT.GestionKits.1.0.29.nupkg
Properties: {"Files":"TMT.GestionKits.1.0.29.nupkg"}

**Comment by sbwalker** [comment]
Is there something unique about that specific package?

**Comment by elgransan** [comment]
I don't think so, it has about 8 oqtane modules and some dependencies like Humanizer and NPOI, that's why is heaviy.

**Comment by elgransan** [comment]
I don't know if it could be the problem but sometimes I uploaded the same package version but with some minimal corrections, so binary level different.

**Comment by elgransan** [comment]
Hi @sbwalker about this error I could reproduce the same error in different environments (in localhost too) and the problem is with big files, files above 2 mb, but if you upload a 100mb video for example you can see the error very fast.
I think is related with the chunks but I don't know which is the problem, seems that the progress bar is moving for each chunk of data, sometime it ends well sometimes it throws an error.

**Comment by sbwalker** [comment]
Thank you for the additional context. I seem to recall I investigated a large file issue in the past and discovered it had something to do with the environment - ie. IIS has different limitations than Kestrel or other web servers - which produces different results. Are you able to share which web server you are using?

**Comment by sbwalker** [comment]
See #1268 where a similar issue was discussed and it was concluded that the issue was related to IIS

**Comment by sbwalker** [comment]
I am not able to reliably reproduce the problems you reported even when I upload files which are > 100MB. However I did make a number of improvements to the file upload process which may or may not help your scenario.

**Comment by elgransan** [comment]
It's happening in Kestrel with Win 11 PRO (inside an Azure AD) in localhost. And also in Azure App Service Free Plan (I think is a IIS)

I uploaded the latest dev version with this change you did but it's still happening, I got a 500 error on this line (sometimes)

![image](https://user-images.githubusercontent.com/9949584/172201632-a6661741-5240-498e-951c-4b5c6d708ff3.png)
