### ISSUE TITLE
Problem with mail messages

### ISSUE THREAD

**Issue by InfDev** [oqtane/oqtane.framework#2239]
1. ascii encoding

```
From: ArmyTeam
Sent: 10.06.2022 9:37:27
To: ????????? ?????? [<alex.shlyakhto@gmail.com>](mailto:alex.shlyakhto@gmail.com)
Subject: ArmyTeam SMTP Configuration Test
```

One cardinal solution [here](https://github.com/InfDev/Suggestions/tree/main/Oqtane.Framework/MailKitMailService)

2. the text of embedded messages cannot be localized

**Comment by sbwalker** [comment]
Please explain the issue in more detail - "ascii encoding" is not an issue. Are you trying to say that you wished the framework supported other encoding methods? This would be an enhancement request.

One of the philosophies in Oqtane is to avoid third party dependencies. This is the reason the framework is using the native SMTP capabilities rather than a third party library.

You are correct, message content cannot be localized. Oqtane is not a CMS so it does not support content localization. This is by design.

**Comment by InfDev** [comment]
The problem is that the site user is receiving inline email notifications (registration and login) in a language other than their preferred language. 

The worst case is when instead of the user's display name, he sees "????????????????".
Easiest way but partial solution:

```
message.BodyEncoding =  System.Text.Encoding.UTF8;
message.SubjectEncoding = System.Text.Encoding.UTF8;
```

If you implement sending through the service, but leave the actual sending through System.Net.Mail.dll, then it is easy to replace the send implementation in a separate external module by applying the appropriate library.

**Comment by sbwalker** [comment]
My suggestion is that you create your own NotificationJob and you will have the freedom to send messages using whatever method you prefer.

**Comment by InfDev** [comment]
For myself, I already solved this problem earlier, but described it for the possibility of improving Octane. The more I use framework in practice, the more I like the framework

**Comment by sbwalker** [comment]
@InfDev if you would like me to add the encoding enhancement PR on your behalf please let me know

**Comment by InfDev** [comment]
If possible then yes
