### ISSUE TITLE
No way to delete a tenant site if tenant has only one site

### ISSUE THREAD

**Issue by dkoeder** [oqtane/oqtane.framework#2250]
Oqtane: current dev branch
Database: LocalDB
Hosting Model - Runtime: Blazor WebAssembly
Hosting Model – Prerender?: Yes

1.	Installed oqtane
2.	Added site, “TestA”, with new tenant, “TestTenantA”
3.	Restarted oqtane
4.	Went to Site Mangement 
5.	Went to Edit on “TestA”
6.	Clicked on “Delete Site”, confirmed.
7.	Always returns “You Are Not Authorized To Delete The Site” due to the (sites.Count > 1) in Index.razor

Oqtane.Client\Modules\Admin\Site\Index.razor

	private async Task DeleteSite()
	{
		try
		{
			var sites = await SiteService.GetSitesAsync();
			if (sites.Count > 1)
			{
                         .
                         .
 			}
			else
			{
				AddModuleMessage(Localizer["Message.FailAuth.DeleteSite"], MessageType.Warning);
			}

**Comment by dkoeder** [comment]
Here is my work around - 
Original code - 

	private async Task DeleteSite()
	{
		try
		{
			var sites = await SiteService.GetSitesAsync();
			if (sites.Count > 1)
			{
				await SiteService.DeleteSiteAsync(PageState.Site.SiteId);
				await logger.LogInformation("Site Deleted {SiteId}", PageState.Site.SiteId);

				var aliases = await AliasService.GetAliasesAsync();
				foreach (Alias a in aliases.Where(item => item.SiteId == PageState.Site.SiteId && item.TenantId == PageState.Site.TenantId))
				{
					await AliasService.DeleteAliasAsync(a.AliasId);
				}

				NavigationManager.NavigateTo(NavigateUrl("admin/sites"));
			}
			else
			{
				AddModuleMessage(Localizer["Message.FailAuth.DeleteSite"], MessageType.Warning);
			}
		}



Modified code - 

	private async Task DeleteSite()
	{
		try
		{
			var tenant = await TenantService.GetTenantAsync(PageState.Site.TenantId);
			if (!tenant.Name.Equals(TenantNames.Master, StringComparison.OrdinalIgnoreCase))
			{
				await SiteService.DeleteSiteAsync(PageState.Site.SiteId);
				await logger.LogInformation("Site Deleted {SiteId}", PageState.Site.SiteId);

				var aliases = await AliasService.GetAliasesAsync();
				foreach (Alias a in aliases.Where(item => item.SiteId == PageState.Site.SiteId && item.TenantId == PageState.Site.TenantId))
				{
					await AliasService.DeleteAliasAsync(a.AliasId);
				}

				NavigationManager.NavigateTo(NavigationManager.BaseUri, true);
			}
			else
			{
				AddModuleMessage(Localizer["Message.FailAuth.DeleteSite"], MessageType.Warning);
			}


The "NavigationManager.NavigateTo(NavigationManager.BaseUri, true);" is just my guess at a navigation that works. If this was left at "NavigationManager.NavigateTo(NavigateUrl("admin/sites"));" it would cause an error in SiteRouter. Could this be due to navigating to a site that was just deleted?  With these changes the issue #2249 seems not to be a problem.

**Comment by sbwalker** [comment]
The logic for validating if there is more than 1 site is intended to prevent a host user from removing all sites from an installation - as there needs to be at least 1 site in the installation to enable the framework to function properly (ie. this validation is to prevent a host user from accidentally "shooting themself in the foot"). 

However, as you identified above, the logic is not correct as instead of checking if there is more than 1 site in the entire installation, it is checking if there is more than 1 site in the current tenant (an installation can have many tenants). However the proper fix is actually a bit different than what you suggested... it should utilize the Alias service as an Alias is the cross reference between tenants and sites.

**Comment by dkoeder** [comment]
@sbwalker I tried it with the latest changes and now, when repeating the steps I define above, it says "Error Deleting Site". 

Looks like the GetAliasesAsync in AliasService.cs need to be changed to something like this

        public async Task<List<Alias>> GetAliasesAsync()
        {
            List<Alias> aliases = await GetJsonAsync<List<Alias>>(ApiUrl);
            if (aliases == null)
            {
                var masterUrl = CreateApiUrl("Alias", null, ControllerRoutes.ApiRoute);
                aliases = await GetJsonAsync<List<Alias>>(masterUrl);
            }
            return aliases.OrderBy(item => item.Name).ToList();
        }

Not sure if that is the right way to get the master tenant url. Should the Alias service always use the master tenant url since it looks like Alias table is only in the host DB?

**Comment by sbwalker** [comment]
@dkoeder the problem was with the redirect logic - it has been resolved in #2260. Oqtane's multi-tenant capability relies on Aliases to determine the appropriate mapping for the Urls in API/UI requests... so this means that when an Alias is deleted, all requests that are still utilizing that Alias will fail. As a result it is necessary to redirect the client to another valid Alias as soon as the current alias is deleted. One other concept which is not entirely obvious is that the "Master Tenant" has nothing to do with Sites or Aliases... a "tenant" in Oqtane simply refers to a database. The "Master Tenant" is the database where the global information related to Tenants, Aliases, Jobs, etc... is stored. The "Master Tenant" may contain Sites as well - however it is possible to remove all Sites from the Master Tenant and still have a functional installation - in this scenario all of your Sites would be in other Tenants (databases).
