### ISSUE TITLE
 Inserting a image in an HtmlTExt/Blog Module does not work for me.

### ISSUE THREAD

**Issue by jaruiz-ual** [oqtane/oqtane.framework#2252]
The HtmlTRext/Blog Module  seems to work only with text.  I can not insert a image as content. Am I wrong?

**Comment by sbwalker** [comment]
Do you not see the Insert Image button above the rich text editor?

![image](https://user-images.githubusercontent.com/4840590/175545510-042ad105-79d1-4042-86ce-642bbef1aa38.png)

**Comment by jaruiz-ual** [comment]
Hi Shaun,First of all, I would like to congratulate you on the magnificent work you are doing with Oqtane. And of course thank you for your interest in answering me.I am trying Oqtane, my interest is to use Oqtane as base for developing web applications using Blazor. Developing my own funcional modules for Oqtane. AS a test, I have tried to add another image to that  Welcome To Oqtane .. HtmlText component. Something very simple.I see the insert button, the comboboxes for selecting Folder and File, button for uploading …  everything is there. But when I click on the insert button finally, the selected image flash a little bit on the component  and nothing else. Best regards    Enviado desde Correo para Windows De: Shaun WalkerEnviado: viernes, 24 de junio de 2022 15:27Para: oqtane/oqtane.frameworkCC: jaruiz-ual; AuthorAsunto: Re: [oqtane/oqtane.framework] Inserting a image in an HtmlTExt/Blog Module does not work for me. (Issue #2252) Do you not see the Insert Image button above the rich text editor?—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you authored the thread.Message ID: ***@***.***>

**Comment by sbwalker** [comment]
My apologies... you are correct that in the latest version of Oqtane the ability to insert an image seems to be broken. There seems to be an issue with the Quill JavaScript method it utilizes.

**Comment by sbwalker** [comment]
After further research, this does not appear to be a problem with the Quill JavaScript component. If I put a breakpoint in the RichTextEditor.razor component on the following line:

```
                await interop.InsertImage(_editorElement, file.Url, file.Name);
```

I am able to see that the image tag is inserted into the content. However, once this method finishes executing it appears that a Blazor refresh operation takes place and it replaces the modified content with the original content.

**Comment by sbwalker** [comment]
The problem is caused by the OnAfterRenderAsync method in the RichTextEditor.razor component. OnAfterRenderAsync is called whenever a browser refresh is required (which is necessary to toggle the visibility of the FileManager component above the rich text editor). On refresh the following logic is being executed:

```
		//	await interop.LoadEditorContent(_editorElement, _richhtml);	
```

which is essentially refreshing the content of the rich text editor with the original content. I will remove this logic... however if you look at the history of the RichTextEditor.razor component you will see a lot of churn as a result of trying to make the component accomodate a lot of different scenarios (https://github.com/oqtane/oqtane.framework/commits/dev/Oqtane.Client/Modules/Controls/RichTextEditor.razor). 

One scenario which may be affected by this fix is related to the following issue:

https://github.com/oqtane/oqtane.framework/issues/1837

In hindsight, the correct way to deal with dynamic modification of the rich text editor content is not by allowing assignment of the Content property, but by introducing specific public methods for setting the Content property - as this will avoid any impact with the component rendering licfe cycle.  

@leigh-pointer @ADefWebserver
