### ISSUE TITLE
Authorization not working properly

### ISSUE THREAD

**Issue by mdmontesinos** [oqtane/oqtane.framework#2290]
I've installed Oqtane.Demo31 module, but when trying to call either the local service or the remote one, I get authorization errors.

As for the local service:
![image](https://user-images.githubusercontent.com/90258222/179180893-646de8da-c92b-4640-a47b-d6d5c98e0906.png)
But I am logged in as the user created with the installation of Oqtane, which does have "Host Users" role.

As for the remote service:
![image](https://user-images.githubusercontent.com/90258222/179181157-3f5d2dc4-cc0a-4bd2-a315-53eaadbd8c23.png)
I'm getting "Unauthorized" so it seems it's not even able to read the current authentication state. I've already checked that the secret is correctly stablished in both "Token Settings" in Oqtane and "appsettings.json" in the WebAPI.

I have not made any changes whatsoever to the module, just downloaded the zip and generated the Nuget package for installation.

I've also tried to recreate the module myself, with my own WebAPI, and I get the same errors.

**Comment by sbwalker** [comment]
I cannot reproduce the problem locally. I have the Oqtane.Demo31 module installed and compiled. I logged into my Oqtane Framework as a host user and went into User Management in the Admin Dashboard. I went into the settings and I added a Client Secret to my Token Settings:

![image](https://user-images.githubusercontent.com/4840590/179220737-a1cf9249-2010-4558-8604-404b09f23965.png)

I clicked Save so that the Client Secret was saved. Then I navigated to the Demo page which had been created by the Demo31 module and I clicked on the Call Local Service button... and I get a valid response:

![image](https://user-images.githubusercontent.com/4840590/179221100-6ccfe365-8aa6-40a3-9291-ce2b3e744ba3.png)

**Comment by leigh-pointer** [comment]
@sbwalker I never did the example before but did watch the YouTube.  So today download the example and ran it with no problems.  So I can also clarify that the code works. (just a head up)

**Comment by mdmontesinos** [comment]
I just fixed the issue. 

When installing Oqtane, it established by default the password of the first user as the secret for the token, and I assumed that was ok. However, the secret is required to be at least 16 characters, but that condition is not checked for the initial one. I also tested that if you manually update the secret with less than 16 characters, it is filled with '?'. Perhaps that should be done as well for the default.

When manually updating the secret to be 16 characters or more, the authorization works perfectly.

Thanks for the help!
