### ISSUE TITLE
3rd Party Control Support

### ISSUE THREAD

**Issue by bbakermmc** [oqtane/oqtane.framework#23]
One of the problems with a lot of frameworks like these is they are built w/out any 3rd party controls like DevExpress, Telerik, SynFusion, etc.  So then when you start programming, some of the UI elements tend to look "off" because maybe some of the pages that are defied in the framework havent been updated to use the other control sets.

I havent looked at the framework fully yet, but it would be nice if you implemented helpers to render out controls that way they could be overridden easily if we wanted to use DevExpress editors and such.

Or is that like a "theme" instead?

**Comment by sbwalker** [comment]
You have to walk a fine line when it comes to application frameworks. On the one hand you should not dictate a specific commercial control suite - you should allow developers to use their preferred control suite ( and in fact you generally cannot distribute an open source framework with a commercial control suite anyways due to licensing restrictions ). On the other side, you need to provide at least a set of basic styles and basic controls so that the framework has cohesive look and feel.

**Comment by bbakermmc** [comment]
@sbwalker Correct, its always the issue :).  The base framework components usually look like bootstrap, in most cases they are tied to admin type pages so its not too bad, but then the other pages have these nice styled controls, it would be nice to just implement an override on a tag helper or something.  Its something to think about since a lot of use use the 3rd party grids and stuff, we just want things to be uniform if possible and not have to re code all the pages you have already done.

**Comment by leedavi** [comment]
On a related, but slightly different angle.  This CSS framework is nice, light and easy.

https://www.w3schools.com/w3css/

It's basically a light weight Bootstrap, I've started to use it on most admin UI.

**Comment by iJungleboy** [comment]
From my DNN experience, I would not include _any_ css by default. Better put the admin-UI stuff in Iframes. The pain on the designers is just too great otherwise.

**Comment by bbakermmc** [comment]
@sbwalker Thanks for making Razor Components for things like the PermissionGrid, etc.  This will help with wanting to use controls like DevExpress.
