### ISSUE TITLE
Replace  JsonAsync<T>  with custom ones with error checking, logging ....

### ISSUE THREAD

**Issue by chlupac** [oqtane/oqtane.framework#232]
Any error in communication with controller now results in unhandled exception and application crash

**Comment by sbwalker** [comment]
I actually logged an error about this in the ASP.NET Core repo in September 2019 - https://github.com/dotnet/aspnetcore/issues/14041

**Comment by chlupac** [comment]
yes, but my class makes app more robust + logging of api calls

**Comment by sbwalker** [comment]
So I am trying to reconcile this suggestions versus the philosophy:

Microsoft Alignment

Although there are cases where it makes sense to come up with original solutions to development problems, it is generally an industry best practice to take advantage of the native solutions which are offered by the providers of the platform. This alignment helps to ensure that the approach is well validated and will be supported in the future. This focus on consistency also minimizes the time it takes for developers to come up to speed on your framework because they are already familiar with the approach based on their other development efforts. In DNN there were many creative solutions, some of which may have been slightly better than what Microsoft provided, however in the long term they became a barrier to entry for new developers and a maintenance headache for the platform. Oqtane will utilize the Microsoft recommended approach as much as possible and only be creative in the areas where Microsoft does not offer a solution. A good example of this is that Oqtane uses Nuget for its packaging and deployment strategy as opposed to creating its own proprietary approach.

So the question is... does it make sense to introduce a custom extensions class to deal with a specific case where the Get method has an unexpected behavior - or is it better practice to use the standard Microsoft extensions class which all developers will be familiar with, even if they have to sometimes deal with the unexpected behavior ( which in all honesty is an edge case )? My opinion is that it makes more sense to use the standard Microsoft method in this case.

In additon, since Oqtane's goal is to support all hosting models - are you sure that your extensions class works in both server-side and client-side Blazor - client-side Blazor has its own HttpClient implementation.

**Comment by chlupac** [comment]
Ok, in this case we have to implement error checking in all service calls. You cannot expect correct data in all cases and in case of error you have to inform user about it.

**Comment by sbwalker** [comment]
Let's discuss this item a bit more. The one limitation with HttpClientJsonExtensions which I have encountered is with the GetJsonAsync() method and the fact that it throws a strange JSON parsing error rather than returning null if the object you are trying to load does not exist. Other than that, I find the HttpClientJsonExtensions to be quite useful and I believe most Blazor examples utilize these methods when teaching the platform to new developers. Which is why I made the comment that replacing it with a custom option needs to be considered carefully.

**Comment by chlupac** [comment]
If you look at my class, I take original framework one and made changes only on two places. Almost same changes which you recommend to do in dotnet/aspnetcore#14041

Another workaround of this is send allways List<T> with zero or one element and on service side 
take .FirstOrDefault()

**Comment by chlupac** [comment]
Against a philosophy, closing with respect, have to find another way how to deal with it.
