### ISSUE TITLE
Language Management Upgrade button not working

### ISSUE THREAD

**Issue by leigh-pointer** [oqtane/oqtane.framework#2323]
After clicking the Update button it appears to have updated but after a minute receive error email:
```
From: Studio-Elf
Sent: 7/28/2022 7:01:22 PM
To: host<[leigh.pointer@studio-elf.net](mailto:leigh.pointer@studio-elf.net)>
Subject: [www.studio-elf.net](http://www.studio-elf.net/) Site Error Notification

Log Message: Package Oqtane.Framework.Client.nl-NL.3.1.4 Is Not Registered

Please visit.....
```

**Error log:**

- `Language Package Oqtane.Client.nl-NL 3.1.4 Downloaded Successfully`

- `Package Oqtane.Framework.Client.nl-NL.3.1.4 Is Not Registered`

**Comment by sbwalker** [comment]
There are a few different problems here... 

The framework must use a convention for associating a translation to the core framework. There is a PackageId constant defined in Oqtane.Shared which has a value of "Oqtane.Framework". This PackageId is used as a prefix for identifying all Nuget packages related to the framework - which includes translations. This means that Nuget translation packages should be named "Oqtane.Framework.{language}.{version}" by convention. The reason why there is no need for ".Client" is because a Nuget package is a collection of assets - so it could contain both a Client and Server satellite assembly in the future (if localization is ever implemented for server components). 

The reason why you see the "Language Package Oqtane.Client.nl-NL 3.1.4 Downloaded Successfully" message is that the Add Language user interface simply queries the Registry for packages of type "translation" - and does not validate the package id prefix. I will need to add this capability to the registry.

This being said, there is a still a bug with the Language Management update feature, as it uses logic of Constants.PackageId + ".Client." + code to download a specific translation - resulting in the error message "Package Oqtane.Framework.Client.nl-NL.3.1.4 Is Not Registered". The logic will need to be modified to remove ".Client".

In reviewing the 3 framework translations, I see that all of them do not follow the correct PackageId prefix convention - they use Oqtane.Client rather than Oqtane.Framework. I am assuming this is because the instructions and examples in the oqtane.translations repo are not correct - this repo needs some attention as it does not help currently help translators get started or keep their translations up to date.

**Comment by hishamco** [comment]
> I am assuming this is because the instructions and examples in the oqtane.translations repo are not correct - this repo needs some attention as it does not currently provide useful information to help translators get started or keep their translations up to date.

I'm assuming there are changes have been made in the framework but the translations repo docs not updated

**Comment by sbwalker** [comment]
@leigh-pointer #2325 fixes the framework translation Upgrade issue. However I also added the filter to the Registry service so that it only returns framework translation results in Lanaguage Management. This required me to modify the PackageId for your Registry entry to use the Oqtane.Framework.{language} naming convention (I did not modify the actual Nuget package name in the Url - however in the future you may want to do this).
