### ISSUE TITLE
Unable to upload User Profile photo.

### ISSUE THREAD

**Issue by leigh-pointer** [oqtane/oqtane.framework#2390]
Using the user name link on the Nav bar you arrive at the User Profile

![image](https://user-images.githubusercontent.com/9447612/187854564-36feebc4-dda1-43f6-beae-f1fd4f724dfa.png)

Here you are unable to upload a User Profile Photo

**Comment by sbwalker** [comment]
@leigh-pointer I believe all of the image upload/display issues you logged are related to the recent change for the 3.2 release to support cross platform paths. And specifically the issue you encountered is that there is upgrade logic for the 3.2 release which changes the Path format in the Folder table to use back-slash (cross platform) instead of forward-slash (Windows). The reality is that the "path" which is stored in this table should never have used forward-slash because it is actually a Url path - not a file path. That being said, you may have encountered an issue in your dev environment because the framework version was moved to "3.2.0" a few weeks ago - but the upgrade logic for fixing paths in 3.2 was only merged a few days ago. So this means that the upgrade logic would not have been executed in your dev environment (because it thought it was already running 3.2). To resolve this issue, open your Folder table in your database and manually change the forward-slash characters to back-slash in the Path field. Then run the framework again and it should be fine. Note that this problem would not happen on a standard upgrade from a prior release to the 3.2 release - it only happened because there is ongoing development in the Dev branch.

**Comment by leigh-pointer** [comment]
@sbwalker they are ready are back-slash
![image](https://user-images.githubusercontent.com/9447612/187957760-55f47a59-e040-45c4-9412-62516601d094.png)

**Comment by sbwalker** [comment]
@leigh-pointer sorry I used the wrong terminology (I have updated my response above). Just to be clear, the Folder.Path field should be in the form "Public/" or "Users/1/" like a standard Url.

**Comment by leigh-pointer** [comment]
@sbwalker for some reason that didn't work. I don't understand why not.  I recreated the database and everything is now ok.  I will close all issues

**Comment by sbwalker** [comment]
@leigh-pointer my apologies for wasting your time on logging these issues - I should have posted an announcement that the changes to the Folder Path would cause issues for existing installations from the Dev branch. But it is nice to know that people are following along and testing the latest bits :)
