### ISSUE TITLE
Minor: Make Name and Panes abstract on ThemeBase

### ISSUE THREAD

**Issue by iJungleboy** [oqtane/oqtane.framework#2404]
These two properties should always be set on any custom theme. 

By making them abstract, we force developers to set them. 

BTW: For such simple wishes - should I even open an issue? or should I just create a pull request and explain why? What would you prefer?

**Comment by sbwalker** [comment]
I believe changing from virtual to abstract would be a breaking change, as it adds a requirement on all derived classes to implement the property. ThemeBase implements IThemeControl and the virtual pattern was used so that if the interface needs to change in the future, there are virtual property implementations which preserve backward compatibility. Name and Panes most likely should have been abstract rather than virtual however we do not want to introduce a breaking change now.
