### ISSUE TITLE
Change ActionLink to Button

### ISSUE THREAD

**Issue by mithang** [oqtane/oqtane.framework#2413]
How to change actionlink to button to onclick go to other component?
Ex: 
`<ActionLink Action="Add" Security="SecurityAccessLevel.Edit" Text="Add Controls" ResourceKey="Add" />`
`=> <button @onclick="@(()=>[What parrams to go to edit component])">Add</button> `

May you help me?

**Comment by sbwalker** [comment]
The ActionLink component is a link which can appear to be a button by using the Class parameter - just use the standard Bootstrap styles:

Class="btn btn-primary" 

If you want to handle the click event there is an OnClick parameter you can specify so that you can call a method in your component:

OnClick="@(async () => await YourMethod(YourParameter))"

I would encourage you to look at the razor components in the Oqtane.Client project as there are plenty of examples on how to use ActionLink in a variety of ways.
