### ISSUE TITLE
Lang context.Version not populated

### ISSUE THREAD

**Issue by leigh-pointer** [oqtane/oqtane.framework#2427]
![image](https://user-images.githubusercontent.com/9447612/191743826-6bae5b10-9edb-41e4-8b88-7f305fde9dc9.png)

**Comment by sbwalker** [comment]
@leigh-pointer So the challenge here is that when you Install a translation it is based on a "package". The standard package name for the Oqtane framework is "Oqtane.Framework". So when someone wants to install the Dutch translation for the Oqtane 3.2.0 release, the package name should be Oqtane.Framework.nl-NL.3.2.0.nupkg (and the Package Id in the Oqtane Marketplace should be "Oqtane.Framework.nl-NL").

A package contains files - usually assemblies... and satellite assembly names need to match the assembly they relate to. So the Dutch translation package would contain an Oqtane.Client.resources.dll in an /nl-NL subfolder (which is associated to the Oqtane.Client.dll). It is possible that in the future when localization is implemented for server-side resources there may also be an Oqtane.Server.resources.dll in an /nl-NL subfolder (which is associated to the Oqtane.Server.dll). During installation the contents of the package are extracted to the appropriate locations on disk (ie. /bin/nl-NL).

There is currently no location to store translation package metadata in the database. So the Upgrade Available logic attempts to use the version information of the satellite assembly file stored on disk. However the current logic is trying to use the Constants.PackageId ("Oqtane.Framework") for this scenario as well. So it is looking for a "Oqtane.Framework.resources.dll" in an /nl-NL subfolder - which is obviously not valid (the assembly is named Oqtane.Client.resources.dll) and results in the null version value in your screen shot.

I will modify the logic so that it looks for "Oqtane.Client.resources.dll" in the Upgrade Available scenario.

**Comment by leigh-pointer** [comment]
@sbwalker Ok , I understand, keeping the translation resources separated by Client, Server, Shared is IMHO a good way to go.
