### ISSUE TITLE
Challenge with "Oqtane" which should be part of the DLL name

### ISSUE THREAD

**Issue by iJungleboy** [oqtane/oqtane.framework#2438]
Sorry to come back with this, but I believe it's important. I'm also aware that I already had various similar issues posted like #2394 

I believe that the core team hasn't really felt these problems I'm about to describe, because the core projects all start with the namespace `Oqtane.xxx`.

### Convention: Namespaces in Companies

I believe most companies use namespace convention such as `MyCompany.Product.Module.Whatever`. 
In the case of Oqtane stuff, it's also usually `Oqtane.Theme.Themename` - like https://github.com/oqtane/oqtane.theme.bootswatch/blob/main/Vapor/ThemeInfo.cs

### Convention: Must use the term `Oqtane` in the DLL name

To optimize DLL loading (see #2394) at least all client DLLs require the term `Oqtane` as part of the DLL name.

### Convention: DLL name matches Namespaces

This one's pretty obvious: usually the DLL should match the namespace it provides.

## Issue: It doesn't mix well

If following this convention, the most obvious solution would be to create a company namespace such as `MyCompany.Oqtane.Theme.Themename`. But this is almost impossible to handle. It requires a lot of fiddling with `global::` and sometimes is nearly impossible to do. 

### Example with C# code

```c#
namespace ToSic.Oqtane.Themes.ToShineBs5.Client.Services;

public class Startup : global::Oqtane.Services.IClientStartup
{
    /// <summary>
    /// Register Services
    /// </summary>
    /// <param name="services"></param>
    public void ConfigureServices(IServiceCollection services)
    {
...
```
As you can see, the only way to make such a file compile, is to add a `global::` to any reference on something inside the Oqtane framework, because otherwise the compiler believes that `Oqtane` must mean `ToSic.Oqtane`.

This is nasty. There are some ways to mitigate this using global imports, but it's not intuitive and I believe it will cause a lot of trouble to less experienced developers.

### Example with Razor

With Razor files it gets even messier: 

![image](https://user-images.githubusercontent.com/5321186/192526632-2193a776-6332-4cb4-be3b-65078b7ec53f.png)

1. This long full name would work, if I didn't have the term `Oqtane` in my namespace. But like this, it appears to be impossible to implement - at least I can't figure it out. 
2. This one again might work - because I'm using global imports (again using `@using global::Oqtane.UI` - ugly) but it actually doesn't work at all.

## Intermediate Summary

So the problem is really this:

1. Any solution containing the term `Oqtane` in the namespace, but not at the very beginning, cannot really use the Oqtane framework parts. It's hard but possible when coding C#, and hard (or even impossible) for Razor
2. The DLLs must contain the term `Oqtane` for loading to work as expected. 

## Current Solutions

As of now, I can only think of these solutions:

1. Go against conventions and create a `Oqtane.ToSic.Theme...` namespace or `Oqtane.Theme.xyz` without the company name - to always start with Oqtane
1. Not use `Oqtane` in the namespace like `ToSic.Themes.xyz` and create a DLL with a different name, such as `ToSic.Themes.ThemeName.Client.Oqtane.dll`

## Options for Resolving

1. Standardize that all Oqtane solutions must start in the `Oqtane` namespace (I don't like this)
2. Recommend to always append `.Oqtane.dll` to DLL names and add a lot of documentation and examples so people don't run into this problem. I don't like this option, because people don't read docs until it's too late, and because it forces developers into a non-standard namespace-naming convention.
3. Change the Oqtane namespace (not an option 😉)
4. Provide another indicator on the DLL level to better detect what should be loaded

Of all these, only the third one actually makes sense. But I understand the current challenge as described in #2394 - where even a brief test to check all DLLs for use of a specific interface increased system startup by ca. 0.5 seconds. 

## Recommendation

I believe someone smart could come up with an idea 😉. Some Ideas I would have are:

1. In addition to looking for `.Oqtane` in the DLL name, also look for `.Client` - as this would match the anticipated namespace and DLL name
2. Find out what the bottleneck is in scanning DLLs for the interface (my guess is that it can't be by design, but maybe some DLLs lose a lot of time at first read because of certain issues we didn't notice)

**Comment by sbwalker** [comment]
@iJungleboy based on your post it appears that there is still some confusion in regards to the Oqtane assembly naming convention. I am guessing that part of the issue stems from the fact that all of the examples in the Oqtane repos are "owned" by Oqtane and therefore have a top level namespace identifier of "Oqtane". And the other part of the issue is that I am guessing you have never utilized the Module Creator or Theme Creator capability which is included in the framework.

The Module Creator and Theme Creator allow developers to scaffold an entire functional module or theme - including the recommended structure for the project, coding conventions, assembly naming conventions, etc.. The user interface within the framework allows a developer to provide parameters to customize the code generation process to match their identity: 

![image](https://user-images.githubusercontent.com/4840590/192548697-a1fbcd99-d235-480a-b2a8-6aa1b797be33.png)

The Owner Name and Module Name provided are used to create the namespace. So if the Owner Name provided is "ToSic" and Module Name is "Announcements" then the namespace generated is "ToSic.Announcements". 

Note that there is no reference to "Oqtane" in the namespace... the only requirement is that the assembly filename generated by building the module contains the term "Oqtane" (so that the framework is able to determine which assemblies need to be loaded into the app domain on startup - as described in #2394). This is accomplished with the following specification in each *.csproj file (note that the example below is for the Client project). Note that the *.csproj files are automatically generated by the Module Creator and Theme Creator so developers do not need to worry about this convention.

```
    <AssemblyName>ToSic.Announcements.Client.Oqtane</AssemblyName>
``` 

Note that even the Oqtane.Blogs reference module (https://github.com/oqtane/oqtane.blogs/blob/master/Client/Oqtane.Blogs.Client.csproj) as well as the Oqtane.Theme.Bootswatch reference theme (https://github.com/oqtane/oqtane.theme.bootswatch/blob/main/Oqtane.Theme.Bootswatch.csproj) use this approach. 

So as you can see, Oqtane is already using solution ##2 you described above. It has been using this approach since version 1.0 (the Module Creator and Theme Creator have always been included and recommended as the best starting points for developers). And I believe the reason why other developers have never raised this issue as a problem is because they have used the Module Creator or Theme Creator (or used the reference module/theme in the repos as an example).

**Comment by iJungleboy** [comment]
@sbwalker Thanks for this. 

I'm using something made with the theme generator, but others had already worked on it a lot, so I guess the result I'm seeing isn't the original any more, hence the confusion. 

In this case I assume most people will simply use this and not run into the problem I described. 

BTW: we have this assembly name, which I think would be a good idea to also use in the Generator, as it's updated when you rename things in your project: 

```
<AssemblyName>$(MSBuildProjectName).Oqtane</AssemblyName>
```

But in this case I guess my concern isn't as relevant as I thought. For me it's ok to close this :)
