### ISSUE TITLE
Naming conventions 

### ISSUE THREAD

**Issue by chlupac** [oqtane/oqtane.framework#245]
This is what I miss in Oqtane code. 
https://docs.microsoft.com/en-us/dotnet/standard/design-guidelines/naming-guidelines

https://github.com/ktaranov/naming-convention/blob/master/C%23%20Coding%20Standards%20and%20Naming%20Conventions.md

with help of refactoring tools is easy to put code to shape

**Comment by sbwalker** [comment]
This is a good suggestion as I am a firm believer in coding standards and consistency. I am concerned that a global refactoring could destabilize the application but the right time to do this is probably before the MVP release. I am noticing that some PR's contain massive amounts of code changes which are not functional but mainly cosmetic - which makes it really difficult to do a code review and identify potential issues. Hopefully implementing some common coding standards will improve this situation.

**Comment by hishamco** [comment]
I already have some doubts about the code conventions, I may push some minor PRs to resolve the issue, instead of a HUGE one ;)

**Comment by sbwalker** [comment]
The main code conventions I would like Oqtane to follow are the guidelines specified in https://docs.microsoft.com/en-us/dotnet/standard/design-guidelines/naming-guidelines ( as mentioned by @chlupac ). So this is primarily related to naming conventions ( upper/lower case, local variables using "_", etc... ). This is not related to changes to the architecture. Smaller PRs would be better than massive ones so that they are easier to review.

**Comment by hishamco** [comment]
Ok, I will start on this one soon ..

**Comment by chlupac** [comment]
Strange Logger (again) problem after #252 
modulebase is null when logger is trying log successful login. 
![image](https://user-images.githubusercontent.com/7838468/76095143-1643eb00-5fc4-11ea-8c50-67246f2a0a53.png)

**Comment by sbwalker** [comment]
Sounds like a regression issue related to #252 - someone will need to track it down. This is why I was hesitant to introduce such a widespread change to the codebase.

**Comment by chlupac** [comment]
I'm trying to debug it now

**Comment by chlupac** [comment]
I have it. Preparing PR now

**Comment by sbwalker** [comment]
Due to the inconsistent upper/lower case naming of local variables and parameters in the original code, it is likely that there may be a few regression issues. That being said, it should be possible to look at the history and code differences to help identify the problems.

**Comment by hishamco** [comment]
@sbwalker don't worry I will have a look too, that's why I suggested CI/CD and unit tests

**Comment by chlupac** [comment]
@hishamco Good job with renaming. You are using R#? Some files are not processed yet (mainly .razor)

**Comment by hishamco** [comment]
> You are using R#?

Nope, I'm using VS 2019, I just do it manually which is take time ;)

>  Some files are not processed yet (mainly .razor)

I will have look

**Comment by chlupac** [comment]
I will also help with task.

**Comment by hishamco** [comment]
Thanks ...

**Comment by chlupac** [comment]
Almost done. Some issues in razor files left.
Server processed completely.

**Comment by hishamco** [comment]
I will have a look to the latest bits

**Comment by thabaum** [comment]
A little off topic here my apologies.  I am wondering if you could put a set of standards on the project site or home page for git hub with this link to naming conventions for .NET but also for CSS possibly?  It is hard to change a community of developers habits down the road and it would be nice to see some guidelines to help new module developers out for helping style things as using ID's is bad practice I believe.  I have not reviewed how things are done in this project yet but just wondering if there is any thought in this direction.  Also a stylesheet load order if any priority is set like in DNN.  Not sure if this is in Oqtane as well.  Portal.css and Page.css should load last IMO and poor mod dev apps dont declare a priority get top priority doing so.   Pages have different load orders of different stuff depending on mods fighting over different styles on top of bootstrap...  
Sorry again for the question just very curious and it relates to this issue here a little.  Thank you.

**Comment by sbwalker** [comment]
@thabaum for .NET guidance we are trying to follow the Microsoft guidelines: https://github.com/dotnet/aspnetcore/wiki/Engineering-guidelines ( @chlupac and @hishamco have done a ton of work in the past couple weeks to get the code closer to utilizing standards ). On the CSS side the goal was to try to use Bootstrap 4 styles as much as possible and not re-invent the wheel by introducing a lot of custom styles. There are a few CSS styles in the app.css file which are prefixed with "app-" to ensure there are no conflicts. As far as CSS loading order is concerned, there are not so many levels in Oqtane as there are in DNN - there is a global app level and a theme level ( currently there is no page or module level ).
