### ISSUE TITLE
REF #2427 Oqtane.Client.resources.dll in the Upgrade Available scenario.

### ISSUE THREAD

**Issue by leigh-pointer** [oqtane/oqtane.framework#2464]
@sbwalker 

> I will modify the logic so that it looks for "Oqtane.Client.resources.dll" in the Upgrade Available scenario.

was this done as my 3.2.1 package is not recognized.  DLL is installed to the correct folder.

**Comment by sbwalker** [comment]
#2443 should have resolved the problem you reported in 3.2.0 (#2427). When I go to the Oqtane Marketplace I do not see a Dutch Translatiion for version 3.2.1 - I only see version 3.2.0:

![image](https://user-images.githubusercontent.com/4840590/196502772-e6317bf9-93cf-47cc-8706-e2b80d1dcea4.png)

To summarize the expected behavior:

- if a user wants to install a new language they would go to Language Management and choose Add Language. If they want to install a Translation they would choose the Translations tab and choose Download and then Install. In order for this to function correctly, the Translation needs to be registered in the Oqtane Marketplace and follow the naming convention Oqtane.Framework.Language.Version.nupkg (ie. Oqtane.Framework.nl-NL.3.2.1.nupkg).

- for languages which are already installed, the main Language Management view will display an Upgrade button next to a language if there a newer version of a Translation which is registered in the Oqtane Marketplace. In order for this to function correctly, there needs to be a satellite assembly in the appropriate language folder under the /bin with the appropriate naming convention (ie. nl-NL/Oqtane.Client.resources.dll) and the Version of the satellite assembly must be less than the Version of the Translation available in the Oqtane Marketplace.

**Comment by sbwalker** [comment]
I don't think it would be possible to test it locally, as the Update Available feature is dependent upon the Oqtane Marketplace having the latest version of the package?

**Comment by leigh-pointer** [comment]
Ok, should we not then remove the option to upload Languages?

I did a test whereby I deleted my language pack (I had to refresh the page to see if it had been removed) and requested it 3.2.0 from the Marketplace.  That didn't work (maybe due to framework and language not same version) so now waiting for nuget to index.

Package 3.2.1 now indexed and still will not install.

**Comment by leigh-pointer** [comment]
Oqtane.Framework.Language.Version.nupkg  <- this has changed as it used to be Oqtane.Client.Language.Version.nupkg 

Will rebuild and change the build project to reflect the new format.

**Comment by sbwalker** [comment]
In #2323 I tried to explain: 

"The framework must use a convention for associating a translation to the core framework. This is done using a PackageId constant defined in Oqtane.Shared which has a value of "Oqtane.Framework". This PackageId is used as a prefix for identifying all Nuget packages related to the framework - which includes translations. This means that Nuget translation packages should be named "Oqtane.Framework.{language}.{version}" by convention."

and mentioned that:

"In reviewing the 3 existing framework translations, I see that all of them do not follow the correct PackageId prefix convention - they use Oqtane.Client rather than Oqtane.Framework. I am assuming this is because the instructions and examples in the oqtane.translations repo are not correct - this repo needs some attention as it does not currently provide useful information to help translators get started or keep their translations up to date."

and as a temporary resolution I indicated:

"This required me to modify the PackageId for your Registry entry to use the Oqtane.Framework.{language} naming convention (I did not modify the actual Nuget package name however in the future you may want to do this)."

And in #2427 I explained that the naming convention of the satellite assemblies within a Translation package (*.nupkg) should use Oqtane.Client, Oqtane.Server, etc... as the resources need to be related to framework assemblies. The Upgrade Available feature uses these assemblies to determine the version of the translation which is currently installed.

**Comment by sbwalker** [comment]
@leigh-pointer I see that the Dutch translation has now been upgraded to 3.2.1 - has the problem you reported been resolved?

**Comment by leigh-pointer** [comment]
@sbwalker yes, I followed the conventions and my site upgraded.
![image](https://user-images.githubusercontent.com/9447612/196703769-bda43115-ad14-47c8-b781-3b5b87cfeaab.png)

However, locally unable to install from the market place.  The procedure works, downloads, unpacks but when Oqtane is restarted the language is not picked up.  Dropdown is selected and nothing changes.

**Comment by sbwalker** [comment]
I see what you mean... I did not have any languages installed locally so I installed the Dutch translation from the marketplace and restarted my application... but the Dutch language was still not available. I had to Add the Language in order for it to be displayed in the list of languages and become available in the language selector for the site... and then once I chose the language in the language selector it worked:

![image](https://user-images.githubusercontent.com/4840590/196749520-30657bab-b298-4e35-ac6f-e3a861ba7f41.png)

So it works but the user experience is not optimal. The tricky part is that there are 2 different concepts and personas which are represented here. There is the concept of Languages which are defined for a Site by an Administrator. And then there are Translations which are applicable to an entire Installation which can only be installed/upgraded by a Host User.

**Comment by sbwalker** [comment]
#2466 attempts to improve the user experience in this area...

1. Each Site needs to define the Languages it supports (this is completely independent of whether there are any Translations in the installation). 

![image](https://user-images.githubusercontent.com/4840590/197021001-4c86411f-2255-4b50-afd6-b555693f743d.png)

2. When an admin navigates to Add Language they will now have the option to specify if they only want to see Languages which have a corresponding Translation installed, or if they want to choose from a list of all Languages. In the scenario where no Translations have been installed previously they will need to choose the latter option and add a Language.

![image](https://user-images.githubusercontent.com/4840590/197021056-78dbfdc5-6622-4c9c-9af0-b03b90118b5e.png)

3. Once a language has been added, it will be displayed in the Language Management list. If the user is a Host User, the list will also indicate columns indicating if a Translation exists for the Language by displaying its version. If no Translation is installed but a Translation is available in the Marketplace, a "Download" button will be displayed for the Language. If a Translation is installed but a newer Translation is available in the Marketplace, an "Upgrade" button will be displayed for the Language. 

![image](https://user-images.githubusercontent.com/4840590/197021272-d7a94b23-6bbb-4748-95e0-5545d17e5749.png)

(the reason it says Upgrade above is because I was testing the upgrade functionality by first installing an earlier version of the nl-NL translation package in my install)

4. If either the Download or Upgrade buttons are selected, the Review License Terms modal will be displayed which now includes information about the Translation including owner, downloads, version, and release date. The user can select Accept or Cancel at this point to proceed with the installation process.

![image](https://user-images.githubusercontent.com/4840590/197021557-c18cec25-0dd3-40d3-b83b-c089c88758ec.png)

**Comment by leigh-pointer** [comment]
@sbwalker sounds good will give it a try later, but sounds fluid enough.
