### ISSUE TITLE
Unclear how to add JavaScript (Google Analytics) to Theme Header

### ISSUE THREAD

**Issue by iJungleboy** [oqtane/oqtane.framework#2488]
I'm trying to add GTM (Google Tag Manager) for Google Analytics to my theme on the theme (as is must be on every page). 

Based on #1967 I tried various approaches

1. There we discussed using the `PageService` but I can't see any APIs which would allow me to do this
2. We also discussed the `Page.Meta` property which is a string. Like `PageState.Page.Meta = "<script>test</script>";` I tried setting but but the result was very unexpected:
    1. One one hand, the stuff I added didn't appear on the page
    2. But then when I went to edit the page settings, the stuff I had added in the page was now in the `Meta` settings of the page
3. Using Resources also seems wrong, because you can't add inline JS using Resources, only URLs.

What is the right way to do this? thx!

**Comment by sbwalker** [comment]
Ok, so it sounds like you need to inject an inline script into the head of the page and you want the script to be present on every page in your site. There are only 2 ways you can accomplish this in Blazor:

(1) including the inline script in the _host.cshtml payload which is generated server-side and sent to the browser in the initial page render. This approach is required if the intended client consuming the page content does not support JavaScript (ie. web crawlers, bots, etc....).
(2) use JS Interop on the client-side after the initial page renders (as this is the only recommended way to manipulate the DOM in Blazor). 

Oqtane does not currently support inline scripts in the _host.cshtml payload.. It does support a "Meta" property which is intended for including "meta" tags in the page head. This is accomplished by editing the Page Settings within the Oqtane user interface and specifying the meta tags in the Meta field so they are saved to the database. On subsequent server-side renderings of the page, the Meta tags will be injected into the page head. It should be noted that although the Meta property is intended for meta tags, it would be possible to specify an inline script and it would be injected into the page head. That being said, the Meta property is only available at the Page level currently - not the Site level - so it would need to be specified for every Page to accomplish your goal. It would probably be useful in the future to support this feature at the Site level as well and allow it to be overridden at the Page level. But including scripts in a Meta field does not really make sense... so maybe Meta should be renamed to "HeadElements" so that any head element could be supported. It should also be noted that the PageState cascading parameter is intended to be read-only - you should never override its values in code - you should only get the values for use in your own components (the strange behavior you encountered is because you set the Meta property programmatically). 

Oqtane does provide a variety of JS Interop methods for managing the DOM. There is an IncludeScript() method which is intended for the purpose you described. The IncludeScript() method has a variety of parameters so that it can support external script references as well as inline scripts, and provide control over whether they are injected in the head or body of the page. That being said, it appears that there is a bug that was introduced at some point in the associated JavaScript method. The script should be declared as:

```
    includeScript: function (id, src, integrity, crossorigin, content, location) {
        var script;
        if (id !== "") {
            script = document.getElementById(id);
        }
        else {
            script = document.querySelector("script[src=\"" + CSS.escape(src) + "\"]");
        }
        ...
```

And the expected usage for an inline script in the head would be:

```
    await interop.IncludeScript("gtm", "", "", "", "test", "head");
```

Note that "gtm" above is the id and "test" is the innerHTML of your inline JavaScript method. You need to specify the "id" parameter so that the system is able to determine if it was already injected previously. The innerHTML for GTM would be the body of the function "(function(w,d,s,l,i ... );" without the enclosing script tags (as these will be added automatically).

I am guessing that the JS Interop approach may be preferable in your scenario?

**Comment by iJungleboy** [comment]
Thanks for this and also the infos why I had my strange side effect. It may be wise to make the set properties read-only of those objects, but certainly not a priority. 

The script method sounds good and I can certainly work with it. But you write it _should_ be this way, which seems to say it isn't working ATM?

Note also that the script method sounds good, but for most users it would be even easier if the resources of a theme would be able to include the body already (which then goes through interop anyhow).

**Comment by sbwalker** [comment]
@iJungleboy maybe I was not clear in my note above where I said "it appears that there is a bug that was introduced at some point in the associated JavaScript method". The current logic for includeScript in 3.2.1 is

```
    includeScript: function (id, src, integrity, crossorigin, content, location) {
        var script = document.querySelector("script[src=\"" + CSS.escape(src) + "\"]");
        if (script === null) {
```

but the correct logic should be:

```
    includeScript: function (id, src, integrity, crossorigin, content, location) {
        var script;
        if (id !== "") {
            script = document.getElementById(id);
        }
        else {
            script = document.querySelector("script[src=\"" + CSS.escape(src) + "\"]");
        }
        if (script === null) {
```
When inserting inline script you need to rely on an Id as there is no other way to determine if the script has already been inserted into the page.

**Comment by iJungleboy** [comment]
@sbwalker You're right - by "User" I actually mean the theme developer. My suggestion is to enhance the Resources. 

API so far: 

```c#
public override List<Resource> Resources => new()
{
    new() { ResourceType = Stylesheet, Url = $"{ThemePath()}theme.min.css" },       // Bootstrap generated with Sass/Webpack
    new() { ResourceType = Script, Url = $"{ThemePath()}bootstrap.bundle.min.js" }, // Bootstrap JS
    new() { ResourceType = Script, Url = $"{ThemePath()}ambient.js", },             // Ambient JS for page Up-button etc.
};
```

New maybe: 

```c#
public override List<Resource> Resources => new()
{
    new() { ResourceType = Stylesheet, Url = $"{ThemePath()}theme.min.css" },       // Bootstrap generated with Sass/Webpack
    new() { ResourceType = Script, Url = $"{ThemePath()}bootstrap.bundle.min.js" }, // Bootstrap JS
    new() { ResourceType = Script, Url = $"{ThemePath()}ambient.js", },             // Ambient JS for page Up-button etc.
    new() { ResourceType = Script, Body = $"console.log('test');", },               // OPTION TO ADD BODY
};
```

This would just make it easier so the Theme developer doesn't need to go too deep into the inline script stuff himself.

**Comment by sbwalker** [comment]
I liked your suggestion above so I mocked up a quick prototype, and quickly ran into a behavior which I had discovered previously. In a single page application, after the initial page render... the page is never fully refreshed (like it would be in a server-based application). So when you add an inline script to Menu1 and then navigate to Menu2 using the client-side navigation, the inline script which was added previously remains in the page content because it is never explicitly removed - but it is inactive because it was already executed. For example, my prototype injected a simple alert('Test'); inline script... so upon navigation to Menu1 it displayed the popup but when I navigated to Menu2 the inline script remained in the page content but was inactive, so no popup. One possible approach is that the Resource manager could remove the inline script and then re-insert it into the page so that it is active and gets executed. 

Note that for external JavaScript references this is never really a problem as the reality is that once a JavaScript resource is loaded for a site, it is never unloaded. However, this behavior was a problem for CSS resources and as a result Oqtane uses a complicated algorithm based on Ids to determine which CSS references need to be added, removed, or preserved (including hierarchical ordering) during client-side navigation.

**Comment by iJungleboy** [comment]
@sbwalker  I completely understand this. 

Anybody adding stuff to the header should know that it's a SPA and will not load it again and again. 
So the JS must be written in a way that knows about this. 

Basically this is what we call an **ambient** javascript, one that's always there. 

Anything else which must be triggered on every page will have to use interops, and I don't think that can be simplified. 

But ambient-inline JS would benefit a lot if it could be simply added like this. Just like ambient external JS.

**Comment by iJungleboy** [comment]
Just for more context: When adding GTM or Google Analytics, our solution would be to include the main script in the theme, and trigger custom events to GTM for every page-change.

**Comment by sbwalker** [comment]
My simple prototype a theme injecting an alert() into the body rather than the head (as I assumed that both page locations needed to be supported). But perhaps my prototype was not a valid example as developers would never use alerts in this manner.

**Comment by iJungleboy** [comment]
@sbwalker I believe we will meet both kinds of developers 😉. And for some cases such as google-analytics it would actually be easier, because that's the default way analytics would work. SPA implementation needs more love. 

But external scripts don't get re-run either, so I believe we don't need to support that assumption. At least not for now. 

For now, just being able to add an ambient script which runs would be a big step forward.

**Comment by sbwalker** [comment]
#2496 adds the capability you requested ie. the ability to declare inline scripts in Resource declarations:

```
    public override List<Resource> Resources => new List<Resource>()
    {
        new Resource { ResourceType = ResourceType.Stylesheet, Url = ModulePath() + "Module.css" },
        new Resource { ResourceType = ResourceType.Script, Content = "console.log('test');" }
    };
```

Note that you do not need to specify an Id as the framework will generate it automatically.

**Comment by iJungleboy** [comment]
@sbwalker awesome, thanks a lot!

**Comment by vnetonline** [comment]
@iJungleboy Did you manage to build a theme that includes GA script and the uses GTM on each page change

I am trying to do the same .... your help with this will be much appreciated

**Comment by iJungleboy** [comment]
@vnetonline sorry I don't have much time, but as a minimal guidance

1. Make sure the JS is included
2. Make sure any page-change event is also tracked

* we have a base class in our cre8magic library, which triggers it https://github.com/2sic/cre8magic/blob/main/ToSic.Cre8Magic.Client/Themes/MagicTheme.cs#L87-L94
* That will send an event to Analytics for every page (optionally not the first page, as that is often auto-tracked already) https://github.com/2sic/cre8magic/blob/main/ToSic.Cre8Magic.Client/Analytics/MagicAnalyticsService.cs
* The GTM interop helps https://github.com/2sic/cre8magic/blob/main/ToSic.Cre8Magic.TestTheme.Client/src/scripts/ambient/gtm.ts

Our code is quite a bit more complex, as we are striving to make it "just work" with configuration only in a json file.
