### ISSUE TITLE
Multi-Language Sites and Pages in Oqtane

### ISSUE THREAD

**Issue by iJungleboy** [oqtane/oqtane.framework#2499]
## Background

We just released our proof of concept (PoC) to create [awesome websites using Oqtane - blazor-cms.org](https://blazor-cms.org/). 

![image](https://user-images.githubusercontent.com/5321186/201602157-f7f1319e-3b82-45d1-8d98-a5ce5f59b955.png)

As you can see in our [blog post](https://2sxc.org/en/blog/post/demo-of-oqtane-as-cms-blazor-cms-org) we believe that Oqtane is ready for prime time, the only thing that's really missing is multi-language sites and pages. I believe we would then have everything a website needs and this would be a huge boost to Oqtane.

## Requirements

I'm pretty open to the best way to do this. My only long-term experience is with DNN, so I'll list some basic requirements from there, before looking at implementation details:

1. **Base URL for each language/culture**: In general each language should have an own site URL because usually people will navigate in the same language - so that should be fairly early on in every URL. Typical examples would be de.blazor-cms.org or blazor-cms.org/de, but for most modern examples blazor-cms.org/de (or blazor-cms.org/de-ch/) would be the preferred way to address language roots. 
2. **Unique but connected Pages**: Pages can vary a lot by language - and sometimes not be published in specific languages - it's important to allow editors to create very different pages in every language. Of course the system must know their relationships, so that switching languages makes the user stay on the same page. 
3. **Unique and sometimes connected Modules**: In many cases a user start with the primary language, and will then create the other languages. In this 80% scenario, the new pages have the identical modules on them to start. If the module itself is multi-language, that's all that needs to be done. In other cases, the user may wish to make changes to the copied module in the target language.

## Implementation

As noted before, my experience is primarily with DNN and that model has worked well for us. But I do also know that it is sometimes hard for editors to work with - so maybe there is an even better way. 

Your ideas? Can this be done fairly soon?

**Comment by iJungleboy** [comment]
We don't mind developing such an extension ourselves. 

Our biggest concern would be that we create a solution for this, which would then be different from a future "standard" implementation in Oqtane and cause a lot of headache. 

So my understanding @sbwalker is, that Oqtane doesn't plan on doing anything in this direction at all, so we wouldn't have to worry about that. 

👉🏽 Is this correct?

To make this reasonably possible, we may need 2-3 extensibility points which may not exist yet. 

👉🏽 Could Oqtane add these while staying in line with the philosophy?

**Comment by sbwalker** [comment]
Correct - content localization, versioning, workflow, etc... are not on the current roadmap for Oqtane.

It is impossible to answer the question about extensibility points without an actual technical proposal to review. In general, every extensibility point essentially becomes part of a public API which needs to be maintained in the long term, so it is very important to validate that every extensibility point is absolutely required in order to serve the user base.

One thing I will say is that although the DNN approach to content localization worked from a user experience perspective, the actual technical implementation was far from optimal. It was highly invasive to the overall framework and basically imposed a tax on all users of the framework regardless of whether they needed content localization or not. Essentially, DNN implemented a tenancy model within a tenancy model - which created a lot of redundancy and complexity at multiple levels of the framework. So I would not be in favor of technical implementation which emulated the DNN approach.

**Comment by sbwalker** [comment]
To better explain what I mean by "tenancy model within a tenancy model" you can refer to the following diagram:

![image](https://user-images.githubusercontent.com/4840590/204291551-8372b679-703c-405e-b9be-1fd8eb6e12b7.png)

DNN had a multi-tenancy model where you could have a distinct set of content for each site in an installation. The content localization implementation then took that one step further and allowed you to have a distinct set of content for each Language within a site (left side of diagram above). The concept made sense on the surface however it soon became apparent that there were many other types of site content other than simply pages which also needed to be localized ie. site settings, role names, urls, profile settings, etc... And as the framework was modified to support localized content for each of these additional areas it eventually became obvious that DNN had implemented a tenancy model within a tenancy model.

With the benefit of hindsight, the better approach would have been to simply leverage the existing tenancy model which already allowed for a distinct set of content for each site. So rather than creating pages for each language within a site, it would have been better to have dedicated sites for each language..  and then have a separate service which performs synchronization and maintains the relationships of equivalent pages across sites. This approach would allow for complete localization of every type of content in a site, could leverage the existing permissions model, and would avoid polluting the framework with an additional tenancy model which creates complexity and performance issues.

**Comment by sbwalker** [comment]
I am also fairly certain that the synchronization service I mentioned above could be developed using the server-side events introduced in 3.2.1 - the details are documented here: https://www.oqtane.org/blog/!/53/oqtane-server-events

**Comment by iJungleboy** [comment]
@sbwalker Thank you so much for these insights!!!

I like your idea with the multiple sites and sync. I do see a few issues which I hope you could give me some suggestions how to approach:

1. User and role management: users should be the same across languages, so that they don't get logged out as they change
2. Managing data which is used by multiple sites - for example the page map which knows what EN page is what DE and FR page: where would we do this in Oqtane?
3. there's probably more, but these are the ones that quickly popped into mind...

Some thoughts:

I believe it would need a concept like a "Site-Group" which would know what sites tie together (to keep them separate from other sites which are not part of the group. Possibly there could be a primary site, which would store the shared data, such as users, roles, page maps...

Your thoughts?

**Comment by sbwalker** [comment]
1. Users are already shared across sites. If you need to synchronize roles across sites you would need to do this in a custom extension.
2. You would need to create a custom extension which synchronizes pages across sites and maintains the relationships between those pages. 
3. It would also need some type of grouping mechanism to associate the related sites (the concept of a site group could work here).

**Comment by iJungleboy** [comment]
The first answer is a bit surprising: Users are always global, so they are not site-specific? But roles are? thx...

**Comment by sbwalker** [comment]
Users are global within a tenant (ie. database) - which basically means if you are using a shared tenancy model and have multiple sites sharing the same tenant database then the users are shared between those sites. If you are using an isolated tenancy model where each site has its own tenant database then users are not shared. Roles are always specific for each site regardless of tenancy model. This is consistent with the .NET Core Identity model - which was based on ASP.NET Membership - which is what DNN used as well.
