### ISSUE TITLE
Fallback in scenarios where WebSockets are blocked by a Firewall

### ISSUE THREAD

**Issue by iJungleboy** [oqtane/oqtane.framework#2500]
In #2495 we have a conversation about using public websites such as https://blazor-cms.org/ - in cases where someone cannot see an Oqtane page because his corporate firewall blocks WebSockets. 

I'm surprised to see such a setup, but I can imagine that this could be quite common in highly controlled environments, since the firewall can probably not scan the WebSockets messages. 

Since I don't know the internals I did some research but it's not comprehensive. 
From what I saw, the Blazor team had planned on _only_ using WebSockets by default, but then apparently realized that's not good idea: https://github.com/aspnet/Announcements/issues/470

It seems that in the original drafts, WebSockets always had a fallback, then they considered removing it from the default (but still supporting it), and then decided to put it in the default again. 

So I did some experimenting and tried to disable Websockets in chrome using TamperMonkey as explained here https://stackoverflow.com/questions/30912854/is-it-possible-to-temporarily-disable-a-websockets-connection-in-a-local-server

The result was an empty page and a console message `WS: Blocked.`

![image](https://user-images.githubusercontent.com/5321186/202049061-c1392a9a-966e-49f1-bcd7-3a87ca7299e7.png)

So I guess the questions are:

1. Is anybody (@sbwalker ) aware of this?
2. Does Blazor offer a built-in way to handle this?
3. ...and could we activate in on Oqtane, as I'm sure this would be better for any application (not just websites) that work on the public internet where we can't fully control the client devices and their security?

**Comment by leigh-pointer** [comment]
Blazor is built on SignalR which requires websockets, and basically cant run without it.
________________________________
From: iJungleboy ***@***.***>
Sent: Wednesday, November 16, 2022 12:53:14 AM
To: oqtane/oqtane.framework ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [oqtane/oqtane.framework] Fallback in scenarios where WebSockets are blocked by a Firewall (Issue #2500)


In #2495<https://github.com/oqtane/oqtane.framework/discussions/2495> we have a conversation about using public websites such as https://blazor-cms.org/ - in cases where someone cannot see an Oqtane page because his corporate firewall blocks WebSockets.

I'm surprised to see such a setup, but I can imagine that this could be quite common in highly controlled environments, since the firewall can probably not scan the WebSockets messages.

Since I don't know the internals I did some research but it's not comprehensive.
From what I saw, the Blazor team had planned on only using WebSockets by default, but then apparently realized that's not good idea: aspnet/Announcements#470<https://github.com/aspnet/Announcements/issues/470>

It seems that in the original drafts, WebSockets always had a fallback, then they considered removing it from the default (but still supporting it), and then decided to put it in the default again.

So I did some experimenting and tried to disable Websockets in chrome using TamperMonkey as explained here https://stackoverflow.com/questions/30912854/is-it-possible-to-temporarily-disable-a-websockets-connection-in-a-local-server

The result was an empty page and a console message WS: Blocked.

[image]<https://user-images.githubusercontent.com/5321186/202049061-c1392a9a-966e-49f1-bcd7-3a87ca7299e7.png>

So I guess the questions are:

  1.  Is anybody ***@***.***<https://github.com/sbwalker> ) aware of this?
  2.  Does Blazor offer a built-in way to handle this?
  3.  ...and could we activate in on Oqtane, as I'm sure this would be better for any application (not just websites) that work on the public internet where we can't fully control the client devices and their security?

**Comment by iJungleboy** [comment]
@leigh-pointer SignalR itself doesn't need websockets. 

> Quote: "It uses WebSockets whenever possible."

* https://learn.microsoft.com/en-us/aspnet/core/fundamentals/websockets?view=aspnetcore-7.0
* https://learn.microsoft.com/en-us/aspnet/core/fundamentals/websockets?view=aspnetcore-6.0

So if it's not available in Oqtane, this is by configuration/design, not by limitation of SignalR - or at least that's my understanding.

**Comment by sbwalker** [comment]
Oqtane uses the standard default configuration for Blazor Server - there is nothing custom about the way it is using this technology.

**Comment by Raceeend** [comment]
Then why doesn't it fall back to long polling in case websockets don't work?
You would expect that SignalR (Blazor) would fall back on long polling.
(see [https://learn.microsoft.com/en-us/aspnet/core/signalr/introduction?view=aspnetcore-7.0](url))

**Comment by sbwalker** [comment]
My understanding is that the long polling fallback for SignalR does not work well for Blazor Server because long polling does not guarantee the delivery order of messages - and because Blazor Server is so dependent on client/server messages for UI interactions, the approach does not work well. In addition, long polling is much more resource intensive on the server and has higher latency.

**Comment by iJungleboy** [comment]
> My understanding is that the long polling fallback for SignalR does not work well for Blazor Server because long polling does not guarantee the delivery order of messages - and because Blazor Server is so dependent on client/server messages for UI interactions, the approach does not work well. In addition, long polling is much more resource intensive on the server and has higher latency.

Reading this https://learn.microsoft.com/en-us/aspnet/core/blazor/host-and-deploy/server?view=aspnetcore-6.0#transports-1

... would mean that it is actually built to use long polling. 

According to the specs, the console should show:

> Failed to connect via WebSockets, using the Long Polling fallback transport. This may be due to a VPN or proxy blocking the connection.

...but it should work. As the message would show, is that having VPN or Enterprise Firewalls block WebSockets is an expected problem. 

There seem to be some timeouts which need a higher value. Maybe these are too restrictive on Oqtane?

**Comment by sbwalker** [comment]
@ijungleboy As mentioned earlier, Oqtane uses the default configuration settings for Blazor Server. It sounds like it is possible to customize the configuration but the fact that there is so little guidance around this would lead me to believe the issue described in this thread is quite obscure - I have never encountered it with any of the Blazor Server apps I  am hosting. The other option of course is to use the Blazor WebAssembly hosting option as it does not rely on any persistent client/server connections - so it does not require websockets or long polling.

**Comment by iJungleboy** [comment]
@sbwalker I'll see if we can do some research on our side, ok?

**Comment by iJungleboy** [comment]
@sbwalker ok. I have a lot on my desk ATM but hope to try this end of December or January.

**Comment by iJungleboy** [comment]
...if you want, you can assign me to the task.
