### ISSUE TITLE
Problem with Initial Password when installing Oqtane

### ISSUE THREAD

**Issue by iJungleboy** [oqtane/oqtane.framework#2512]
When installing Oqtane it always starts with the slightly scary dialog with DB etc.

Basically I always (seriously) need about 20 tries to get a password which it will allow - because it just complains but doesn't say what's wrong. 

I believe we should at least specify what the supposed guidelines are for the password, so people don't get frustrated. I really tried all kinds of number ABC abc !? combinations. 

My guess is that the password had parts of the user name in it or something (for my dev installs) and that complained.

Interestingly I can later set the simple password in the admin-UI, it's only blocked during installation.

**Comment by sbwalker** [comment]
User account creation in Oqtane is controlled by .NET Core Identity password complexity criteria. By default, .NET Core Identity requires that passwords contain an uppercase character, lowercase character, a digit, a non-alphanumeric character, and must be at least six characters long.

**Comment by iJungleboy** [comment]
I kind of assumed that criteria, but even when I did all that it didn't work. For local dev I always use a simple setup because I have so many installations. Fake example: user `2sicSuperUser` and password `2sicSuperUser` - but Oqtane also complained on `2sicSuperUser!` which would fit all the criterias. Even something like `2sic-SuperUser!` didn't work. 
So it appears that there is also a check if significant parts of the user name appear in the password. 

I believe mentioning this in the setup would be helpful.

**Comment by sbwalker** [comment]
#2515 includes a more detailed error message "The Password Provided Does Not Meet The Complexity Policy. Passwords Must Be At Least 6 Characters In Length And Contain Uppercase, Lowercase, Numeric, And Punctuation Characters." It is possible that .NET Core Identity also ensures that the password does not contain the username - but that is just a fundamental best practice. 

I was also able to determine that the complexity policy was not being fully utilized in the password change scenario, so it has now been fixed as well so that it is consistent throughout.
