### ISSUE TITLE
Since the 3.3.0 Framework version - Modules can not be added to a page.

### ISSUE THREAD

**Issue by leigh-pointer** [oqtane/oqtane.framework#2561]
**Trying to add the Framework HTML module**

1. Adding a module from the control panel does not add the module to the page.
2. I checked the Log and the Module was created.
3. Looked at the DB I see records for the module.  Records exist in **Module** and **PageModule** Tables.

Ran the same with the same result on Live, Test and Dev.

Using my Forked instance of the Framework the module is added correctly.

What is strange is that it occurs on 3 totally separate instances.

**Comment by leigh-pointer** [comment]
Ok so it isn't me.   Just downloaded new source 3.3.0 unpacked and built and ran.  Can't add HTML module.

**Comment by leigh-pointer** [comment]
So it looks like that EntityId is not being populated. But even after updating with the correct EntityId the module still did not show :(

![image](https://user-images.githubusercontent.com/9447612/212463577-1e58429f-11e8-42a3-9c0c-162df2e39d03.png)

**Comment by sbwalker** [comment]
I was able to reproduce the issue. Your analysis above is on the right track but the actual problem is the EntityName. The Control Panel has logic for populating the permissions for the new Module being added based on the Page permissions (and the Visibility selected by the user). The problem is that the Control Panel never explicitly set the EntityName property to "Module" in the past... and this used to work fine because the framework assumed that a collection of permissions were all associated to the same entity. However with the recent permission enhancements in 3.3.0, a collection of permissions can be for multiple entities so it now uses the specific EntityName property value specified.

**Comment by leigh-pointer** [comment]
@sbwalker will you be releasing a patch for this fix?
