### ISSUE TITLE
Improve Connection String Handling

### ISSUE THREAD

**Issue by iJungleboy** [oqtane/oqtane.framework#2567]
As of now, a typical Oqtane site has one DB and stores the connection string in two locations:

1. The `appsettings.json`
2. The DB in the table `Tenants`

This causes problems when moving the DB, because the DB Admin and whoever else is involved must know this. 
I understand that the idea is for large, complex systems to be more flexible, but I would suggest an enhancement.

**Goals**

1. The most common, simple installations should stay simple
2. Large/complex installations should remain flexible

For this to work, the idea is that anything that just wants to re-use the main connection should not store it in the DB as a copy, but somehow reference the original in the `appsettings.json`. Either by storing an empty value or by storing the connection name (nicer, because it would allow for more connections to be stored in the `...json`. 

My suggestion is: 

1. that the DB entry can `DefaultConnection` - or any other connection name in the `appsettings.json`
2. when a user creates/modifies a tenant, there is a dropdown for connections - listing the ones from appsettings. By default, the `DefaultConnection` is selected. If he/she choses `manual` they can add something else, but to be honest that's a very rare case.

**Comment by sbwalker** [comment]
This will require some research as it is a core aspect of the multi-tenancy capability which supports isolation (in addition to shared tenancy). The main area I would be concerned about is the migrations abstraction which handles multiple types of databases.

**Comment by sbwalker** [comment]
This enhancement request was very well articulated and is well aligned with the goals of the framework. In particular, developers expect connection strings to be located in appsettings.json, so storing them in any other location has the potential to cause confusion. There have been numerous issues logged over time by developers who were trying to migrate Oqtane to a new infrastructure and were blocked because they did not understand Oqtane's unique connection string approach. The enhancement described in this issue will make this area much easier to manage in the future. 

The challenge was introducing this change in an upgradeable and backwards compatible manner. Since database connections are so central to the functionality of a framework like Oqtane and also support third party module integrations, great care had to be taken to ensure a seamless upgrade experience.

The biggest challenge ended up being the DBContextBase class... and in particular the challenges of inheritance in .NET when using dependency injection. It turns out that are many articles documenting this problem, as well as a variety of solutions, however by the time you run into this dilemma it may already be too late to code your way out of it. In a nutshell, base classes generally have dependencies... and these dependencies need to be passed to the base class from your derived classes. This all works well until you need to add an additional dependency to the base class - as it means that all derived classes will need to be modified to support this change. 

In the case of DBContextBase, it had 2 dependencies already... but I needed to add another through DI - IConfigurationRoot - which would allow me to obtain a connection string from appsettings.json. Here is an example of the HtmlTextContext derived class - notice the base() logic which contains the 2 existing services needed by DBContextBase:

```
        public HtmlTextContext(ITenantManager tenantManager, IHttpContextAccessor httpContextAccessor) : base(tenantManager, httpContextAccessor) { }
```

It turns out that if you are developing a base class and there is ever any chance that your dependencies will change in the future, it is best to create a dedicated "dependencies" class. This class has the flexibility to add/remove dependencies without affecting any derived classes. DBContextBase has now been modified to have a dependencies class - which allowed me to add IConfigurationRoot and can also support other potential changes in the future.

```
        public HtmlTextContext(IDBContextDependencies DBContextDependencies) : base(DBContextDependencies) { }
```
This works well for the future but what about existing derived classes which are dependent upon the current DBContextBase interface? Luckily .NET included a ConfigurationBuilder capability which allows you to create the Config service without dependency injection. This is clearly an anti-pattern and is less than optimal, but it works and it allowed me to retain the old constructor for backward compatibility (and emit a compiler message to let developers know they should upgrade their code to the new method).

```
        [Obsolete("This constructor is obsolete. Use DBContextBase(IDBContextDependencies DBContextDependencies) instead.", false)]
        public DBContextBase(ITenantManager tenantManager, IHttpContextAccessor httpContextAccessor)
        {
            _tenantManager = tenantManager;
            _accessor = httpContextAccessor;

            // anti-pattern used to reference config service in base class without causing breaking change
            _config = new ConfigurationBuilder()
                .SetBasePath(Directory.GetCurrentDirectory())
                .AddJsonFile("appsettings.json")
                .Build();
        }
```

Once this major challenge was out of the way, the rest of the solution was fairly straightforward. Basically the DBConnectionString property in the Tenant database table no longer contains the full connection string - it only contains the name of the connection which refers to the actual connection string that is stored in appsettings.json. Upgrade logic was included to perform this migration automatically.  

The user interface needed to be updated in a number of places as a result of this change - in particular Site Settings and Site Management (when adding a new site). I also took the opportunity to change the terminology in the UI from using "tenant" to "database" as the tenant concept seems to cause a lot of confusion. Lastly, Sql Management was overhauled so that it is driven from the list of database connections in appsettings (rather than from the Tenant database table) and now allows you to add additional connections as well (even ones that are not related to the Oqtane framework).

This turned into a fair amount of work but I think it is a worthwhile improvement for the framework.

**Comment by sbwalker** [comment]
Note that the ConfigurationBuilder approach for backward compatibility does have a limitation for environments which are using an environment-based appsettings file. This is because it needs yet another service dependency (IWebHostEnvironment) in order to determine the environment (which is not possible based on the existing services passed to DBContextBase):

ie .AddJsonFile($"appsettings.{WebHostEnvironment.EnvironmentName}.json");

Hopefully not many people are using environment-based appsettings files... and that developers upgrade to the newer constructor in their code which avoids this problem altogether.
