### ISSUE TITLE
Control panel is too narrow

### ISSUE THREAD

**Issue by chlupac** [oqtane/oqtane.framework#258]
width 1200 px.
Please use divs instead of tables for dialog design. Tables are not responsive.
![image](https://user-images.githubusercontent.com/7838468/76089532-1c34ce80-5fba-11ea-9485-d5f5d6a1f549.png)

**Comment by mikecasas** [comment]
Decided to add on to this issue instead of opening a new one, is there a way to increase the width of the middle container (Content Pane)? 

When viewed normally my content is bunched, but when I click on Edit of the HtmlText control the additional space formats it perfectly. Is there a way to set the width of the Content Pane for each page?

**Comment by chlupac** [comment]
yes, it's bootstrap classes, I will fix it in spare time

**Comment by mikecasas** [comment]
No, I know it's bootstap, I can adjust the size and move on, but I was wondering if there was a better way for the framework to handle something like this.

**Comment by chlupac** [comment]
Here is wrong classes used in template and modules do not fill empty space correctly

**Comment by chlupac** [comment]
Solved with #264 
![image](https://user-images.githubusercontent.com/7838468/76166339-09f39580-615e-11ea-8f7c-74a4a25c1b4c.png)

**Comment by chlupac** [comment]
@mikecasas best solution - make your own theme and design it as you like
