### ISSUE TITLE
SQLite database init fails with 'An Error Occurred Creating Site. An error occurred while saving the entity changes. See the inner exception for details.'

### ISSUE THREAD

**Issue by markdav-is** [oqtane/oqtane.framework#2584]
When pulling master for v3.3.1 and running the startup screen in the SQLite configuration it stops after a few moments with the error "An Error Occurred Creating Site. An error occurred while saving the entity changes. See the inner exception for details."  no additional details are captured in the logs.

![image](https://user-images.githubusercontent.com/311063/217147394-00c3cd7d-c004-4923-8642-53e9010f5206.png)

**Comment by sbwalker** [comment]
Thank you for reporting this issue... it turns out that this is a bit tricky. In version 3.2.2 migrations were introduced to remove the DeletedBy, DeletedOn, and IsDeleted columns from the Folder and File tables (as these columns were never used). However SQLite does not support the ability to drop columns - so the migration executes fine but does not remove the columns from the tables in the database. And then the system tries to create some folder records during install and it fails because the IsDeleted column has a NOT NULL constraint. I am going to have to investigate if there is a way to remove the constraint so that this works on SQLite. Multi-database support is a real challenge based on the fact that not all database engines support the same basic operations.

**Comment by sbwalker** [comment]
There is no ability to alter a column in SQLite either... so no ability to change the constraint. Which basically only allows for 2 options:

1. Add the IsDeleted properties back to the Folder and File entities and identify them as deprecated. The IsDeleted property will still need to be explicitly set to avoid the SQLite error during insert - even though the property is meaningless to the rest of the framework.
2. Remove the deprecated properties from the EntityBuilders. This will ensure they are never added on a new install. However this will not resolve the issue for users that are already running on SQLite and want to upgrade to a later version of Oqtane.

Option 1 is the better approach so that Oqtane can meet its upgradeability philosophy. In the future this essentially means that properties should not be physically removed from database entities if they are not nullable.

**Comment by markdav-is** [comment]
thanks for addressing this.
