### ISSUE TITLE
Error rename a file

### ISSUE THREAD

**Issue by lthoa** [oqtane/oqtane.framework#2596]
![image](https://user-images.githubusercontent.com/6874322/218726387-8ea6725f-0aef-4175-95ef-6512af30e267.png)

**Comment by sbwalker** [comment]
@lthoa can you please provide the exact steps to reproduce - I am unable to duplicate the problem using the current code in Dev branch.

**Comment by lthoa** [comment]
@sbwalker error occurred when renaming files in the 'My Folder' folder

![image](https://user-images.githubusercontent.com/6874322/219040512-f52a2d20-2d90-40ab-9176-3de6911ac0a0.png)

**Comment by sbwalker** [comment]
Thank you for clarifying... I will try to reproduce the issue locally.

**Comment by sbwalker** [comment]
So it turns out that this issue had nothing to do with renaming a file. The differentiating factor between "My Folder" and other folders is that "My Folder" has the Capacity property set by default. When the Capacity property is set the framework needs to calculate the total size of the files in the folder to determine if the Capacity has been exceeded. This calculation logic was causing the list of files to be tracked in EF Core - which resulted in a tracking error during update.
