### ISSUE TITLE
Exclude legacy Permissions property setter is breaking change 

### ISSUE THREAD

**Issue by tvatavuk** [oqtane/oqtane.framework#2687]
I'm writing this issue only if the breaking change was not intentional.

It is related to commit [exclude legacy Permissions properties from serialization/API payload](https://github.com/oqtane/oqtane.framework/commit/af3b289331ad2e03db2845651bfd502fa6a070ec#diff-5ec13562e24c77e30d39477ca4211188c8c4964b76540ce5baf0514d695caeeb
).

Old third-party code that was setting `Oqtane.Models.Folder.Permissions` string property can not work any more, because it is read-only now.

Upgrading this code to use the new property `PermissionList` collection makes it incompatible with older Oqtane versions.

We used reflection to workaround this.

I realise all benefits of new implementation and I'm 100% behind it. 

Thanks

**Comment by sbwalker** [comment]
This change was intentional. The vast majority of third party modules only consume permissions and rely on IsAuthorized calls based on Module permissions - so backward compatibility was preserved for this scenario. If your module was leveraging permissions for custom entities and was actually setting the Permissions value using the PermissionString model and custom access control string format then it will experience a breaking change, as the amount of legacy code that would have been required to provide backward compatibility for this specific scenario would be highly problematic for the framework long term.

**Comment by sbwalker** [comment]
The specific commit you identified was where a change was made to make the Permissions property Read-Only. This was done because it was assumed that if a module contained logic where it was setting this property, then it must be managing permissions in the old custom format which is no longer supported. 

Perhaps this was the wrong assumption? 

If your module was retrieving Permissions from the PermissionGrid using GetPermissions() then they would be in the new format and if you were simply assigning them to the Permissions property without doing any custom manipulation then it actually should have worked fine. But the read-only property is preventing this.
