### ISSUE TITLE
Hitting refresh after edit mode clicked takes you out of edit mode

### ISSUE THREAD

**Issue by thabaum** [oqtane/oqtane.framework#2713]
I am not sure if this is by design issue is by design:

  Adding an HTML module, save module after editing the HTML module, manage settings and then save... and Oqtane stays in edit mode.

If I click the browser refresh button Oqtane is no longer in edit mode.  Is this by design?

**Comment by thabaum** [comment]
@sbwalker It looks like this is a bug and was something attempted to being fixed in fix #2640

I will look at the area you were fixing to see what can be done as this gives me an idea of what you had planned for it.

It should be stored in a cookie or local storage or state management saved/restored along with event handlers for when the page is reloaded.

I can probably fix this up or clue you in on the issue more once I play a bit with this tonight if not later this week.

**Comment by sbwalker** [comment]
Can you please explain why you are doing a browser refresh? A browser refresh does a full page refresh from the server rather than relying on the standard client-side behavior which leverages the the client-side state which is already loaded. Basically in a SPA architecture, users should avoid doing browser refresh operations (which are common in server-side architectures). A reset of the edit mode is the expected behavior in a browser refresh as it basically indicates that a page should be displayed in its "default" state.

**Comment by thabaum** [comment]
While editing sometimes I hit refresh to see how things are going or to refresh the state of a component (not the page edit mode)
