### ISSUE TITLE
To Cache Or Not To Cache

### ISSUE THREAD

**Issue by chlupac** [oqtane/oqtane.framework#272]
I realized recently than some info is somehow cached. Generally I'm not big fan of caching, It's often source of strange bugs and developer frustration.

Which information are cached and why? 
Performance impact of this?
Can be caching switched off?
And how to clean cache correctly in case of changes?

**Comment by sbwalker** [comment]
The framework does not use caching in the traditional sense. It is a client/server application and all client interaction is managed through the site router. The site router is using cascading parameters to manage state so that it can be shared with all components in the hierarchy. The two main cascading parameters are the PageState which is populated at the site router level, and ModuleState which is populated for each module instance on a page. PageState contains a variety of information for the current site, page, and user which can be used within modules. This prevents modules from having to manually load the information themselves ( which obviously has a performance impact as every web service call has latency and processing time ). PageState is not fully rebuilt for every user interaction... the site router has logic to determine whether any criteria has changed which affects items in the PageState. If criteria has changed, it reloads those items which are affected. The performance impact of this is very significant as it drastically reduces the number of web services calls for each user interaction. In a multi-user environment there may be changes to a site in one client which affect the PageState in other clients. As a result there is a synchronization service which orchestrates the state invalidation. Currently it is not possible to turn off/disable PageState - it is an integral part of the site router. If the router is working correctly there should be no need to "clean the cache" - however if you want to reload the state you simply need to open a new browser tab and browse to the site - it will initialize the PageState when the client loads.

**Comment by sbwalker** [comment]
As a side note, when it comes to caching in server applications I am also not a fan for the same reasons you described. Only the most commonly requested entities which rarely change are being cached on the server in Oqtane ( ie. Alias, ModuleDefinition ).

**Comment by chlupac** [comment]
Thank you.  I'm little bit more in picture now.
