### ISSUE TITLE
Edit site is not working when site is not working

### ISSUE THREAD

**Issue by tvatavuk** [oqtane/oqtane.framework#2721]
Issue is related to `Admin / Site Management`.

It is visible when sub-site is not working as demonstrated in #2720. Where main site is working but sub-site `s1` is not working.

## Steps

1. On main site (https://oqtane-poc212.oqtane.me/) open `Admin / Site Management`.

![image](https://user-images.githubusercontent.com/2724850/229807447-2ba01074-a2ae-4eba-a404-24f0e263320d.png)

2. Click on **Edit** for sub-site `s1`.

![image](https://user-images.githubusercontent.com/2724850/229807499-36d7583e-c26d-4e2f-844f-9b11a6d5ede4.png)

Edit site is not working, because site edit is executed with in sub-site  (https://oqtane-poc212.oqtane.me/s1) that is not working because of #2720.

It will be great if we can edit `s1` site options, on main site (https://oqtane-poc212.oqtane.me/).

**Comment by sbwalker** [comment]
The expected behavior of the Edit button in Site Management is that it navigates you to the other site (where you can edit if you have the appropriate rights). The security architecture prevents you from accessing APIs or performing any type of management for a site with a different alias. This is by design.
