### ISSUE TITLE
Invalid template when I try and use the Deploy to Azure button

### ISSUE THREAD

**Issue by vnetonline** [oqtane/oqtane.framework#2733]
Deployment template validation failed: 'The resource 'Microsoft.Web/Sites/AmazingSolutions/config/connectionstrings' is not defined in the template. Please see https://aka.ms/arm-syntax for usage details.'. (Code: InvalidTemplate)

**Comment by vnetonline** [comment]
Fixed the Deploy to azure submited the [pull request #2771](https://github.com/oqtane/oqtane.framework/pull/2771)

1. removed depends on connection strings
2. Moved sku outside properties for type Microsoft.Web/serverfarms and added various app plans
3. Removed worker size and replaced with instance capacity
4. Replaced database and sqlserver to use various editions
5. Updated ApiVersions for various types

**Comment by sbwalker** [comment]
@vnetonline I have used the Deploy to Azure option a few times now and it works great - the only thing I noticed is that there is a noticeable delay between when the the resources are deployed and when the Oqtane app is provisioned - but once you understand that the template is still being installed then you just need to be patient. One small item I would suggest is that the SQL Server database which is provisioned by the template should be the Basic tier rather than the Standard tier by default. The Basic tier is only $5 per month and provides 2 GB of space which is more than enough for Oqtane (a default install only consumes 30 MB). The Standard tier is $30 per month and provides 250 GB of space.

**Comment by sbwalker** [comment]
@vnetonline yes, I understand that its the Azure orchestration which causes the delay. Setting the App Service to Basic B1 is a good change as well - essentially it means that in $USD the Azure cost for an Oqtane instance is ~$60 - and the multi-tenant capability of Oqtane allows you to host multiple sites, making it a very economical option (I am hosting 10 sites from an Oqtane instance using the Basic tier and it works great).

**Comment by vnetonline** [comment]
I am still trying to get around this theme issue I have
