### ISSUE TITLE
Issue: CSS styling breaks when navigating from page to page

### ISSUE THREAD

**Issue by vnetonline** [oqtane/oqtane.framework#2850]
I am trying to create a new theme using the dev repo which is Version 4.0.0 with the latest Head and Body Content i have the following in my ThemeInfo

![image](https://github.com/oqtane/oqtane.framework/assets/15242923/2b8c28f8-f7af-4266-94bd-15260ec30583)

but the script is never added ... style sheets work fine and I can see them in the head .

**Comment by vnetonline** [comment]
I have added the `level` and `location` attributes and it seems to be working now the scripts are added to the body 

![image](https://github.com/oqtane/oqtane.framework/assets/15242923/d58a849b-4421-47e3-a37e-639bb794defe)

![image](https://github.com/oqtane/oqtane.framework/assets/15242923/98a8dbe9-1d0f-4d2d-9eed-fab95343efe5)

**Comment by sbwalker** [comment]
Just to clarify, when you said the script references were not added to the page... were you doing a View Source in the browser... or were you using your browser's developer tools to examine the DOM? The reason I am asking is because script references that are injected dynamically will not appear in View Source.

**Comment by vnetonline** [comment]
I was looking in the browser view source ... but you are right they appear in the head and can see them in DOM using browser developer tools if I take out `level` and `location`

**Browers view** 
![image](https://github.com/oqtane/oqtane.framework/assets/15242923/14427ae1-3205-4ea7-abaf-9d33298acb1e)

**DOM in Browers Dev tools**
![image](https://github.com/oqtane/oqtane.framework/assets/15242923/8cf206ba-0b6f-4057-90c4-81ff850b4c93)

since they are being loaded dynamically I don't think they run because I am getting a whole bunch of errors

![image](https://github.com/oqtane/oqtane.framework/assets/15242923/27f49e33-562c-43be-862d-6e6a9635f91a)

**Comment by sbwalker** [comment]
If they are in the DOM then it means they are being registered. The error would be caused by how you are using the JavaScript in your code. Are you using JS Interop or are you including JavaScript directly in your components? And if you are using JS Interop are you only calling it in OnAfterRenderAsync? And are you using flow control to ensure the JS library is loaded before calling its methods? The DNF.Projects project provides some examples of how to use JavaScript. In general, the idea behind Blazor is to try and avoid JavaScript and use native C# methods.

**Comment by vnetonline** [comment]
Yes i am using JS interop and using similar loagic which is in the DNF Projects and the Default Oqtane theme here is what I see 

I have managed to clear all the errors, my `OnAfterReder` looks like this 

![image](https://github.com/oqtane/oqtane.framework/assets/15242923/0d23e3e7-7e83-4a48-a531-aa4cad197d2a)


this is the result i am getting on load the UI flashes with no css styling which does give user a good experience.

![screen2gif-missing-css-on-theme-onload](https://github.com/oqtane/oqtane.framework/assets/15242923/bb915e8d-a0b9-42db-9ac5-f3bb9f24c3fc)

I have notied this happing on First installation page as well 

![screen2gif-missing-css-on-installation](https://github.com/oqtane/oqtane.framework/assets/15242923/9a86835e-867f-4164-9837-5eb91f04dfa6)

**Comment by sbwalker** [comment]
In version 4.0.0, stylesheets are now managed by the Head root component - they are not dependent on JS Interop as they were in prior versions of Oqtane. That being said, the way that Blazor updates the DOM may be problematic ie. if it removes the link elements and then re-adds them it may cause a "flash" in the browser U. The JS Interop method used by Oqtane in the past used a complex algorithm to only update stylesheet links if they actually changed (it did not remove and re-add them on each render). It appears that more research will be necessary to determine if 4.0.0 will need to revert to using the old logic for managing stylesheets.

**Comment by sbwalker** [comment]
@vnetonline I am not able to reproduce the UI "flash" you included in your screen shot above. Can you please include how you are declaring your style sheets.

**Comment by sbwalker** [comment]
@vnetonline can you also share what your Site Settings are for Hosting Model - Runtime and Prerender?

**Comment by vnetonline** [comment]
@sbwalker 

here is how i am declaring style sheets the theme is based on the free [AdminLte ](https://github.com/ColorlibHQ/AdminLTE)

![image](https://github.com/oqtane/oqtane.framework/assets/15242923/08bd1646-5c48-42c7-8667-973071919bd9)

The Runtime is `Server` and Prerender is `ServerPrerendered`

![image](https://github.com/oqtane/oqtane.framework/assets/15242923/a0103db4-ddfd-4204-95e8-3bb718d3b425)

**Comment by vnetonline** [comment]
I am using chrome but i have tested on ms edge and I get the same result 

I have also created a server page from a stock standard ms template the flash doesn’t happen in there 

So it is definitely something in Oqtane

**Comment by sbwalker** [comment]
Is it happening in Oqtane 3.x? I am asking because in 4.0 I took advantage of the new .NET 7 method for CSS - but perhaps it does not fully work. Note that a default Blazor template created in .NET 7 is not a good comparison as all CSS and JS references are hardcoded in the server page itself (which would never work in a framework).

**Comment by sbwalker** [comment]
@leigh-pointer have you tested your Rocket Fuel theme on Oqtane 4.0 yet? Any issues such as the ones described in this thread?

**Comment by leigh-pointer** [comment]
@sbwalker there are a few issues but they are expected with new functionality in Oqtane Framework 4.0.  However, using the default theme and navigating to **Page Management**  selecting a page wtih RocketFuel Theme applied for edit I do see the RocketFule settings, but hitting save didnot save the changes.

**Comment by sbwalker** [comment]
@leigh-pointer I should have been more clear with my earlier question... I was curious if you were seeing a "flash" in the browser when the CSS was injected into the page on version 4.0? @vnetonline documented some behavior earlier in this thread which I can not reproduce locally (and I am guessing is caused by the custom prerender JavaScript he is using) so I was looking for feedback from other users.

**Comment by leigh-pointer** [comment]
@sbwalker no flash

**Comment by vnetonline** [comment]
I have just uploaded the theme I am working on to a repo located here 

[Amazing.AdminLTE](https://github.com/vnetonline/Amazing.AdminLTE)

@sbwalker if you download and set it to this theme then you should be able to replicate the issue.

**Comment by sbwalker** [comment]
@vnetonline did you try your theme on Oqtane 3.x to determine if this is a new behavior or existing behavior?

**Comment by sbwalker** [comment]
It also appears that the CSS references are for Bootstrap 4 - whereas Oqtane has been on Bootstrap 5 for the past 2 years. There were breaking changes between Bootstrap 4 and 5 which means that the Control Panel and Module Actions will not work properly unless you are using a compatible version of Bootstrap.

**Comment by vnetonline** [comment]
Okay so now I am trying a new theme that is compatible with Bootstrap 5.3 and uses no jquery 

I am still getting the flash

![screen2gif-missing-css-on-nice-admin-theme-onload](https://github.com/oqtane/oqtane.framework/assets/15242923/7a2bc810-0b70-4c68-8e65-0a52d1a56005)

![image](https://github.com/oqtane/oqtane.framework/assets/15242923/e120f54e-3391-4a91-bb76-4546ad0a0b8c)
 uploaded repo here 

[Amaizng.NiceAdmin](https://github.com/vnetonline/Amazing.NiceAdmin/tree/main)

**Comment by vnetonline** [comment]
> @vnetonline did you try your theme on Oqtane 3.x to determine if this is a new behavior or existing behavior?

@sbwalker I just tried the Amazing.NiceAdmin theme on 3.4.1 and the flashing doesn't happen 

![screen2gif-missing-css-on-nice-admin-theme-onload-noflash](https://github.com/oqtane/oqtane.framework/assets/15242923/b1a12bbc-7154-4fbc-b113-2ce9d5e135b4)

**Comment by sbwalker** [comment]
@vnetonline I will investigate further. Did you say that the "flashing" is also happening for you with the default Oqtane or Blazor theme in Oqtane 4.0?

**Comment by vnetonline** [comment]
> @vnetonline I will investigate further. Did you say that the "flashing" is also happening for you with the default Oqtane or Blazor theme in Oqtane 4.0?

@sbwalker I can't notice the flashing with the default themes

**Comment by vnetonline** [comment]
@sbwalker If I navigate to the page which is set with Amazing.NiceAdmin theme and then press the back button yes i get the flash and css breaks on Oqtane 4.0.0

**Comment by sbwalker** [comment]
ok... then it must be something specific about the custom theme. My suspicion is that it might not have anything to do with the CSS and might be related to the number of JavaScript dependencies you are trying to load. In Blazor this requires JS Interop which can be slow... so perhaps the delay on the first page load is caused by all of the JS Interop calls. This is one of the main differences I see between your custom theme and the default themes. On that note, it is not clear to me why you are loading so many JavaScript dependencies - does your theme actually use 3 different types of charting libraries, the tinymce rich text editor, and a PHP form validator?

**Comment by vnetonline** [comment]
The thing is when I did the test on 3.4.1 it has the same amount of JavaScripts that are being loaded and there is no flash

When I do the same test with the with the same amount of JavaScripts then there is a flash

I even tried with no JavaScripts on 3.4.1 no flash

On 4.0.0 with no JavaScripts I get a flash 

There are a lot of themes out there which have several JavaScripts which make custom theme nice and visually appealing so hence trying to use a template rather then reinventing the wheel from scratch.

**Comment by vnetonline** [comment]
I just changed the title of this issue to

**Comment by leigh-pointer** [comment]
@sbwalker @vnetonline I get the same flash with RocketFuel (version 4)

**Comment by sbwalker** [comment]
@leigh-pointer  when you said "No Flash" in this comment (https://github.com/oqtane/oqtane.framework/issues/2850#issuecomment-1584525846) in the thread above, was it because you were using different test criteria (ie. you did not know the steps to reproduce)?

I still do not understand why the default themes included with Oqtane would not exhibit this same behavior, as they use the exact some approach for managing CSS in the page head.

As I mentioned earlier, if we can prove that this is a real issue then it basically means that the Blazor algorithm for applying dynamic changes to the DOM cannot be used for CSS references (due to the way that browsers process these changes). This would be really unfortunate as it would mean that we are getting limited benefit from the upgrade to .NET 7 and the use of Root Components (ie. it can only be used for Meta tags).  The good news is that Oqtane has a working solution to this CSS problem in prior versions that we can roll back to - even if it is far more complicated from a code perspective and relies on JS Interop.

**Comment by sbwalker** [comment]
@vnetonline what you are essentially referring to is FOUC - Flash Of Unstyled Content (more info here - https://dev.to/lyqht/what-the-fouc-is-happening-flash-of-unstyled-content-413j). This problem has the potential to appear in any browser-based application - usually on slower connections - and is related to the ordering of rendering events. SPA applications are especially tricky to deal with because the page content is never fully refreshed from the server - it is dynamically modified on the client. When you dynamically remove CSS references from the head of the page, the browser thinks it needs to react to this event immediately and renders the page without any styling... and then when new CSS references are added, it reacts to this event as well and re-renders the page. So if there is any latency between the removal and addition of the CSS references there will be FOUC. Oqtane 3.x dealt with this problem by using custom JS Interop to consolidate the remove/add operations into a single intelligent update operation (which is extremely complex based on the fact that the ordering of CSS references is critical for cascading to work properly). In Oqtane 4.0 the framework is using a standard Blazor Root Component (Head) to manage the content in the page head - which relies on Blazor's own internal DOM differencing algorithm - which may actually utilize an remove/add approach (I do not know). Basically I am just trying to explain the difference in technical approaches between Oqtane versions which may cause the difference in behavior. One thing which I want to investigate is if the new Head component is rendering multiple times with different content which may be contributing to the problem.

**Comment by leigh-pointer** [comment]
@sbwalker interesting and obviously a challenge.

**Comment by leigh-pointer** [comment]
> when you said "No Flash" in this comment ([#2850 (comment)](https://github.com/oqtane/oqtane.framework/issues/2850#issuecomment-1584525846)) in the thread above, was it because you were using different test criteria (ie. you did not know the steps to reproduce)?

Well yes and no.  One point is the CSS was being loaded the old way and RocketFuel was the default theme site wide.

**Comment by vnetonline** [comment]
Please see the resolution for this issue in merge #2902 which details that @sbwalker reverted to the old logic of injects stylesheets which doesn't cause the flashing 

![screen2gif-nicetheme-noflash](https://github.com/oqtane/oqtane.framework/assets/15242923/34b219c3-cf32-4e0d-9770-f87a44f17f12)

**Comment by sbwalker** [comment]
@vnetonline could please do me a favor? #2923 includes some logic which provides the ability to test the old and new approaches for rendering stylesheets. Once you get the latest code from the Dev branch and build you can use a querystring parameter to control the behavior:

http://localhost:44357/?method=old 

http://localhost:44357/?method=new

Please try the initial page load and browser page refresh scenarios using both methods and let me know if there is any noticeable difference in behavior. between them.

Do NOT bother testing the scenario of switching between different themes on different pages within the same site. That scenario has too many technical challenges and will not be supported.

Note that there is a slight difference between these latest methods and the previous tests you conducted. In this iteration both methods are initializing the stylesheet references in the head of the page (ie._host.cshtml) BEFORE Blazor begins processing.  I am curious if this was in fact causing the "flash" (ie. it may not have been a result of Blazor's rendering engine).

**Comment by vnetonline** [comment]
@sbwalker they work both the same way as I can see recording below 

![screen2gif-nicetheme-new-old](https://github.com/oqtane/oqtane.framework/assets/15242923/71fe4751-9e20-48d6-8fed-3066c24c378d)

The head when run in new way 

![image](https://github.com/oqtane/oqtane.framework/assets/15242923/6ade44e4-1f0e-49b6-b3a2-8e14d81081ff)

The head when run in old way

![image](https://github.com/oqtane/oqtane.framework/assets/15242923/501a9f4b-c4a2-4247-a4e2-c5d10b41df98)

**Comment by sbwalker** [comment]
@vnetonline thank you for testing these options. In reviewing the head markup (thank you for providing) I noticed that the stylesheet ordering was not behaving as intended. In addition, there was something in the way that you conducted your tests which did not produce the expected results. When running in "method=new" there should not be any "id=" attributes in the ```<link>``` elements (as these are only used in the "old" approach). This might have been because the "method" parameter was only constrained to a single page rendering... and if you navigated to another page using the menu, the parameter would be lost and the rendering would revert to the "old" method. I have merged a few PRs this morning which will allow you to conduct the tests again - this time the "method" parameter will be retained during navigation. Please use the same Urls:

http://localhost:44357/?method=old

http://localhost:44357/?method=new

Test the differences in behavior between these methods using the following 3 scenarios:

1. Entering the Url directly into the browser address bar and hitting Enter
2. Once a page is loaded using a specific "method" perform a browser page reload (using the reload button)
3. Navigate from page to page using the menu

Note that if you view the source using the browser dev tools and you are running the "old" method, the stylesheet references should have an "id=" attribute. If yoyu are running the "new" method, the stylesheet references should not have an "id=" attribute.

Please let me know your results.




2927

**Comment by sbwalker** [comment]
To provide some extra context for my testing requests, I want to clearly understand if there is a benefit of using the "old" vs "new" approach. There are different performance and code maintainability aspects to each approach, but the overarching requirement i that they function at run-time as expected from a user experience perspective - hence why the UI testing and comparison is so critical.

**Comment by vnetonline** [comment]
Okay will do and report back

**Comment by sbwalker** [comment]
@vnetonline & @leigh-pointer are either of you able to perform the CSS tests I outlined above? Specifically I simply need to know if there is any behavioral difference between them. I am personally not able to notice any difference but I would like to get more feedback.

**Comment by vnetonline** [comment]
Doing it now

**Comment by leigh-pointer** [comment]
@sbwalker for me the old way is better!

**Comment by sbwalker** [comment]
@leigh-pointer can you please elaborate on how the behavior is different when using method 
=old vs method=new. Specifically which scenarios out of the above are different?

**Comment by leigh-pointer** [comment]
@sbwalker so my test are with modules on the page! So first the theme loads then modules! (Real scenario) 
The old way theme loads, no flash only waiting for modules.
New way i get a flash and wait for modules to load!
Using Edge.

**Comment by sbwalker** [comment]
Thank you @leigh-pointer ... I upgraded oqtane.org to 4.0.0 and I am able to reproduce the behavior you described on the Blog page with the Edge browser. The .NET 7 root component is clearly removing and adding the style sheet references which causes the FOUC - whereas the old JS Interop method is performing an update. I will remove the "method=" A/B testing logic and consider this issue closed and ready for the 4.0 release. Thanks to both yourself and @vnetonline for your support on this item.

**Comment by vnetonline** [comment]
Finally we have got to the bottom of this I think I was going crazy … glad you got to reproduce the flashing and we have reverted to old way of updating stylesheets

**Comment by sbwalker** [comment]
Basically the core issue is related to browser compatibility, as different browsers seem to react differently to ```link``` elements being modified.

**Comment by sbwalker** [comment]
#2930 completes this work
