### ISSUE TITLE
ISiteTemplate ideas and extensions

### ISSUE THREAD

**Issue by chlupac** [oqtane/oqtane.framework#296]
Good start, thank you.
I have in my mind some ideas, enhancements, refactorings.

1. Site template should define not only pages but also other aspect of site (custom roles, profile fields, folders)
2. Site template should be data structure only and should be interpreted by server in moment of installation. Installation process should be done in dedicated class (SiteBuilder). Now is  installation process distributed through many classes and layers.   
3. Site template should allow to define own set of administrator forms and pages or possibility of replace some of them (custom login form, user profile form .... )
4. Module types should be defined by "refactoring friendly" way, not by magic string.

I'm interested in this area and I can do this contribution.

**Comment by ADefWebserver** [comment]
I suggest 'caution' with expanding features of this because too many options can cause problems for custom module developers because it can create too many 'use cases' that they have to support.

Oqtane does not have a huge 'custom module development' community yet, but, like with DotNetNuke it will. When it does, *that* will be what is most important to users. Those modules must work well or the entire Oqtane community suffers.

So, I just want us to be aware of anything that causes issues in that regard.

Thanks!

**Comment by chlupac** [comment]
Two things is important for me:
1. Separation of concerns, separate site creation from template, site repository, client form and move all business logic to one dedicated class.  
2. Extend possibilities of definition. Not so many options, but only roles and user profile.

**Comment by sbwalker** [comment]
I am not sure if some of the concepts behind ISiteTemplate are obvious from the implementation, so I will try to explain the rationale...

In DNN there was a concept of site templates. The way it was implemented was via an XML file which contained pages, modules, roles, files, etc... Since an XML file is a static resource which is external to the application and created at a point in time specific to a framework version, it was a nightmare to support in the long term through product upgrades - especially when entities often add additional properties from version to version or even larger refactorings occur to the framework which can be handled in the APIs for backward compatibility - but not easily handled in external XML files. In addition, developers would raise new requirements of things they wanted to accomplish via a site template and the framework would need to provide the implementation ( if the enhancement was approved ). This created restrictions which developers could not easily work around.

Oqtane uses a dynamic approach instead - a very simple interface method where a developer has the freedom to implement whatever logic they desire. They can add/update/remove roles, users, folders, files, themes, pages, modules, permissions, content, etc... They can even access the file system, make Http requests, modify config files, etc... With this approach framework upgrades will not be an issue and there is no restriction on what a site template can do.

**Comment by chlupac** [comment]
I agree with simple interface with one method : create site. I can add/remove  whatever I want with framework methods and classes. it's great, I like this concept. 
But I also like to have possibility start with clean site with opportunity to replace or modify current elements. Or make my template based on another one.
We should implement three templates with ISiteTemplate 

1. Clean site as base class 
2. Empty site, only with login and admin pages as a good startup for creating own templates
3. Demo site with all features of oqtane

**Comment by sbwalker** [comment]
I consider all of the Admin pages/modules as essential as if they are not included in a site you have no ability to manage the core framework entities. So I see 1 & 2 as the same template - with a blank Home page... and 3 is a template with the extra page content. And it’s possible for a developer to specify their desired install template in the appsettings.config file.
