### ISSUE TITLE
Theme update bug in oqtane in version 4.0.0

### ISSUE THREAD

**Issue by farhanalie** [oqtane/oqtane.framework#2973]
After updating to Oqtane version 4 I can't update the theme of the page, Theme dropdown only populates one item which is the default theme of the site. Even in my db, this page has a different theme. 

![image](https://github.com/oqtane/oqtane.framework/assets/21053342/8518800c-184d-491c-8d8b-4eedbb62119c)

**Comment by sbwalker** [comment]
This was a deliberate change in 4.0. There is a long thread about this topic (#2912) but the summary is that allowing completely different themes to be used on different pages within the same site has a lot of technical problems which cannot be resolved (due to SPA characteristics). 

For JavaScript it only works in scenarios where the themes are using the exact same version and source of JavaScript libraries (which is why it appears to work in the default Oqtane themes). However if themes use a different version/source of JavaScript libraries, there will be conflicts and the site functionality will break. 

CSS has similar issues - if themes use different versions or sources for Bootstrap, there will be a noticeable FOUC (flash of unstyled content) which occurs when the page is rendered.  

Therefore a change was made in 4.0 so that you can only use theme components from the same theme within a site. This helps ensure that the JS and CSS references will be consistent.

**Comment by sbwalker** [comment]
@farhanalie & @markdav-is this behavior was rolled back and replaced with a warning message in #3018 - this will be included in the 4.0.1 release:

![image](https://github.com/oqtane/oqtane.framework/assets/4840590/2bed9755-f5c2-4261-bf41-78140da00c5d)

**Comment by farhanalie** [comment]
@sbwalker That's great, thank you for considering it. When will 4.0.1 will be released?
