### ISSUE TITLE
When the first user is setup with a new install of Oqtane and  clicks on `My Page`  an error is logged

### ISSUE THREAD

**Issue by vnetonline** [oqtane/oqtane.framework#2978]
When the first user (Host User) is setup with a new install of Oqtane and  clicks on `My Page`  an error is logged

![image](https://github.com/oqtane/oqtane.framework/assets/15242923/e80edfc0-1a94-41bd-b48c-13b816da251a)

![image](https://github.com/oqtane/oqtane.framework/assets/15242923/24aabce2-c170-4784-aa09-428d30af053a)

The error is logged because there is no mypage/host which exists. so to fix this when the user is an ` Host User` and/or `Administrator User` then they are not to have personalized pages??

@sbwalker & @leigh-pointer your thoughts?

**Comment by sbwalker** [comment]
The behavior is supposed to be:

- if a page is flagged as personalizable then if a user navigates to that page...

- the system checks if a personalized version of that page has been previously created for the user. If a personalized page exists:

- it redirects the user to their personalized page

- else it displays the standard page and the user has the ability to click the Edit icon at the top left - which will dynamically create a personalized page for them and navigate them to it. 

- other users can navigate to the personalized page based on its unique path and view the page content.

**Comment by vnetonline** [comment]
@sbwalker I got the behaviour, but what I am trying to say is that when the host user which you created at the installation of Oqtane visits the My Page which is personalized it looks for mypage/hosts. 

Host's personalised page is not created and the site starts logging errors every time you visit My Page becuase mypage/host doesn't exist

**Comment by vnetonline** [comment]
If the user has the Role of `Host Users` then the host user should not have a personalised page??

**Comment by sbwalker** [comment]
@vnetonline I finally had a chance to take a closer look at this issue. You are correct that an error should not be logged for this scenario. The SiteRouter needs to be able to check if a personalized page exists, and if not, continue processing without logging an error. This has been resolved.

In regards to the differences in user behavior... if the user who is logged in has Edit rights to the current Page then clicking Edit will put them into Edit Mode for that page. Previously this would NOT create a personalized page for them (because there would be no way for them to administrate the page). This has now been resolved.
