### ISSUE TITLE
site is disable

### ISSUE THREAD

**Issue by maxmontgmx** [oqtane/oqtane.framework#3067]
Hi all,

After setting up web site Hosting Model as "Blazor Hybrid", Web Browser displays only "Site Is Disabled"
It it normal?
How can I come back to "Blazor Server" value.

Thanks for your support

**Comment by sbwalker** [comment]
The Blazor Hybrid option indicates that you only want to run the framework as a hybrid app - not as a web app... which is why you are unable to launch it in a web browser. You should be able to run the Oqtane.Maui project in Visual Studio, login to the app and modify the Site Settings if you want to change the Hosting Model to Server or WebAssembly.

**Comment by maxmontgmx** [comment]
I would like to browser web site with MAUI client but I can't (cf issue #3068).
I tried this : static string apiurl = "http://localhost:44357/prod/" to brower sub site but I go to main site url : "http://localhost:44357"

**Comment by sbwalker** [comment]
@maxmontgmx I am not sure how to resolve this specific issue related to the site being disabled. I explained above the reason why your site says it is disabled - it is related to the Hosting Model configuration you set in Site Settings. So I believe this issue is resolved, and #3068 is the issue which needs further investigation.
