### ISSUE TITLE
MAUI client : Unable to browse other web site

### ISSUE THREAD

**Issue by maxmontgmx** [oqtane/oqtane.framework#3068]
Hi all,

I tried MAUI client and it's working with http://localhost:{port}
But when I try my second web site by modifying MauiProgram.cs static string apiurl = "http://localhost:{port}/prod/";
it displays the main web site http://localhost:{port}
How can start application on another site than the main one.
Thanks for your help

**Comment by sbwalker** [comment]
@maxmontgmx when you refer to a "second web site" I am assuming you mean that you used Oqtane's multi-tenant capability to create another Site which is part of your installation (ie. using Site Management in the Admin Dashboard)?

**Comment by sbwalker** [comment]
@maxmontgmx I was able to reproduce this problem... I am investigating further

**Comment by maxmontgmx** [comment]
@sbwalker it's a good news. I hope you will be able to fix this issue easily
It should be nice to override site URL in a config file. With this solution, the site URL wouldnt be hard coded and the MAUI application could be the same for all web sites access.

**Comment by sbwalker** [comment]
@maxmontgmx this ended up being much more difficult than I expected... but it also exposed some other limitations which I was able to address. PR #3086 addresses the following items:

- ability to specify a microsite as an ApiUrl in MauiProgram.cs (ie. "http://localhost:44357/sitename/") - note that the microsite must already exist in the installation.  Note that Blazor Hybrid apps run under an IP of "0.0.0.0" so it is necessary to specify an ApiUrl to provide "context". However it also means that you are bound to a specific context when interacting with the Maui client ie. you cannot switch to another site/tenant while the client app is running.
- scope Installation service to a specific site so that only DLLs and Scripts related to a specific site are downloaded to client
- modified Blazor WebAssembly program.cs to pass Alias to InstallationService
- use SiteKey rather than SiteId in ServerStateManager as SiteId is not unique across different tenants in the same install
- relocate site initialization logic to middleware so that it is not dependent on _host.cshtml

**Comment by sbwalker** [comment]
#3090 provides the ability to create an appsettings.json file in the FileSystem.Current.AppDataDirectory folder (which differs based on environment but is the recommended location to store files on Maui). The format of the file is very simple:

```
{
  "Url": "http://localhost:44357/"
}
```

**Comment by maxmontgmx** [comment]
@sbwalker yesterday, I made a great job by addressing my both requests, congratulations.
but knowing the path where to put appsettings.json is a big challenge as it's composed by GUID.
In my case is : "C:\Users\maxime\AppData\Local\Packages\0E29FC31-1B83-48ED-B6E0-9F3C67B775D4_9zz4h110yvjzm\LocalState"
I'm able to known it by debugging muai app and see the variable value of path.
But without debugger, not so easy.

**Comment by sbwalker** [comment]
@maxmontgmx yes, I had added the appsettings.json feature in a previous version and then removed it because the folder is not intuitive - however it is the only location available to a MAUI app. I will look into adding it's value to the System Info UI.

**Comment by maxmontgmx** [comment]
@sbwalker it's a good idea. Thanks

**Comment by sbwalker** [comment]
@maxmontgmx so there is a bit of a chicken vs. egg problem here... the Maui client needs context in order to load the Blazor Hybrid app (ie. it needs a Url or else it cannot startup). The Url can be specified in the FileSystem.Current.AppDataDirectory folder... however if the user does not know how to find that folder then they cannot specify the Url. So the only realistic place where the FileSystem.Current.AppDataDirectory location could be displayed is somewhere in the Maui client app. But I am not sure if its a good idea to display it in the main user interface.

**Comment by sbwalker** [comment]
@maxmontgmx PR #3095 adds some improvements:

- introduces a MauiConstants.cs file to isolate the client app settings
- includes a UseAppSettings property to indicate if the client app supports overrides via appsettings.json (default is True)
- on startup if UseAppSettings is enabled, creates an appsettings.json file automatically
- during app load validates if the ApiUrl is set (either hardcoded or in appsettings.json) and displays message to user if it is missing (including location of appsettings.json)

This should improve the usability of the Maui client
