### ISSUE TITLE
Sql scripts naming conventions

### ISSUE THREAD

**Issue by chlupac** [oqtane/oqtane.framework#316]
Based on recommendations, because order of sql migration scripts is important, I suggest for dbUp sql scripts this naming convention:

```c#
fileName = $"{TargetDB}.{DateOfCreation:YYYYMMddHHmmss}.{Description}.sql"
```
where TargetDB is "Master" or "Tenant"

https://www.stevefenton.co.uk/2019/02/5-dbup-tips-from-paul-stovell/

**Comment by sbwalker** [comment]
I would prefer to use version numbers for this purpose, as this is the way I have always handled upgrade scripts in the past. So the pattern should be $"{TargetDB}.{Version}.sql". The benefit of this approach is that you can easily identify the scripts which are associated to a release. At this stage we have not started to use upgrade scripts yet because we have not declared an "official" release version yet - so changes have continued to be made to the installation script. Perhaps its time to declare an official "Beta" release and if so, we can start using the upgrade pattern.

**Comment by chlupac** [comment]
Problem is with moduleCreator. On every module build you have to change script name. And if two contributors use same name, here will be merge conflict.

**Comment by chlupac** [comment]
I know than we do not start versioning now, but system must be prepared for it.

**Comment by sbwalker** [comment]
Well the Module Creator is a very different scenario than the Oqtane core framework and I would not want to change the core approach to accomodate the Module Creator. I think the Module Creator needs a variety of enhancements to make it more adaptive to different scenarios

**Comment by sbwalker** [comment]
the original goal of the module creator was for an individual developer to be able to quickly scaffold a functional module so they could more easily learn that patterns and techniques for developing a module.

**Comment by sbwalker** [comment]
"I know than we do not start versioning now, but system must be prepared for it" - agreed, and I am really happy that you added this capability for the master DB scripts :)

**Comment by chlupac** [comment]
Ok, but we should change generated name in creator to conform "Tenant ...." scheme or this script will run first, and it should be problem. I will make PR for it.

**Comment by sbwalker** [comment]
The SQL script that is generated by the Module Creator is not an embedded resource so it should not be picked up by DbUp, correct? Either way, you are correct that the script should be named [Module].Version.sql

**Comment by chlupac** [comment]
But if you want to use it you have to embed it. Or database changes would not be generated to new database. Script should be named Tenant.Version.[ModuleName].sql to be unique and to be loaded in correct order.

**Comment by chlupac** [comment]
But from git view it's hard to maintain core changes with own modifications, I prefer to build extra set of projects in new "Samples" solution folder and generate new module here. And this folder can be easily ignored by git. Because if I want to use generated module seriously and do not want to PR it, only (and relatively difficult) way is create set of projects and move generated code here.

**Comment by sbwalker** [comment]
I think this is a much bigger topic - which is why I told hishamco last weekend that we need to discuss the higher level requirements before we start making changes to the Module Creator. There is the initial creation scenario ( partially covered by current module ), the ongoing development model, the deployment model, etc... Each of these has different needs that need to be addressed.

**Comment by chlupac** [comment]
I agree. Let this topic as is. Maybe it's time for declare Stop for improvements and 
make final polishing for MVP release.
