### ISSUE TITLE
Changing Cookie Name in User Settings

### ISSUE THREAD

**Issue by sbwalker** [oqtane/oqtane.framework#3210]
If you change the default Cookie Name (".AspNetCore.Identity.Application") in User Settings for a Site, you are unable to login using an existing user account.

**Comment by sbwalker** [comment]
Note that if you want to share cookies across subdomains you need to configure the DataProtection API and cookie:

services.AddDataProtection()
  .PersistKeysToFileSystem(GetKeyRingDirInfo())
  .SetApplicationName("example");

services.ConfigureApplicationCookie(options => 
{   
    options.Cookie.Name = "example";
    options.Cookie.Domain = ".example.com";
});

this may be a useful enhancement for User Settings.

**Comment by sbwalker** [comment]
Setting cookie name in ConfigureOqtaneCookieOptions method works fine - the cookie is created with the specified cookie name and users are able to log in. ConfigureOqtaneCookieOptions is a global method which gets its settings from appsettings.json.

Setting cookie name in WithSiteAuthentication does not work. The cookie is created with the specified cookie name but .NET Identity does not recognize the cookie and will not log in the user. WithSiteAuthentication is a multi-tenant options method which gets its settings from the database based on the current site.

**Comment by thabaum** [comment]
@sbwalker While I am cruising around in this area with trying to understand Oqtane CORS and Antiforgery tokens more I read over this again and feels like a relating area. I see how this is relate to providing solutions for multi-tenants and single sign on.  I am geared up now with IDE's and production SSL enabled test sites when ready to discuss this further.

I just want to clear up some confusion I may have if possible.

We should be testing two instances of Oqtane and multi-tenant as this should be able to reach across domains correct?  Maybe not for Oqtane, but in general you could have domain1.com and domain2.com pass this user cookie between the apps running these domains?  Or does this only apply to sub domains with a wildcard SSL certificate or a multiple sub-domain certificate?

**Comment by zyhfish** [comment]
Hi @sbwalker ,
as I analyzed, this is caused by the IdentityAuthenticationStateProvider was not registered in the Server project. I tried to add the code in Server.Startup class and the authentication works with custom cookie name:
![image](https://github.com/oqtane/oqtane.framework/assets/3364448/fd203135-2d1b-461e-a935-7dc8aac29625)

Could you please help to check whether this analyze is in the right way:
https://github.com/zyhfish/oqtane.framework/commit/3948b5218fc47682a3b4abe15759afd95fe5b7f0

I saw this code was added in the Client.Program class, but this will not be called when running the server project, this is confusing me, if this change is in the correct way, we still need to verify below areas:
1. whether it works in multiple tenants with different cookie name defined between them;
2. whether the cookies can be shared between tenants if they have same cookie name. (not sure whether this is in scope, or need to set up the cookie domain name as additional steps)

Thanks,

**Comment by thabaum** [comment]
@sbwalker I can help test some things out over the next week for you and @zyhfish relating to any of these remaining issues if there is a fix proposed.

**Comment by zyhfish** [comment]
Hi @thabaum , here is the proposed fix for this: https://github.com/zyhfish/oqtane.framework/commit/3948b5218fc47682a3b4abe15759afd95fe5b7f0

I verified this works for this scenario, but as this change the authentication provider, it need more tests to make sure it not break anything.

**Comment by sbwalker** [comment]
@zyhfish sorry I missed the earlier message about a potential solution. I will review now.

**Comment by sbwalker** [comment]
@zyhfish in 5.1 I added the IdentityRevalidatingAuthenticationStateProvider to the Server project and declared it in Startup... and since it inherits from AuthenticationStateProvider I think this may have resolved the problem. I need to do some more testing and if you have time, you could do the same.

**Comment by zyhfish** [comment]
Hi @sbwalker ,yes I checked and the issue has been fixed by this change, thx!

**Comment by sbwalker** [comment]
Closing as it has been resolved in 5.1 - thank you @zyhfish for verifying
