### ISSUE TITLE
Bug: Moving a page or renaming the "Url Path" results in 404 error page after saving in Admin/Page/Edit.razor. 

### ISSUE THREAD

**Issue by thabaum** [oqtane/oqtane.framework#3229]
When administrating a page which updates the Url Path the page results in a 404.

This issue happens both when changing the location of the page (parent/child) and when updating the `Url Path` in Modules/Admin/Pages/Edit/razor component while administrating the page from the page itself.

```
if (!string.IsNullOrEmpty(PageState.ReturnUrl))
{
    NavigationManager.NavigateTo(_page.Path);
}                    
else
{
    NavigationManager.NavigateTo(NavigateUrl());
}
```

This final update after refactoring and testing changes the If statement that checks for a `PageState.ReturnUrl` and if it has one after being saved it will use the `_page.Path` for the `NavigateTo()` function.

After full testing both in Admin Page Management and on pages redirecting to the new page path while editing a page from a page works as expected instead of resulting in a 404 error page.

**Comment by sbwalker** [comment]
@thabaum thank you for reporting. Since the routing is based on page paths, this is indeed a problem when a page path changes. There are multiple ways that the Page Edit component can be called in the framework - which is why there is logic for ReturnUrl. I appreciate your efforts with PR #3230 but I don't think it is the correct fix, as it does not take into consideration the different user flows. I will investigate further.

**Comment by sbwalker** [comment]
User Flow 1 - Admin Dashboard - Page Management - click Edit for a page - launches Edit Page  UI - no ReturnUrl
- works fine

User Flow 2 - Control Panel - click Edit for current page - launches Edit Page  UI - passes ReturnUrl
- ReturnUrl contains the page path as well as the querystring (the framework needs to retain this state so that it can restore the user to the exact experience they had previously)
- If a modification is made in Edit Page which changes the path specification:
  - a UrlMapping record is created automatically which is intended to handle the page redirect if the old path is requested
   - when the user is redirected from Edit Page, the ReturnUrl is no longer accurate so it should trigger the 404/redirect logic so that it can be routed to the correct url

**Comment by thabaum** [comment]
This only updates the "Edit" page from returnurl to the updated path.  If the path is not updated it returns to current url.  

I was doing a check if you look at my comits to see if there is a different url in path from current url.... this change is only the page edit component and should not affect any other part of Oqtane.

However after thinking about it if there is a return url present, then that means you are on a page while editing.

It's the only 2 scenarios I know of, editing the page from Page Management and from the Page admin panel itself.

From page management you would not notice a change... it uses the ELSE statement as there is no return url. the logic there `NavigateTo()`

When you are on a page it has a return url so the edit page component is looking for a place to go.  So if you edit the page.Path or not which is saved just before you now get navigated back to that pages path regardless of being updated or not with the solution created.

**Comment by sbwalker** [comment]
#3238 resolves this issue - the logic for creating the UrlMapping was not correct

**Comment by thabaum** [comment]
Gotcha, thanks!  I will review and test.

**Comment by thabaum** [comment]
Tested and works as expected!
