### ISSUE TITLE
Issue: Head Title and Head Content rendering indents and line

### ISSUE THREAD

**Issue by thabaum** [oqtane/oqtane.framework#3232]
The head section resources for `HeadContent` and `Title` elements can use some formatting for indents and line breaks when rendered as source.

I have all but the theme style sheets indenting with new lines as needed in PRs I will link with one by editing the `Head.razor` file and the other is editing the `ThemeBuilder.razor` file I will submit a PR for each to be reviewed.

I was unable to quickly get a solution for the theme.css files to load with indents.  The second+ are not indented, however the first is and the last element might be leaving an extra new line if it is not coming from somewhere else.

Not a big deal since most all apps (like github) you try to read the head source rendered are far worse than Oqtane's current rendering of these head elements.  However for developing and testing out new modules and themes resources loading it is nice to clearly see things load.

**Comment by sbwalker** [comment]
I will not be merging PR #3232 as it will break functionality which parses Head Content. In addition, the formatting of HTML source sent to the browser is an opinionated topic based on individual preference and has no relevance to the framework. Since the UI is fully composable at run-time based on themes and modules which were created by different authors, the HTML source formatting for each page is going to vary significantly.

**Comment by thabaum** [comment]
I had no issues parsing head content with these PR's.  Did you find a way these PR's would cause problems?  Can you share?
