### ISSUE TITLE
The External Login Provider Did Not Provide A Valid Email Address For Your Account. Please Contact Your Administrator For Further Instructions.

### ISSUE THREAD

**Issue by Rodien** [oqtane/oqtane.framework#3325]
I am trying to use the 'External Login Settings,' and everything works except when I get redirected back to oqtane. Upon redirection, I receive the following message: 'The External Login Provider Did Not Provide A Valid Email Address For Your Account. Please Contact Your Administrator For Further Instructions.

Calling the userinfo endpoint via Postman returns the following values: (userinfo-endpoint)

`{
    "name": "admin",
    "sub": "4rt0pmemefh6k1qpmvx7pbftwz",
    "email": "r.bas@dummy.nl",
    "email_verified": true,
    "roles": [
        "Administrator",
        "F M"
    ]
}`

That's a valid email, so I don't get why it's failing. Or is there maybe something I am forgetting in the admin area?

![image](https://github.com/oqtane/oqtane.framework/assets/50739829/be699d15-de48-42f5-b00d-fad80844bc11)

**Comment by sbwalker** [comment]
@Rodien please look in your Event Log - there should be more detailed information related to why the login is failing.

**Comment by Rodien** [comment]
Error detail: 
`Provider Did Not Return An Email Address To Uniquely Identify The User. The Email Claim Specified Was email And Actual Claim Types Are oc:entyp, sub, oi_au_id, azp, nonce, at_hash, oi_tkn_id, aud, exp, iss, iat. Login Denied.`

Here is a dump of the token values. 

`{
  "http://schemas.xmlsoap.org/ws/2005/05/identity/claims/nameidentifier": "4rt0pmemefh6k1qpmvx7pbftwz",
  "http://schemas.xmlsoap.org/ws/2005/05/identity/claims/name": "admin",
  "http://schemas.xmlsoap.org/ws/2005/05/identity/claims/emailaddress": "r.bas@dummy.nl",
  "http://schemas.microsoft.com/ws/2008/06/identity/claims/role": [
    "Administrator",
    "Financieel Medewerker"
  ],
  "Permission": [
    "ManageSettings",
    "AccessAdminPanel",
    "ManageAdminSettings",
    "PublishContent",
    "EditContent",
    "DeleteContent",
    "PreviewContent",
    "CloneContent",
    "AccessContentApi",
    "ListContent",
    "EditContentOwner",
    "ApiViewContent",
    "ViewContentTypes",
    "EditContentTypes",
    "ExecuteGraphQLMutations",
    "ManageUsers",
    "View Users",
    "ManageOwnUserInformation",
    "ListUsers",
    "EditUsers",
    "DeleteUsers",
    "AssignRoleToUsers",
    "Import",
    "Export",
    "ManageRemoteInstances",
    "ManageRemoteClients",
    "ExportRemoteInstances",
    "ManageFeatures",
    "ManageLayers",
    "ManageMediaFolder",
    "ManageMediaProfiles",
    "ViewMediaOptions",
    "ManageMenu",
    "ManageApplications",
    "ManageScopes",
    "ManageClientSettings",
    "ManageServerSettings",
    "ManageValidationSettings",
    "ManageQueries",
    "ManageRoles",
    "SiteOwner",
    "ManageSecurityHeadersSettings",
    "ApplyTheme",
    "ManageCultures"
  ],
  "email": "r.bas@dummy.nl",
  "email_verified": true,
  "oc:entyp": "user",
  "sub": "4rt0pmemefh6k1qpmvx7pbftwz",
  "name": "admin",
  "oi_prst": "CoolBlue_financiele_afdeling",
  "oi_au_id": "9ff252054e45468ab89042edf420c730",
  "client_id": "CoolBlue_financiele_afdeling",
  "oi_tkn_id": "b80a8e2b271241f1a9a88adaf43e48c6",
  "aud": [
    "oct:CoolBlue",
    "oct:Default"
  ],
  "scope": "openid profile roles email",
  "jti": "9ee3d207-65d4-4821-bfca-356e7c9e6168",
  "exp": 1695727139,
  "iss": "https://localhost:7271/CoolBlue",
  "iat": 1695723539
}`

**Comment by sbwalker** [comment]
The log error is telling you the full list of claims which Oqtane is receiving from the IDP based on the configuration specified. This list appears to be different than the list of claims you are receiving when calling the IDP with Postman (which obviously is using its own configuration to access the IDP).  You will have to try to figure out what the difference is in configuration between the 2 methods.

**Comment by sbwalker** [comment]
I have done some more research and found a really helpful article related to this topic:

https://nestenius.se/2023/03/28/missing-openid-connect-claims-in-asp-net-core/

**Comment by Rodien** [comment]
Thanks for the article.

Quick Update:

Oqtane is currently looking inside the TokenId for an email claim, but it cannot find it. The next step should be for Oqtane to call the userinfoEndpoint, but it's not happening.

![image](https://github.com/oqtane/oqtane.framework/assets/50739829/0fef123e-69f3-47dd-9587-a331d0c7b02b)


### From the article: 
If the expected claims are not found in the ID token, then enabling the GetClaimsFromUserInfoEndpoint flag will tell the OIDC handler to make an additional request to this endpoint.

.AddOpenIdConnect(options =>
{
    ...
    options.GetClaimsFromUserInfoEndpoint = true;
	...
}

I added that option inside Oqtane server but I still can not login.

![image](https://github.com/oqtane/oqtane.framework/assets/50739829/88e71745-35e1-4c7f-a875-e4ee9c7dae19)


I am gonna look futher at whats going on. This was just a quick update.

**Comment by sbwalker** [comment]
Oqtane is multi-tenant - so it allows you to define OIDC options for each site in your installation.  So you need to look at Oqtane.Server\Extensions\OqtaneSiteAuthenticationBuilderExtensions.cs to see where the OIDC configuration is being specified. You will notice that it already sets GetClaimsFromUserInfoEndpoint (as well as other properties mentioned in the article):

```
            // site OpenId Connect options
            builder.AddSiteOptions<OpenIdConnectOptions>((options, alias, sitesettings) =>
            {
                if (sitesettings.GetValue("ExternalLogin:ProviderType", "") == AuthenticationProviderTypes.OpenIDConnect)
                {
                    // default options
                    options.SignInScheme = Constants.AuthenticationScheme; // identity cookie
                    options.RequireHttpsMetadata = true;
                    options.SaveTokens = false;
                    options.GetClaimsFromUserInfoEndpoint = true;
```

I feel like the issue you are experiencing has to to with the mappings after the user token has been received. Oqtane already contains the following logic in Oqtane.Server\Extensions\OqtaneServiceCollectionExtensions.cs:

```
       public static IServiceCollection ConfigureOqtaneAuthenticationOptions(this IServiceCollection services, IConfigurationRoot Configuration)
        {
            // prevent remapping of claims
            JwtSecurityTokenHandler.DefaultMapInboundClaims = false;
```

This is supposed to prevent .NET from performing its "default" mapping which changes the names of the claims. However I also see other other references online to these methods:

```
    JwtSecurityTokenHandler.DefaultInboundClaimTypeMap.Clear();
    JwtSecurityTokenHandler.DefaultOutboundClaimTypeMap.Clear();
```

and the article linked above uses:

```
    options.MapInboundClaims = false;
```

So it seems that .NET is a bit of a mess in this area - with lots of conflicting guidance.  However the last portion of the article where it talks about the .NET ClaimsMapper removing claims so that the cookie cannot become not too large also seems to be an area to explore.

**Comment by sbwalker** [comment]
Another good article here:

https://leastprivilege.com/2017/11/15/missing-claims-in-the-asp-net-core-2-openid-connect-handler/

**Comment by sbwalker** [comment]
One suggestion is that we could add an "Enable Logging?" option in User Settings which would log indicate that the framework should log information from additional events such as OnUserInformationReceived and OnSigningIn so that you can see what is happening under the covers in the .NET security infrastructure. By default the Enable Logging? option would be disabled as it would be a performance issue in a production environment. This could be helpful for troubleshooting OIDC integration issues.

**Comment by Rodien** [comment]
FILE: Oqtane.Extensions.OqtaneSiteAuthenticationBuilderExtensions

I placed a breakpoint at 'OnCreatingTicket(OAuthCreatingTicketContext context),' but it's not getting triggered.

'OnCreatingTicket' contains logic for calling the userInfo endpoint.

Currently, the code stops at 'ValidateUser(string email, string id, string claims, HttpContext httpContext, ClaimsPrincipal claimsPrincipal) => // email invalid.


But again the logic for user endpoint nevers gets triggerd.


![image](https://github.com/oqtane/oqtane.framework/assets/50739829/cec274ed-a788-4060-b353-f627cf65084f)

Where can I find the 'UserInfoUrl' setting field?

**Comment by Rodien** [comment]
Wait a minute, I just changed the Provider Type to OAuth 2.0, and it now works.

OpenID Connect provider is not working.

OAuth 2.0 does have logic that calls the userInfo endpoint.

![image](https://github.com/oqtane/oqtane.framework/assets/50739829/071df3db-e985-4219-839b-e184ddd77da6)

**Comment by sbwalker** [comment]
@Rodien I know its confusing but the OnCreatingTicket event is only called by OAuth2 - OnTokenValidated is called by OIDC. Please note that OIDC is essentially built on top of OAuth2 - it simply provides some standards for providers and consumers on how the 3 different endpoints which are part of the OAuth2 flow should interact with one another. 

The difference between the 2 options in Oqtane is that the OIDC option uses the middleware provided by .NET Core - which internally contains handlers, etc... for implementing the OIDC process. OIDC does call the UserInfoEndpoint - you just can't see it because its embedded inside of a .NET Core handler. However, .NET Core also does a lot of other "magic" under the covers in terms of claims mapping, etc... which makes the process more difficult to follow and diagnose.

The OAuth2 option implements the process manually - in a very simplistic manner. This is why you can see the call to the UserInfoEndpoint in the Oqtane code. It is mainly intended for legacy systems which do not implement OIDC. But it can also be used with OIDC providers. It does not do any claims mapping - it only handles obtaining an auth token, and then calling the UserInfoEndpoint and looking for an Email claim - that is it. There is no mapping of any other claims.

**Comment by sbwalker** [comment]
@Rodien I should probably also mention that I am using the OIDC approach in a number of my own production sites and it is working fine. I also know of a many Oqtane users who are using this capability without any issues. So there is something specific about the IDP you are integrating with which seems to be causing issues with the OIDC support in the .NET Auth system.

**Comment by Rodien** [comment]
Oh yes, I find it puzzling because I can see that the ID Token does not contain an ‘email’ claim, but I can’t yet figure out why the userInfo is not being called.

We can probably close this issue.

I will keep looking into this issue for a few more days.

I am using Orchard Core as the IdP, and Orchard is using ‘OpenIDDict.

But I saw videos of it working for other people.

So, yeah, it’s puzzling. I’m going to go back and check the configuration even more carefully

**Comment by Rodien** [comment]
@sbwalker I got it working.

I had to make some configuration changes inside Orchard Core, and I made a change in the 'AddSiteOptions' for the OpenID Connect options inside Oqtane.

So basically, I had to turn on 'Hybrid Flow' in Orchard Core (OpenID server configuration), and I had to turn on 'Hybrid Flow' again at the application level.

### Server Config:
![image](https://github.com/oqtane/oqtane.framework/assets/50739829/ea1d0822-44fc-49f9-a36f-1d4ce93e33a4)

### Application Config:
![image](https://github.com/oqtane/oqtane.framework/assets/50739829/2c6e7b41-a3d2-40f7-aed1-684ae2878d26)


**I changed 'OpenIdConnectResponseType.Code' to 'OpenIdConnectResponseType.CodeIdToken'**

![image](https://github.com/oqtane/oqtane.framework/assets/50739829/7d90231f-4a03-40b5-85fe-6266aac48b94)

**Comment by Rodien** [comment]
I think that there needs to be a field added for 'ResponseType' in the 'External login settings'?

**Comment by sbwalker** [comment]
@Rodien as of OAuth 2.1 there are only two recommended flows:

1. Authorization code flow, - user->server interaction
2. Client credentials flow - server->server interaction

Hybrid Flow includes some aspects of Implicit Flow which was deprecated in OAuth 2.1. So this is why Oqtane sets the ResponseType to OpenIdConnectResponseType.Code (Authorization code flow). However for older IDP servers that are still using the Hybrid Flow it may be necessary to allow Oqtane to set the ResponseType.

**Comment by sbwalker** [comment]
@Rodien I believe this is resolved with the addition of the response types. I will close this issue. Thank you for your assistance.
