### ISSUE TITLE
Module Settings Container setting not saving.

### ISSUE THREAD

**Issue by leigh-pointer** [oqtane/oqtane.framework#3497]
The container settings is not being retrieved and what saved not set.  This can lead to confusion as the message doesn't identify what tab it is erroring.

![ContainerSettingsNotSaving](https://github.com/oqtane/oqtane.framework/assets/9447612/33967054-1921-40be-a5f2-279efa7ee7c4)

**Comment by sbwalker** [comment]
@leigh-pointer are you sure its not related to this item documented previously:

https://github.com/oqtane/oqtane.framework/discussions/2874

**Comment by sbwalker** [comment]
I am not able to reproduce using the Container settings for the default Oqtane theme.

**Comment by leigh-pointer** [comment]
@sbwalker I have done a bit of research, and it comes from changing themes on a page.  
I was viewing my module in RocketFuel Theme and then changed it over view it in Oqtane Theme.  Changing the Theme does not reset the Container in the database [dbo].[page].[DefaultContainerType].  The reason it is not updated, could be because the Container names are the same between the two themes.

I will look further and do a PR for a fix.

**Comment by sbwalker** [comment]
@leigh-pointer This area is actually very complicated as there are many scenarios which need to be considered....

Containers are related to a specific Theme - so when a Theme is changed, the associated Container must be changed as well. 

Themes and Containers are hierarchical/cascading and can be set at the Site, Page, and Module level. 
- Site Default Theme / Container (default for entire Site)
- Page Default Theme / Container (only specified if it is different than the Site default - in which case it overrides - otherwise it should be unspecified)
- Module Container (only specified if it is different than the Page Default Container - in which case it overrides - otherwise it should be unspecified)

Scenario 1: A Page Default Theme is set which overrides the Site Default Theme. Later, the Site Default Theme  is changed.
>> should this reset the Page Default Theme settings for all Pages to inherit the new Site Default Theme? Or should it retain the existing Page Default Theme overrides?

Scenario 2: A Page Default Container is set which overrides the Site Default Container. Later, the Site Default Container  is changed.
>> I believe this should reset any Page Default Container settings for Pages where the previously set Page Default Container matches the new Site Default Container... and any Module Container settings where the previously set Module Container matches the new Site Default Container should be reset as well.

Scenario 3: A Module Container is set which overrides the Page Default Container. Later, the Page Default Container is  changed.
>> I believe this should reset any Module Container settings for the Page where the previously set Container matches the new Page Default Container

Scenario 4: A Module Container is set which overrides the Page Default Container. Later, the Page Default Theme is  changed which requires that the Page Default Container must also be changed.
>> I believe that all Module Container settings for the Page must be reset as they relate to a Theme which is no longer active for the Page.

**Comment by leigh-pointer** [comment]
@sbwalker That as a lot to consider, pff!
I believe Scenario 1 if possible should ask for confirmation. Scenarios 2,3,4 I agree.

**Comment by thabaum** [comment]
@leigh-pointer should this be closed with #3498 as a fix?

**Comment by leigh-pointer** [comment]
@thabaum yes this should be closed.

**Comment by thabaum** [comment]
@sbwalker looks like this should of been closed with fix #3498.
