### ISSUE TITLE
ENH: Start Date and Expiry Date for Module instances and Pages

### ISSUE THREAD

**Issue by leigh-pointer** [oqtane/oqtane.framework#3538]
# Start Date and Expiry Date for Module Instances and Pages in Oqtane

## Overview

The "Start Date and Expiry Date for Module Instances and Pages" feature in Oqtane enhances content management capabilities by providing administrators with control over the visibility and availability of modules and pages. This feature introduces time-based activation and deactivation for precise content scheduling.

### Module Instances Activation

- Administrators can set a "Start Date" for module instances to determine when a specific module becomes active.
- Modules remain inactive until the designated start date is reached, ensuring content is revealed at the intended time.

### Module Instances Deactivation

- "Expiry Date" can be assigned to module instances for automatic deactivation at a specified time.
- Modules seamlessly transition to an inactive state once the expiry date is reached, streamlining content lifecycle management.

### Page Activation and Deactivation

- Pages can be configured with "Start Date" and "Expiry Date" for granular control over visibility.
- A page's "Start Date" activates the entire page, while the "Expiry Date" automates deactivation based on the schedule.

### User Notification

- Oqtane provides notification mechanisms to alert administrators before module or page activation or expiry, facilitating proactive content management.

### Dashboard Control

- Centralized dashboard in the Oqtane administration interface offers an overview of all scheduled start and expiry dates.
- Efficiently manage and monitor content deployment and deactivation for streamlined content governance.

## Benefits

- **Content Strategy:** Facilitates strategic content planning by enabling administrators to schedule activations in advance.
- **Timely Information Delivery:** Ensures timely display of information through automated activation and deactivation.
- **Efficient Content Management:** Reduces manual workload by automating content activation and deactivation.
- **Improved User Experience:** Enhances user experience by presenting relevant and up-to-date content.

**Comment by W6HBR** [comment]
This will be a much needed enhancement!

One thought that that comes to mind on page activation is that you will need to have a mechanism to be able to have a duplicate "Url Path" defined for new pages so that they can replace existing pages.  You currently cannot add multiple pages with the same Url Path (for obvious reasons).

**Comment by leigh-pointer** [comment]
@W6HBR 
> duplicate "Url Path" 
 As far as i see it, a page will be either active or inactive (visible of invisible) 

How are you seeing this functioning?

**Comment by W6HBR** [comment]
@leigh-pointer 
Yes, I agree it would be either active or inactive.  However, the current validations when creating a page will not allow you to enter a duplicate Url Path value.  You will need to be able to schedule complete replacement pages for existing pages using the same Url Path.

**Comment by leigh-pointer** [comment]
@W6HBR  
Only one page will be needed. That page would either be 
- Visible Functions as it does now.
- visible until an expiration date.
- visible on a Activation date.
-  visible on a Activation date until until an expiration date.

So as you can see only one page and route would be needed. There was a similar functionality introduced in DNN version 2.1.9 I believe.

The modules will have the same functionality.

**Comment by W6HBR** [comment]
@leigh-pointer 
I think you're missing my point.  For complex page changes that may be using a new theme and many different content modules, it would make sense to completely develop the new page and then activate it at the specified time.  This will require some type of mechanism to re-assign the existing page route to the new page while deactivating the route from the old page.

**Comment by leigh-pointer** [comment]
@W6HBR I do understand but this ENH is going to follow the same pattern as the Roles.  For the functionality you are suggesting we should create another Issue.

**Comment by sbwalker** [comment]
@W6HBR what you are referring to is "content versioning" - which will not be implemented in the Oqtane framework.

**Comment by sbwalker** [comment]
@leigh-pointer I merged PR #3602 but I think it will need some fairly substantial testing to ensure it functions properly in all scenarios. I was hesitant to add this functionality to the framework, primarily because it is not a mainline use case - but it imposes a processing tax on every page request regardless of whether the feature is being used or not (ie. it needs to evaluate additional conditional permission logic for every request). So this is ultimately a tradeoff between functionality and framework performance - and the feature has been requested enough times that it seems to be worth the tradeoff.

In regards to the other items identified in this PR... I would prefer to NOT include notifications or a content scheduling capability in the framework itself. These should be implemented as third party modules so that the the core framework remains lean and optimized. PR #3602 is focused on the foundational building blocks to allow for more advanced solutions to be created.

**Comment by leigh-pointer** [comment]
@sbwalker 
> I think it will need some fairly substantial testing to ensure it functions properly in all scenarios.

I am going to continue with this.

> These should be implemented as third party modules so that the the core framework remains lean and optimized. PR https://github.com/oqtane/oqtane.framework/pull/3602 is focused on the foundational building blocks to allow for more advanced solutions to be created by third party developers.

I Agree
