### ISSUE TITLE
User Profile - After "Save" action user redirects to homepage.

### ISSUE THREAD

**Issue by thabaum** [oqtane/oqtane.framework#3561]
When a user saves their profile they get redirected to the homepage instead of staying on the user profile page and tab they are currently on with a status message confirming  that this has been saved.  

Expected behavior is a notification success message staying on page and tab.

__

Looks like this logic has been updated relating so I am going to say this is by design and not an issue.

However would it be better to use `NavigationManager.NavigateTo(PageState.ReturnUrl);` instead of `NavigationManager.NavigateTo(WebUtility.UrlDecode(PageState.QueryString["returnurl"]));` or does it matter?  We used this in a previous commit to return a user and looks more simplified.  I have tested both and seem to get similar results.  I can create a PR if `NavigationManager.NavigateTo(PageState.ReturnUrl);` is preferred.

Also would it be good idea to put a status message that maybe shows up for 3-5 seconds when page navigates to the return url displayed over the theme z to let a user know it was successful?  Or a toast or popup message that says saving was successful and when you click close it navigates a user to the return url.

Other than that after further review it looks like this can be closed.  This ended up being more of a discussion than an issue.  I am just interested in hearing about the use of the navigation manager.

**Comment by sbwalker** [comment]
@thabaum as you noted, this change was made so that regardless of where you are located within an Oqtane site, if you navigate to the User Profile to update some information, when you Save you will be automatically redirected back to the location where you originated (including any querystring state parameters which may have been present at that time). This should provide a better user experience as previously you would not be redirected and would need to use the browser back button to try to get back to your prior location. This new behavior is now consistent with the behavior of Login / Register. The reason you were redirected back to the Home page is because that is where you were located when you decided to navigate to your User Profile. 

One possible option is that the Save option could display a "User Profile Saved" message and the user would need to click the Close button to be redirected to their previous location. This behavior would not be obvious so the message would probably need to explicitly indicate "Click Close to return to your previous site location". However the main question is why a user would need this "Save" confirmation message... any error or validation issue will display a message and prevent Save from occurring - the only time a user will be redirected is when the Save was successful - and if that is the case then why do they need to see a "Saved" message as it is somewhat redundant.

You comment about using NavigationManager.NavigateTo(PageState.ReturnUrl) is valid... the one scenario which would need to be verified in making this change is the new behavior where a user logs in via OAuth2 and does not have an email and is redirected to the User Profile page automatically - we would need to verify that the ReturnUrl property is hydrated in this scenario since it is not the typical flow.

**Comment by thabaum** [comment]
I do not have any OAuth2 instances setup to test this scenario described currently.

Couple notes: 

1. If a user navigates from a 404 page they will be navigated back to the 404 page which could be confusing.  

2. To stay on the profile page use the URL `domain.com/profile` removing the return URL from the path to get the legacy behavior.   

Some other feedback:
It is nice to sometimes want to stay on the profile area to review your changes after the save.  I was having to go back after each save to see how it looked or it it was saved at all.  A popup giving an option buttons to stay on the profile page or navigate back to previous page or go to home page after saving would make it worth along with a don't ask again checkbox.   That would make the popup more useful but maybe a bit much adding something extra for the user to engage.  A toast UI control would be the other option but still not necessary.

I like the idea of staying in profile after saving check box next to save button that lets the app know if the user wants to stay in the profile area.  Kind of like a profile "edit" mode that leaves you in the profile until you close profile edit mode and save which then redirects to the page you came from or by navigating away from the profile page.  But it is not necessary.

Smoothing out the current behavior should be good enough.

I also thought maybe there should be a splash page or redirect page you can set in site settings for where to redirect when needing to redirect but no redirect url has been provided to know where to redirect or navigate to.  A user page, site page, homepage.  A some sort of default redirect url option potentially set in site settings.
