### ISSUE TITLE
Issue:  Register page should resolve to 404 page if Registration is not enabled.

### ISSUE THREAD

**Issue by thabaum** [oqtane/oqtane.framework#3578]
### Issue:  Register page should resolve to 404 page if Registration is not enabled

http://localhost:44357/register should act the same as http://localhost:44357/join, http://localhost:44357/account, http://localhost:44357/wp, http://localhost:44357/wp-admin, http://localhost:44357/admin unless enabled or user is authenticated with rights to edit this page.  In other words they should all go to login even if the page does not exist or is not enabled.  After logging in the user gets forwarded to a 404 if does not exist or goes to the page that does. The other most secure option I believe is to show a 404 for all these page URLs examples shown in a fresh instance of Oqtane installation (registration disabled).  The options would be send all to 404 or all to login then 404 if dont exist when needing to login.  A site setting for use case preference is preferred as I can see lax vs hardened approaches to applications.  Expose as little as possible and if your an admin you should know to go to login first.

I was reviewing these behaviors to see how they should most securely react depending on settings and configurations.

Reason for all those above example urls to go to the same page is to not expose login systems if you want to for example change the name of the login page to something else and not have any links to it so it is not discoverable as easy.  Really in this case you would want all other URLS above to go to 404 pages. Currently you see the Register page, and Admin forwards to Login, the others are 404 redirects.  If I had register disabled I would want to be sure some bot does not index this page if possible.  In the most secure scenarios you would potentially want site pages to look as static as possible with no back end - ftp old school.

At the same time all of these urls that don't exist can go to a login page instead of 404 so that if you type admin or account it does the same thing as anything else that may or may not exist.

Site Settings may need enhanced to allow different approaches for the more friendly to a more hardened application philosophy.

I can also see this issue being closed as is there is no bug or problem other than a preferences that I feel the behavior described could be improved for security reasons.  I am trying to be as flexible all directions I could with solutions for ideas to take into perspective.

But again to resolve this to me would be to see the Registration and Admin pages resolve to 404 in a default instance of Oqtane installation. Or all pages go to login if they don't exist to match behavior and not give away page structure an administrator may want to not be as transparent about.  Not sure if this is going to make it on the issue list but felt worth a try.

**Comment by sbwalker** [comment]
So to summarize... if the site does not support Registration... and a user tries to browse to the "/register" Url path (by manually entering the Url into the their browser address bar, as there would be no link for them to click on the page)... and they are not logged in... they will see the following:

![image](https://github.com/oqtane/oqtane.framework/assets/4840590/e1b73ce0-524a-470f-8212-a08b94037c70)

And you are saying that under these circumstances, the framework should display the 404 page instead:

![image](https://github.com/oqtane/oqtane.framework/assets/4840590/541fbed9-8416-4207-bc8c-a751cf7a0e90)

it is not clear what benefit this provides. My suggestion is that if you want the behavior you describe then delete the Register page from your installation. Then requests to it will result in a 404 because the page does not exist.
