### ISSUE TITLE
Npgsql.PostgresException (0x80004005): 42P01: relation "ABCAbcJob" does not exist

### ISSUE THREAD

**Issue by timdinh** [oqtane/oqtane.framework#3648]
So i created a new module from the module management page with the following values
Owner: ABC
Module Name: AbcJob

I compiled the module and restart oqtance.

I than proceed to add **AbcJob** module to my home page

Once added, there is a button called **Add AbcJob**, i clicked on it and put in a job name of _zzz_ and press **Save** button

Recevied the exception `Npgsql.PostgresException (0x80004005): 42P01: relation "ABCAbcJob" does not exist`

Upon checking the database, it created a table called `abc_abc_job`

It appeared that there is a mismatched of table name between `ABCAbcJob` and `abc_abc_job`

I can't seem to find where it define a table name of `abc_abc_job` anywhere in the code. 

Anyone as any ideas?

**Comment by timdinh** [comment]
Found this code from `PostgreSQLDatabase.cs`
```
public override DbContextOptionsBuilder UseDatabase(DbContextOptionsBuilder optionsBuilder, string connectionString)
{
    return optionsBuilder.UseNpgsql(connectionString)
                .UseSnakeCaseNamingConvention()
                .ReplaceService<IHistoryRepository, OqtaneHistoryRepository>();
}
```

I guess the line `.UseSnakeCaseNamingConvention()` convert the table name to `abc_abc_job` instead of `ABCAbcJob`

**Comment by timdinh** [comment]
Managed to fix by performing the followings

In `AbcJobContext`, add
```
    protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
    {
        optionsBuilder.UseSnakeCaseNamingConvention();
        base.OnConfiguring(optionsBuilder);
    }
```

Add this to the `.csproj` file
```
<PackageReference Include="EFCore.NamingConventions" Version="8.0.0-rc.2" />
```

In `SeavaJobEntityBuilder`, replace
```
private const string _entityTableName = "ABCAbcJob";
```
with 
```
private const string _entityTableName = "abc_abc_job";
```

In `AbcJob`, replace
```
[Table("ABCAbcJob")]
```
with
```
[Table("abc_abc_job")]
```

**Comment by thabaum** [comment]
welcome @timdinh, would you be willing to create a pull request for this?

The community loves any contributions provided to the Oqtane Framework project source.  

@sbwalker will get back with you soon as he has the time.  

I am glad you found a solution to your issue.

If you are not up for putting together a pull request I am willing to do this and be willing review and test it as well.  Otherwise put a PR together and link it with Fixes #3648.  These changes look like they will be merged if this fixes your issue as PostgreSQL common convention is snake_case with all lowercase characters and an underscore to separate the words.

Cheers!

**Comment by lthoa** [comment]
@timdinh,
All of Oqtane's original modules work well with PostgreSQL, only customized modules have the above error with PostgreSQL.
I also discovered this error and haven't found a fix yet.

**Comment by lthoa** [comment]
I found this error, just remove the [Table("ABCAbcJob")] attribute. Let Entity Framework automatically handle table names.

**Comment by sbwalker** [comment]
@lthoa Currently the default module template scaffolds the Model class using:

[Table("[Owner][Module]")]

It does this to try to prevent a database table naming collision with an existing table. The generated Model code using the above example would be:

[Table("ABCAbcJob")]

When using PostgreSQL, the EntityBuilder is executed and creates the table in the database using snake case:

abc_abc_job

Your suggestion of removing [Table("[Owner][Module]")] from the module template would solve the problem. However it would also mean that the table would be created in the database without the Owner prefix:

abc_job

Since this change would apply to all modules generated with the Module Creator, regardless of which database platform the modules are intended to run on, it means that it would increase the potential that a database table naming collision could happen.

Perhaps this is not a real concern - in which case the suggestion to remove [Table("[Owner][Module]")] from the module template is a viable solution.

Note: that the reason why the core framework does not suffer from this issue is because it does not use [Table] attributes in its models.

**Comment by zyhfish** [comment]
maybe we can add below code in the DBContext class:
![image](https://github.com/oqtane/oqtane.framework/assets/3364448/214554f8-a97f-4797-8458-9b58d18bad72)

in this case we can have a custom method to define the table name, and replace it in the template to keep it same in all the places.

**Comment by zyhfish** [comment]
maybe we can implement the OnModelCreating method in the DbContext class with the table name as a token. then we can replace the table name in templates with all the same value.
![image](https://github.com/oqtane/oqtane.framework/assets/3364448/345a4a71-86bc-425a-a630-ff0471a21583)

we also need to find out the way to get the correct table name between different database providers.

**Comment by sbwalker** [comment]
@zyhfish the goal is that modules should not contain any database-specific logic - you should be able to create a module and have it function properly on any of the 4 supported database platforms. This includes both provisioning the schema as well as run-time execution. So we would want to avoid any database specific logic in the Module Creator. Your suggestion about OnModelCreating may be a good path to explore - there are already methods in the database provider abstractions to deal with differences in behavior ie. RewriteName in the PostgreSQL provider converts object names to snakecase format.

**Comment by zyhfish** [comment]
thanks @sbwalker , I submitted a PR to call to the RewriteName method to correct the table name in the template file:
`builder.Entity<Models.[Module]>().ToTable(ActiveDatabase.RewriteName("[Owner][Module]"));`

**Comment by sbwalker** [comment]
thank you @zyhfish I will test it now. Just to confirm, with this modification the Model attribute will be retained and will still include the Owner as well as Module names?

**Comment by sbwalker** [comment]
@zyhfish I validated that the PR you submitted resolves this problem - thank you!
