### ISSUE TITLE
Bug: Theme and Module Creator Template Visual Studio Project Build Error.

### ISSUE THREAD

**Issue by thabaum** [oqtane/oqtane.framework#3781]
5.0.3

Theme Creator Template Visual Studio Project Results In ModuleInstance.AddModuleMessage object reference build error in ContainerSettings.razor.

```
        catch (Exception ex)
        {
            ModuleInstance.AddModuleMessage(ex.Message, MessageType.Error);
        }
```

![image](https://github.com/oqtane/oqtane.framework/assets/13577556/f4445b7b-5650-439f-9fce-909f26b8174b)

Comment out `// ModuleInstance.AddModuleMessage(ex.Message, MessageType.Error);` as a quick workaround.

**Comment by sbwalker** [comment]
@thabaum please test #3787 - the expected behavior is that the module or theme code should compile - however it will provide compilation warnings that ModuleInstance methods are deprecated. And at runtime if a module or theme references the ModuleInstance methods, the code will not throw an exception however it will also not display a message, etc... This is because component references are not serializable and cannot be passed across render mode boundaries - so the solution is to use the equivalent methods in ModuleBase.
