### ISSUE TITLE
Obsolete code

### ISSUE THREAD

**Issue by chlupac** [oqtane/oqtane.framework#388]
I think than folders 
Oqtane.Server/Modules/HtmlText
Oqtane.Client/Modules/Counter
Oqtane.Client/Modules/Weather

should be safely deleted.

Not sure about 
Oqtane.Client/wwwroot

**Comment by sbwalker** [comment]
Oqtane.Client/Modules/Counter and Oqtane.Client/Modules/Weather are sample modules which were part of the original Blazor Server app template and serve no real purpose. They can be deleted.

Oqtane.Client/Modules/HtmlText needs to be retained in order to allow user to add content to pages - plus it is a functional example of an in-line module which people can explore. The backend of the HtmlText module is in the Oqtane.Server/Modules/HtmlText folder - it contains the controller, repository, etc... it also contains the implementation of the IModule interface which is used when creating the default site template. It cannot be deleted ( and neither can the Oqtane.Shared/Modules/HtmlText folder as it contains the model ).

Oqtane.Client/wwwroot was a requirement for Blazor WebAssembly... but after the recent changes to support both client and server using the _Host.cshtml I am not sure if the static assets need to be in the Client project. You would need to test this by running Oqtane on WebAssembly and removing the Oqtane.Client/wwwroot folder to see what happens.

**Comment by chlupac** [comment]
Oqtane.Server/Modules/HtmlText

**Comment by hishamco** [comment]
> Oqtane.Client/wwwroot was a requirement for Blazor WebAssembly... but after the recent changes to support both client and server using the _Host.cshtml I am not sure if the static assets need to be in the Client project. You would need to test this by running Oqtane on WebAssembly and removing the Oqtane.Client/wwwroot folder to see what happens.

I will try to have a look ...

**Comment by hishamco** [comment]
Should be closed after merge #398

**Comment by chlupac** [comment]
Thanks
