### ISSUE TITLE
User Permissions not saving when unchecked.

### ISSUE THREAD

**Issue by leigh-pointer** [oqtane/oqtane.framework#3893]
After setting a user permission if it be system or custom the permission can not be unset and saved. 

![UserPermissions](https://github.com/oqtane/oqtane.framework/assets/9447612/485bb451-c500-4e95-8a87-d409bba7a8ff)

**Comment by nicpitsch** [comment]
I can't confirm this issue. The user permissions are persisted. Environment:

- Oqtane dev branch, latest commit.
- Render Mode: Static Server Rendering.

**Comment by sbwalker** [comment]
I cannot reproduce this issue either using the latest code in development

**Comment by sbwalker** [comment]
@leigh-pointer since multiple people are unable to reproduce this issue, can you please try to reproduce it in your environment in a module which does not have custom extended permissions - just the default View/Edit permissions. I would like to narrow down if the issue is related to  custom extended permissions.

**Comment by leigh-pointer** [comment]
@sbwalker its working fine in a normal case. Stupidly i didn't say that the permissions are being set when the module is on a user personalized page.

**Comment by thabaum** [comment]
The User permission group this issue is related to works OK with the HTML module as everyone has said I can confirm as well.

I will add some custom permissions to the HTML module to try to replicate tomorrow if not resolved by then.

On another group permission relating note:

I am trying to figure out the difference between the red X and unchecked box.  If you save it with a red X and go back to view it later it is an unchecked box and not a red X.  Below shows what you can save and see the results.

![image](https://github.com/oqtane/oqtane.framework/assets/13577556/c150f946-32d6-409d-ad56-157b5c1487a0)

The issue described above as you can see only happens in the Role permissions group. 

Would this be another issue we need to log in the same area? I just noticed adding a red X to the by User group permissions saves as a red X when you revisit permissions.  This is not the case in the by Role group permission group.  The permission groups should have the same behavior shouldn't they?

I am testing using static SSR.

**Comment by sbwalker** [comment]
@thabaum the red 'X' indicates a Deny permission. It means that the role is denied access to the permission. Deny permissions are evaluated first in permission verification and will override other grant permissions. You did not include the role names in your screen shot, but there is validation logic in the permission grid to prevent specific roles from being denied. In your case I am guessing you tried to deny Registered Users - which is not valid because every user in a site has the Registered Users role. You can look at the Permission Grid validation method if you want to understand this better.

**Comment by thabaum** [comment]
@sbwalker thanks for clarification as I wanted to be sure, this was a Role permissions, not User so this is not an issue as it sounds like it is by design other than maybe not allowing the X option so it removes any user confusion like I had.

![image](https://github.com/oqtane/oqtane.framework/assets/13577556/94a80fe7-3b15-4987-9e96-db76da48b65c)

All of these save as unchecked boxes.

![image](https://github.com/oqtane/oqtane.framework/assets/13577556/4d10b1b3-e634-46dd-9a1a-b553e3355c90)

While the User roles will actually allow the "Deny" permission.  Suppose some Oqtane.Docs documentation on permissions for both administration and development could help.

**Comment by thabaum** [comment]
@leigh-pointer hello, looks like issue is still looming here.

So to be clear to reproduce this issue:
1. Create a custom module with custom permissions added to it.
2. Add the module on a page that can be personalized ("My Page").
3. Add the custom permission setting a user set to "allow" (green checkbox) and save changes.
4. Revisit permissions page of the custom module and unset the user custom permission (empty checkbox) previously set in last step, then save changes.
5. The result is after revisiting, the module permissions remain set to the "allow" permission (green checkbox) is still set to allowing permissions for the custom user permission setting.

Few questions:
- One question is does this issue still happen with "deny" permission ( red X ) is set for the user custom permission?
- My next question is which version are you testing this on, 5.1.0 or 5.0.2?  Or does it happen in both?
- Do you see anything in the browser F12 logs OR in the console of Visual Studio when you click save that may be some sort of an error or different then when you set the setting in step 3?
- Last, I want work with permissions on a fresh custom module to see if I can reproduce this.  Any further information that can help me do this so I can create a simple reproduction of it similar to what you have?

Thank you.

**Comment by thabaum** [comment]
@StudioElf.DynamicForm beta version I cannot access the settings page in 5.1 for your dynamic forms module

![image](https://github.com/oqtane/oqtane.framework/assets/13577556/1ea9d5f7-4704-4317-94f4-260108cf2dcc)

Interactive Mode:

![image](https://github.com/oqtane/oqtane.framework/assets/13577556/c8e81dd1-ee40-4a67-b09b-d95267bd1365)

And in static mode it is blank when accessing.

In fact I pretty much downloaded all modules from the marketplace almost and can't find one with a custom permission.

2sic module is glitching as well, but I don't know if it from 5.1 or what as I figured I would test everyones modules out I could and report any issues to help out with limiting migration issues.

I am not using your paid version so maybe it works better.

From what I can tell so far just those two modules really are not functioning currently in 5.1

I get all kinds of bugs trying to use your beta version 1.0.3.1 on 5.1:

![image](https://github.com/oqtane/oqtane.framework/assets/13577556/ae39bb0e-8031-4154-863c-52667366d4b7)

I also just tried with 5.0.2 and resulted in a similar errors:

`An Unexpected Error Has Occurred In StudioElf.DynamicForm, StudioElf.DynamicForm.Client.Oqtane: Could not load type 'Oqtane.Models.PermissionString' from assembly 'Oqtane.Shared, Version=5.0.2.0, Culture=neutral, PublicKeyToken=null'.`

![image](https://github.com/oqtane/oqtane.framework/assets/13577556/bce41e08-6f5b-4205-a9a0-96cac8defdb6)

**Comment by leigh-pointer** [comment]
@thabaum I would expect this as 1.0.3.1 is a very old beta and should have been set in inactive (which it is now, so thank you). DynamicForm 1.0.8.5 Beta is only compatible with 4.0.5-4.0.6 and this is set in the Market place.  As far a the commercial product goes, I will look in to it with the source from Git version 5.1.0.

**Comment by leigh-pointer** [comment]
Using Dev-5.1.0
Persmission grid works with custom Permission on the Main Role grid and on the User Permissions grid.

Solution Used
[ModulePermissions.zip](https://github.com/oqtane/oqtane.framework/files/14460980/ModulePermissions.zip)

**Comment by sbwalker** [comment]
@leigh-pointer I don't really understand your post above... are you saying that there is no problem and this issue should be closed? And if so, what is the purpose of the ZIP file you uploaded?

**Comment by leigh-pointer** [comment]
Issue is not happening in 5.1.0.
