### ISSUE TITLE
Bug: html content is empty when edit in a child site

### ISSUE THREAD

**Issue by zyhfish** [oqtane/oqtane.framework#4017]
Reproduce Steps
1. fresh install the instance with default settings;
2. create a new child site in site management, with the domain set to {domain}/child;
3. browse to the child site home page, click the edit button.
4. click the edit button for any html module, you will open the edit content popup.

Expected Result
the html content should display in the editor.

Actually Result
both the rich-text editor and raw editor are empty.
![image](https://github.com/oqtane/oqtane.framework/assets/3364448/253be473-20d0-4971-a4c2-96f05846f64e)

**Comment by sbwalker** [comment]
This one is a complicated issue... 

When running on the Server, the component initially makes a call to the HtmlTextService to get the most recent HtmlText object based on the ModuleId. This works fine and returns the correct record. 

Then Blazor makes another call to the HtmlTextService, and this time the SiteState.Alias is null - so it tries to resolve the correct Alias for the HttpContext, however the HttpContext is:

GET http://localhost:44357/_blazor HTTP/1.1 101 Switching Protocols

And because it is missing the "child" alias path it resolves the Alias to the root domain. And since ModuleId does not belong to the root domain SiteId, it returns an HtmlText object of null. Which is why the RichTextEditor displays no content.

I believe the problem is that the second call to the HtmlTextService is transitioning render mode boundaries - ie. from Static to Interactive, as the Edit.razor component is an Interactive component. For some reason the SiteState is not being passed across the render mode boundary - which means the "context" is lost.

Note that this is not a problem when using the API approach for data access because the Controller always has the correct Url with the child alias path embedded in it, so it can resolve the Alias correctly. It is also not a problem for root domains because the GET request for _blazor includes the full domain name which can be resolved to an Alias. 

So this is only an issue for child sites. And it only became an issue after the "dual" service HtmlTextService was added, because previously all data access occurred through the API Controller.

**Comment by thabaum** [comment]
@sbwalker what I notice is the extra `/` as well.

![image](https://github.com/oqtane/oqtane.framework/assets/13577556/b01881f2-6505-4430-bb0f-afea0bf7f23e)

![image](https://github.com/oqtane/oqtane.framework/assets/13577556/33d3755c-95b8-49c8-b09a-0fe3ca3b6e38)

I forced the edit component into static and the raw data did exist although the rich editor was broken along with interactivity.  So there is definitely an issue with crossing render mode boundaries.

**Comment by sbwalker** [comment]
#4019 fixes the issue. The problem is that there were actually 2 SiteState services registered in the framework - one was defined in the Shared project, and one was defined in the Server project (Infrastructure namespace). The reason why there were 2 is because there were some properties on the SiteState class which were only applicable to Client projects - and these were included in the Shared version of the class. However now that Blazor is statically rendered server-side, it blurs the lines between client and server components - so it makes sense to only have a single SiteState service. So the fix was to remove the SiteState class from Server/Infrastructure - which allows the framework to marshal the SiteState values properly across the render mode boundary.

**Comment by sbwalker** [comment]
@thabaum I think you are identifying a different issue - not related to the issue which @zyhfish reported. The Url issue is most likely related to the refactoring of NavigateUrl(). It should be logged separately but I will investigate further.

**Comment by thabaum** [comment]
@sbwalker Nice to see this was resolved and not as huge of an issue as first thought.  I made the modifications to source and tested working as expected.

I will report the new issue found as I was wondering if it was an issue worth reporting while reviewing this, thank you.
