### ISSUE TITLE
Favicon is not set properly

### ISSUE THREAD

**Issue by ajahangard** [oqtane/oqtane.framework#4061]
When the favicon is selected for a site it is shown but the html tag generated is not correct and the type attribute is corrupted.
for example the tag is something like this:
```
<link id="app-favicon" rel="shortcut icon" type="image//files/id/1" href="/files/id/1">
```

this is because the favicon type is extracted from favicon URL but the URL does not have extension (ThemeBuilder.razor line:42).

**Comment by sbwalker** [comment]
- rel="shortcut icon" is no longer considered valid HTML - it should be rel="icon"
- type does not need to be specified on the element because the file server is including the mimetype header

**Comment by thabaum** [comment]
@ajahangard Hello, thank you for reporting this.  I see a couple issues and I am actively working on this now to see what I can do to help this area of Oqtane.

1.  if you select `ico` file it would change to `image/ico and not remain `x-icon`
2. if you select `svg` file it would change to `image/svg` instead of `image/svg+xml`
3. It does not look like it is finding a default file in the document root.  Sometimes you can just put a favicon.ico file in the doc root folder and expect this to be the "default" icon and maybe can be selected automatically in a new site that use the default site template? 
4. `rel=\"shortcut-icon\"` should be `rel=\"icon\"`
5. Last thing is the file name in the image you are showing.

```

        // favicon
        var favicon = "favicon.ico";
        var favicontype = "x-icon";
        if (PageState.Site.FaviconFileId != null)
        {
            favicon = Utilities.FileUrl(PageState.Alias, PageState.Site.FaviconFileId.Value);
			// Extract file extension
			var fileExtension = favicon.Substring(favicon.LastIndexOf(".") + 1).ToLower();

			// Check if the file extension is not "ico"
			if (fileExtension != "ico")
			{
				// Set favicontype based on file extension
				if (fileExtension == "svg")
				{
					favicontype = "svg+xml";
				}
				else
				{
					favicontype = fileExtension;
				}
			}
        }
        headcontent += $"<link id=\"app-favicon\" rel=\"icon\" type=\"image/{favicontype}\" href=\"{favicon}\" />\n";
```

This would resolve the file type and rel attribute issues.

@sbwalker should I log these issues and submit a PR for these with this solution?

**Comment by sbwalker** [comment]
@thabaum handled in #4063
