### ISSUE TITLE
[BUG] Unsaved content is lost when inserting an image in HtmlText/RichTextEditor

### ISSUE THREAD

**Issue by mdmontesinos** [oqtane/oqtane.framework#4108]
### Oqtane Info

Version - 5.1.0
Render Mode - Static 
Interactivity - Server
Database - SQL Server

### Describe the bug

The updated content of the HtmlText/RichTextEditor is lost if not saved before trying to insert an image.

[htmlTextBug.webm](https://github.com/oqtane/oqtane.framework/assets/90258222/08dd8311-b9a1-4717-ac69-8b5e854d44cb)

### Expected Behavior

The content shouldn't be lost when inserting an image, which is the typical use case for this type of modules.

### Steps To Reproduce

In a fresh Oqtane install, try to edit the default HtmlText modules include and see whether the updated content is lost or not.

### Anything else?

I believe the StateHasChanged used in the InsertRichImage method of the RichTextEditor is causing the updated content to be lost, as it is not yet synchonized with the _richhtml variable and the OnAfterRenderAsync overrides it with 
```c# 
await interop.LoadEditorContent(_editorElement, _richhtml); 
```

**Comment by sbwalker** [comment]
I believe this was caused by the fix in #3641 which was introduced because the rich text editor was not being refreshed when the Content parameter value passed by the consumer was changed. But the fix seems to have side effects - which will require more investigation. Perhaps the fact that Synchonization support was removed from the editor will make it easier to resolve now (as synchronization caused all sorts of strange problems).
