### ISSUE TITLE
[BUG] My Page - Personalizable Page - Users Can Add Modules From Existing Pages With Permissions

### ISSUE THREAD

**Issue by thabaum** [oqtane/oqtane.framework#4150]
### Oqtane Info

Version - 5.1.0+
Render Mode - Static 
Interactivity - Server
Database - SQL Server

### Describe the bug

Users Can Add Modules From Existing Pages With Permissions.

### Expected Behavior

Only allow components to be listed to be included in the page that are flagged as Personalizable.

Not allow them to see modules from pages that are not "personalizable" to avoid issues.

If allowing users to add other modules, make a way to flag them as personalizable and only display pages to select from that have modules included that are flagged as personalizable.

### Steps To Reproduce

1. Log in as a regular user
2. Navigate to My Page
3. Click the edit pencil if the gear icon does not appear.
4. Click the gear to open the page control panel.
5. Select 'Add Existing Module`
6. notice the drop-down list how you can select modules such as the login and registration module.  If you select the login module, you cannot remove it since it will redirect you to homepage after selecting my page.

### Anything else?

Probably need to log another issue for the "Edit" button in the Control Panel does nothing.  It should send the user to the page in the edit mode to allow a user to move things around or not be rendered in the UI since a user cannot edit those page settings.  Currently it does nothing (inactive) which is probably correct, unless we can add some personalizable options to the page editor allowing users to update things like the title of the page when visiting it.  Not sure anyone would want this but maybe it is supposed to allow this?

Not sure if the "Admin Pane" is something to allow or is named properly. I am using theme creator theme so maybe this is just the name of it and can be renamed.

Option to delete the page creates a new fresh page... maybe normal.

I believe I only had a pencil to edit the page before, but once I click pencil I was getting the page control panel icon so I began testing this area.

Add the secure content to the page as an existing module from the Private page and you cannot edit the module settings like move it around the page or anything.  Or delete it... without deleting the page to a 404 not found and having Oqtane Framework rebuild the page when revisiting (refreshing) that page.

Add the login page login module and you cannot delete the page to start over for that user, and the page is pretty much broken going forward.

A few issues in one but I can break this up if needed.

### Screenshots

First Visit:
![image](https://github.com/oqtane/oqtane.framework/assets/13577556/7d5b94fc-f252-4761-9ad7-63f76b956e84)

Should this show just the pencil to edit the page OR should it show the Control Panel Option as well?  I experienced just the "Edit" pencil until I clicked on it, then the page control panel icon appears as shown below I figure once the personalized page is created by the framework for the user which maybe normal:
![image](https://github.com/oqtane/oqtane.framework/assets/13577556/49785aa5-d990-416d-a231-e4831a7c5d34)

List of pages a normal registered user can select modules from:
![image](https://github.com/oqtane/oqtane.framework/assets/13577556/99855d72-bbe1-43c7-9faf-f6e3ace31ea2)
Examples of modules to select:
![image](https://github.com/oqtane/oqtane.framework/assets/13577556/7e6ae9b4-573f-4e7a-a9e7-26bc9e905eb8)

![image](https://github.com/oqtane/oqtane.framework/assets/13577556/3426cd71-303e-44c2-97b0-4d52875e63e7)

**Comment by sbwalker** [comment]
If I login as a regular user and I navigate to a page which is personalizable, the initial view of the page will include the default non-personalized content as well as an Edit icon which can be used to create a personalized page:

![image](https://github.com/oqtane/oqtane.framework/assets/4840590/7f35d680-2d6c-4933-98cc-2d6bf7c2800c)

If I click the Edit icon, a personalized version of the page will be created containing a copy of all of the default page content. A Control Panel icon will be displayed:

![image](https://github.com/oqtane/oqtane.framework/assets/4840590/6217496b-a519-4dc1-9640-94ecb9cc8849)

If I click the Edit icon I can go into Edit Mode where I can modify the page content:

![image](https://github.com/oqtane/oqtane.framework/assets/4840590/0e486170-0743-4258-811a-50212c4b1ac9)

If I click the Control Panel icon I will see a menu of available options:

![image](https://github.com/oqtane/oqtane.framework/assets/4840590/65f3ebe0-4ee5-46ee-aee6-ef622c6faf5a)

By default, Add New Module is selected. The list of modules which can be added will only include modules to which the user has been granted Utilize permissions:

![image](https://github.com/oqtane/oqtane.framework/assets/4840590/5e3cab64-723f-43bb-b50c-f6f8f174e358)

![image](https://github.com/oqtane/oqtane.framework/assets/4840590/f0c0d5aa-ed20-4f11-9211-0688bbbe0b3f)

If you choose Add Existing Module, the list of pages displayed are only those to which the user has View access to. However this includes pages like Login and Register because from a permissions perspective, all users have view access to those pages. 

I believe that the "Add Existing Module" option should not be included in the Control Panel for this personalized page scenario.
