### ISSUE TITLE
[BUG] the control panel mask element won't hide after add a new module into page

### ISSUE THREAD

**Issue by zyhfish** [oqtane/oqtane.framework#4224]
### Oqtane Info

Version - 5.1.1
Render Mode - Static 
Interactivity - Server
Database - SQL Server

### Describe the bug
the control panel mask element won't hide after add a new module into page, user has to click on the page to hide the mask manually.

### Expected Behavior
The dialog mask should be hidden automatically after the control panel closed.

### Steps To Reproduce
1. login as host, click the gear button to open control panel.
2. the control panel will be closed after adding a new module into the page, but the mask still there.
![image](https://github.com/oqtane/oqtane.framework/assets/3364448/a49960e9-8846-4c7f-b3a5-7b189cf10712)

**Comment by mdmontesinos** [comment]
I'm also experiencing this issue.

**Comment by sbwalker** [comment]
@zyhfish please let me know if this is a reproducible issue - or isolated to your specific environment.

**Comment by zyhfish** [comment]
Hi @sbwalker , yes, this is reproducible only with Static render mode:

https://github.com/oqtane/oqtane.framework/assets/3364448/d06c98f6-53e8-49f7-bbb9-f05cc8677a2b

**Comment by zyhfish** [comment]
Hi @sbwalker , I submitted a new PR to keep the control panel open after adding a new module, anyway the code is not that beautiful, please check whether the change can be applied.

**Comment by sbwalker** [comment]
@zyhfish I am able to reproduce the issue in Static render mode as well. I have reviewed the PR and my general rule is that if something appears to be overly complicated, it usually is. So my preference would be to try to find a simpler solution if possible. In general, when we run into scenarios where there is a difference in behavior between Interactive and Static render mode, I would like to avoid conditional logic as it will become very complicated to maintain over time. So in a perfect world we would be able to find a solution which works on both render modes and does not require any conditional logic. That being said, there are already scenarios we have encountered where it is not possible to have a single solution which works in both render modes - and in these cases I would still prefer to try and find the simplest solution possible (ie. not introduce a bunch of complex logic and infrastructure which is specific to 1 render mode). 

In regards to this issue, the main problem is related to this statement:

NavigationManager.NavigateTo(Utilities.NavigateUrl(PageState.Alias.Path, PageState.Page.Path, ""));

in Oqtane.Client\Themes\Controls\Theme\ControlPanelInteractive.razor. Note that at this point we made a decision that the Control Panel is an Interactive component - regardless of whether it is being used in a Static or Interactive Site. This approach is working fine in all cases except for the Add Module scenario. The issue with the Add Module scenario is that the page needs to be refreshed with the new module that was added - and the desire is that the Control Panel stays visible so that the Admin can add more modules. This works fine in Interactive render mode. However in Static render mode, it is using .NET 8 Blazor Enhanced Navigation by default and when the NavigationManager.NavigateTo() method is called, some of the dynamic CSS classes which are part of the Control Panel are lost. Note that it is not doing a full server-side page refresh however the Blazor Enhanced Navigation DOM differencing algorithm seems to be resetting some attributes which it should not.

I believe the simplest solution would be to accept that the behavior may be different in Static rendering than Interactive rendering - and do a full server-side refresh when running on Static render mode. This will reset the mask. However the Control Panel will not remain open. The benefit of this approach is that the conditional logic is minimal and much easier to maintain long term than the code in the PR. And perhaps Microsoft will improve Enhanced Navigation in future .NET releases.

Or perhaps there is another simple alternative which has not been discovered yet. Either way, I am, going to keep this issue open in an effort to find a simpler solution.
