### ISSUE TITLE
[ENH] Usability: Remove or better demark the logout button in the side-panel

### ISSUE THREAD

**Issue by iJungleboy** [oqtane/oqtane.framework#4235]
### Oqtane Info

Version - 5.0
Render Mode - all
Interactivity - all
Database - all

### Describe the enhancement

ATM there is a huge logout button right under the "Add-Module" button which is very easy to hit by accident. 
This can be ever more difficult with other color schemes, where people will be clicking this by accident.

I recommend removing it or placing it much further down.

![image](https://github.com/oqtane/oqtane.framework/assets/5321186/710f7cd3-8055-4d27-90ab-54e2a8c704c8)

**Comment by leigh-pointer** [comment]
@iJungleboy 
up vote.  This has got me quite a few times!

**Comment by sbwalker** [comment]
The Logout button was added to the Control Panel for Themes which either do not include a Login button (ie. they simply use the "/login" url to login). In these scenarios there needs to be a way for a user to Logout - so this enhancement was added in the 4.0.4 release on Sep 25, 2024. Since it serves a specific purpose, we are not going to remove it. I will add an ```<hr>``` so that it is more clearly separated from the Module Management area. However since it took 9 months to be reported as a problem I would have to believe it is not a serious issue.
