### ISSUE TITLE
[BUG] Theme Settings not saved when creating a new page

### ISSUE THREAD

**Issue by leigh-pointer** [oqtane/oqtane.framework#4279]
### Oqtane Info

Version - 5.1.1
Render Mode - Static 
Interactivity - Server
Database - SQL Server

### Describe the bug
When creating new page and updating information on both the Settings tab and the Theme Settings tab on save the Theme settings are not saved.  This is obviously due to the fact the Page does not yet exist in the database.

### Expected Behavior
The Page should be created and then the Theme Settings saved on the save command

### Steps To Reproduce
Create a new page and enter Theme settings, save page.

**Comment by sbwalker** [comment]
@leigh-pointer There is actually more to this issue than what you described. There are 4 different scenarios where ThemeSettings components are rendered:

1. Add Page - invoked from Control Panel (page id is based on querystring parameter)
2. Add Page - invoked from Page Management (page id is based on url parameter)
3. Edit Page - invoked from Control Panel (page id is based on querystring parameter)
4. Edit Page - invoked from Page Management (page id is based on url parameter)

Oqtane contains an interface called ISettingsControl and it only contains a single method for UpdateSettings(). This interface allows parent components to call into child setting components such as Module Settings or Theme Settings. The problem is that these components need to be able to understand the context - which is not as simple as it is for modules where you can rely on the PageState or ModuleState. In the case of Theme Settings it needs to determine which of the 4 scenarios outlined above were used to invoke the component - so that it can get the PageId which will be required to update the database.

Currently the Oqtane Theme contains the following logic in OnInitializedAsync() to determine the PageId:

```
        if (PageState.QueryString.ContainsKey("id"))
        {
            pageId = int.Parse(PageState.QueryString["id"]);
        }
```

This handles scenario 3 from above... but does not handle any of the other 3 scenarios. Scenario 4 could be supported by getting the PageId from the url parameter. Scenarios 1 & 2 are a bigger problem - as the PageId is not known until the parent component actually creates the Page in the database. However there is no way to pass this PageId to the Theme Settings component. And in fact the Add Page component does not even call await themeSettingsControl.UpdateSettings() currently because of this problem. 

Unfortunately, I believe the only way to resolve this problem is to introduce a new ISettingsControl interface and enhance the UpdateSettings() method to be able to pass some state.

**Comment by leigh-pointer** [comment]
Good fix, as i see now how complex a solution would have been to be.
