### ISSUE TITLE
[ENH] - Ability to specify an anchor in Page Management

### ISSUE THREAD

**Issue by vnetonline** [oqtane/oqtane.framework#4315]
### Oqtane Info

Version - 5.1.2
Render Mode - Static 
Interactivity - Server
Database - SQL Server

### Describe the enhancement

- If you have a theme that has a, there should be the ability to specify an anchor in the Page Settings
- ATM, you can't use the UrlPath or Redirect to have, for example, `#about` so that it auto scrolls to the about section of the same page.

### Anything else?

- Is Oqtane currently able to do this? Am I missing something ?
- @sbwalker I don't want to code the Nav Menu into the theme hard. That would defeat the purpose of having pages,

**Comment by sbwalker** [comment]
@vnetonline this is already supported. If you look at https://www.oqtane.org you will notice that the about page (and many others) in the main nav use anchors. You need to use the Redirect property in the page settings. It can be either an absolute or relative Url and if it is specified the menu should utilize it rather than the Url Path when generating links. 

![image](https://github.com/oqtane/oqtane.framework/assets/4840590/a4e71ac2-fc79-4245-b840-13c6698b0753)
