### ISSUE TITLE
[ENH] Implement text editor provider

### ISSUE THREAD

**Issue by zyhfish** [oqtane/oqtane.framework#4316]
### Oqtane Info

Version - Latest
Render Mode - Static 
Interactivity - Server
Database - SQL Server

### Describe the enhancement
Add interfaces of text editor so that we can have ability to introduce other rich text editors.

**Comment by sbwalker** [comment]
I think this abstraction looks good. One other item I have been thinking about is the RichTextEditor component itself. Currently it is comprised of multiple features (in yellow in diagram below) - which are all related/dependent upon one another:

![image](https://github.com/oqtane/oqtane.framework/assets/4840590/41bf1680-7314-4624-93f2-dd1da190755b)

1. The reason why there are 2 tabs - one for Rich Text Editor and Raw HTML Editor is because QuillJS is not an HTML editor and there is a need for more granular control in some cases to customize HTML. However if you were using a different rich text editor component than QuillJS - one which supported HTML more natively - then there would be no need for a Raw HTML Editor option.

2. There is an ability to insert an image into the Rich Text Editor (or Raw HTML Editor). It uses the standard FileManager component to ensure permissions are enforced, uploads are secure, and assets are stored in the proper locations. However the Insert button uses JavaScript which is specific to the QuillJS editor.  If you were using a different rich text editor component than QuillJS - it would require different logic to insert an image. 

3. This is the actual QuillJS editor. Currently the initial PR submitted for this issue allows you to replace this component with an alternative component.

However based on what I described above, it seems that the actual component which needs to be replaceable with an alternative is the entire area outlined in green. Basically, the QuillJS editor would contain the 2 tabs for Rich Text Editor and Raw HTML Editor , the FileManager/insert logic, and the QuillJS editor. If you wanted to create an alternative (ie. using something like FCK editor for example) the alternative would not need 2 tabs - it would only need 1 view which contains the editor as well as a FileManager with specific integration logic to allow for the insertion of images into the content (although it would be possible to use the native file manager included with the editor I would strongly recommend against it as the integration would be poor and the security risk would be high).

Does this make sense?

**Comment by zyhfish** [comment]
Hi @sbwalker , thanks so much for the review, the PR has been updated to move the raw html editor into Quill editor.
