### ISSUE TITLE
[BUG] no install button after module upload

### ISSUE THREAD

**Issue by dvdobrovolskiy** [oqtane/oqtane.framework#4397]
### Oqtane Info

Version - 5.1.1
Render Mode - Static 
Interactivity - Server
Database - SQL Server

### Describe the bug
should be an install button after module uploaded. 
![image](https://github.com/oqtane/oqtane.framework/assets/7299951/71cd87a9-e427-4c56-9159-6231c7c867a2)

But there is no Install buttom
![image](https://github.com/oqtane/oqtane.framework/assets/7299951/b07966d5-5bd4-4c5e-a64b-7521a80d98da)

nupkg file itself uploaded to \Packages\ folder.

**Comment by leigh-pointer** [comment]
@dvdobrovolskiy If you look above a the message at the top.

"Module Package Downloaded Successfully. You Must **Restart** Your Application To Complete the Inatallation."
Click the restart link and then the module(s), Theme(s) will be loaded.

HTH.

**Comment by dvdobrovolskiy** [comment]
Did it several times. No install button but module appered

**Comment by leigh-pointer** [comment]
There is no install button . When you click download the package is downloaded and unpacked in the correct folder / folders. The installation is done but the system needs to restart to load the new assemblies into the Oqtane application domain.

**Comment by sbwalker** [comment]
@dvdobrovolskiy the Install button was removed from the UI on Aug 15, 2022 in this PR - https://github.com/oqtane/oqtane.framework/commit/cc3cc55269db896caa4c88567a8e427e4b6d949c. However I can understand the confusion because the Help Text in the Upload tab still says "Upload one or more module packages. Once they are uploaded click Install to complete the installation.". The Help Text should be changed to reflect the actual functionality.
