### ISSUE TITLE
[BUG] private page will not display after login

### ISSUE THREAD

**Issue by zyhfish** [oqtane/oqtane.framework#4401]
### Oqtane Info

Version - Latest dev branch
Render Mode - Static 
Interactivity - Server
Database - SQL Server

### Describe the bug
private page will not display after login.

### Expected Behavior
private page should appear in the menu after login with host user.

### Steps To Reproduce
1. open the site in anonymous mode, the menu will only display Home and My Page, this is expected result.
2. Login with the host user.
3. After login, the private page should appear in the menu.

### Anything else?
None

**Comment by sbwalker** [comment]
I am able to reproduce - thank you for reporting. This is related to the scalability changes in the Dev branch - specifically the changes in caching. I will investigate.

**Comment by sbwalker** [comment]
Previously the Site object was being cached per user - which had scalability limitations. It is now cached once per site. This issue is a result of the code below:

```
       public async Task<Site> GetSiteAsync(int siteId)
       {
           var alias = _tenantManager.GetAlias();
           var site = await _cache.GetOrCreateAsync($"site:{alias.SiteKey}", async entry =>
           {
               entry.SlidingExpiration = TimeSpan.FromMinutes(30);
               return await GetSite(siteId);
           });

           var pages = new List<Page>();
           foreach (Page page in site.Pages)
           {
               if (!page.IsDeleted && _userPermissions.IsAuthorized(_accessor.HttpContext.User, PermissionNames.View, page.PermissionList) && (Utilities.IsEffectiveOrExpired(page.EffectiveDate, page.ExpiryDate) || _userPermissions.IsAuthorized(_accessor.HttpContext.User, PermissionNames.Edit, page.PermissionList)))
               {
                   pages.Add(page);
               }
           }
           site.Pages = pages;

           return site;
       }
```

On the surface this looks fine - the code retrieves the Site object from the cache and then it security trims the Pages collection to only include the pages which the current user has access to. The problem is that the cache object does not behave as expected. The GetOrCreateAsync method retrieves the object by reference - not by value. So setting the Site.Pages property actually changes the contents of the object stored in the cache.
