### ISSUE TITLE
SSO implementation within 2 oqtane server applications, Login into one app logs out the second app

### ISSUE THREAD

**Issue by zohaibwhizz** [oqtane/oqtane.framework#4409]
Hi, 
I have an identity duende server configured as SSO IDP. We already using this for our MVC applications.  Now we want to implement SSO between multiple Oqtane applications. 
I have configured IDP from admin dashboard in both Oqtane applications as per documentation (Expternal Login Settings section, Under user management). However when I logged into one application the other application does not get logged into automatically. Now if I logged into second application manually then the first application get logged out automatically. 
Could you please guide me where I am wrong. How can I implement SSO between 2 different Oqtane application? 
As I am still learning Oqtane so I have both Oqtane applications running from visual studio.  
I am attaching SS for both apps settings

![image](https://github.com/user-attachments/assets/50cf1436-5269-4ec3-aa90-113047241308)

![image](https://github.com/user-attachments/assets/fb451383-cb67-43eb-9b8d-d017a7be90bc)

**Comment by sbwalker** [comment]
Oqtane uses a backend-for-frontend (BFF) security architecture - documented here:

https://www.oqtane.org/blog/!/39/backend-for-frontend-bff-architecture

Web clients can authenticate against a remote IDP however the user's credentials are then stored in cookies. Since cookies are domain specific, if you want to have 2 Oqtane installations that share SSO then you would need to use subdomains or port#s so that both installations are under the same domain.
