### ISSUE TITLE
[BUG] Theme Issues: New theme, with changing theme after adding New theme RocketFuel

### ISSUE THREAD

**Issue by ridingmower** [oqtane/oqtane.framework#4510]
hello I am using latest 5.2 version and trying to build themes for oqtane, and modules, but testing it broke the entire app.

### Bug: After install and switch _rocket fuel theme_ breaks navigation and other functionality to admin dashboard.

- [ ] After install and switch _rocket fuel theme_ breaks navigation and other functionality to admin dashboard and other pages, after cloning and first run, go to theme management add new theme from marketplace and restart app, all the site functionality and navigation is lost.
- [ ] Nice to have, a master control or some form of **reset to gain the default site behavior back**. Currently I cant, except delete everything reclone , and new db
- [ ] in place update or reinstall button in dashboard

### Issue: navigation is lost, click admin/dashboard no longer works

![image](https://github.com/user-attachments/assets/7b00aefc-8f32-4cdf-b1d7-dfe062a50e65)

### Steps To Reproduce

- [ ] Add new theme rocket fuel v 5.2 from market place via theme management
- [ ] Restart app
- [ ] switch to new theme
- [ ] Click on admin dashboard

### New theme development items/issues:

- [ ] Project location, when creating a new scaffolded theme project _creates it outside solution folder_, expected behavior _is within the solution folder in a separate project folder_.
- [ ] Help with, numbered steps or & inline Comments on which files to be modified, in the theme & modules project
- [ ] Where do I add the JS files 3 party plugins in the theme project
- [ ] How do I refer to them, is there a bundler to register?
- [ ] If I am adding 3rd party js plugins like [jquery bracket](https://www.jqueryscript.net/tags.php?/Tournament%20Bracket/), howler, js colorpicker2 how to add scss or new plugin css,

**Comment by sbwalker** [comment]
@ridingmower RocketFuel theme is not part of the Oqtane framework... it is a 3rd party theme so I would suggest you ask it's developer for assistance with the issues you encountered

 In regards to new theme development, these are not "issues" - they are support requests and should be posted in the Discussion area.
- projects are scafolded outside of the solution folder by design - Oqtane is a modular framework - not a project template. The whole idea is that extensions are developed/deployed independently from the framework (which also allows the framework to be upgraded independently from the extensions).
- if you review some of the example themes (ie. https://github.com/oqtane/Oqtane.Theme.Arsha) you will see how JavaScript resources are registered

**Comment by leigh-pointer** [comment]
Hello @ridingmower as @sbwalker says this is third party and i am said party so please reach out https://www.studio-elf.net/contact and then we can start a discussion
