### ISSUE TITLE
[Route question] How manage dynamic route in this Framework 

### ISSUE THREAD

**Issue by Trongnguyen-IT** [oqtane/oqtane.framework#4528]
### Oqtane Info

Version - lastest
Render Mode - Static 
Interactivity - Server
Database - SQL Server

Hi team,
I have create application with Oqtane but currently, I don't know how to create dynamic route in project.
Details: I have list News and I want to click to News item to navigate to News details. 
I have tried with @page "/newsdetails/{Id:int}" but It is seem ignore. Hope your team give me advise.

**Comment by zyhfish** [comment]
Hi @Trongnguyen-IT , to accept additional URL parameters, you can set the UrlParametersTemplate property, for example:
https://github.com/oqtane/oqtane.blogs/blob/4945e4e2772d4c7e3b198bab01d774b8a0d09f09/Client/Index.razor#L178

in this case, URL "{URL}/!/123/abc" will parse the parameters to PageState.UrlParameters object.

**Comment by sbwalker** [comment]
@Trongnguyen-IT the standard Blazor @page directive is not supported in Oqtane. This is because the @page directive is a static definition which is hard-coded into a component and cannot be changed at run-time... whereas Oqtane is a fully dynamic framework where the routes are not hard-coded into components and are instead managed based on run-time configuration. 

To create the News module you are describing would be very simple. I would always recommend starting with the default module template:

- login to your Oqtane site as the host user
- navigate to the Control Panel / Admin Dashboard and choose Module Management
- click Create Module button
- enter Organization name (ie. TrongnguyenIT), Module name (ie. News), select default template, and select Oqtane version 5.2.0
- Create Module

this will scaffold a completely functional module with all required code. Open the solution file in Visual Studio and compile the code. Then hit F5 to run the solution. Your browser will open and display the default Oqtane site. Use the Control Panel to add an instance of the News module to your page. Enter a few News items.

Now you are going to modify the module's functionality. Stop the Visual Studio debugger and expand the Client project  and Modules folder to find the razor components. 

Open the Index.razor component

Change the line:

```
<td>@context.Name</td>
```

to 

```
<td><a href="@EditUrl("View", $"id={context.NewsId.ToString()}")">@context.Name</a></td>
```

EditUrl() is a helper method which generates Urls in the format which Oqtane's custom router can interpret so that it can dynamically load components.

Now create a new razor component named View.razor (in the same folder where the other razor components are located). Paste the following code into the component:

``
@using Oqtane.Modules.Controls
@using TrongnguyenIT.Module.News.Services
@using TrongnguyenIT.Module.News.Models

@namespace TrongnguyenIT.Module.News
@inherits ModuleBase
@inject INewsService NewsService

@_name
<br /><br />
<NavLink class="btn btn-secondary" href="@NavigateUrl()">@Localizer["Cancel"]</NavLink>
<br /><br />
<AuditInfo CreatedBy="@_createdby" CreatedOn="@_createdon" ModifiedBy="@_modifiedby" ModifiedOn="@_modifiedon"></AuditInfo>

@code {
    public override SecurityAccessLevel SecurityAccessLevel => SecurityAccessLevel.View;
    public override bool UseAdminContainer => false;

    private string _name;
    private string _createdby;
    private DateTime _createdon;
    private string _modifiedby;
    private DateTime _modifiedon;

    protected override async Task OnInitializedAsync()
    {
        try
        {
            var news = await NewsService.GetNewsAsync(Int32.Parse(PageState.QueryString["id"]), ModuleState.ModuleId);
            if (news != null)
            {
                _name = news.Name;
                _createdby = news.CreatedBy;
                _createdon = news.CreatedOn;
                _modifiedby = news.ModifiedBy;
                _modifiedon = news.ModifiedOn;
            }
        }
        catch (Exception ex)
        {
            await logger.LogError(ex, "Error Loading Item {Id} {Error}", PageState.QueryString["id"], ex.Message);
            AddModuleMessage("Error Loading Item", MessageType.Error);
        }
    }
}
```

Compile the module in Visual Studio. And then hit F5. This time when the module is displayed, the names of the items in the list will be hyperlinks and when you click on them, the new View.razor component will be displayed with the information for that item.

**Comment by Trongnguyen-IT** [comment]
Hi @sbwalker ,
I have create new module and name News. and make some code. but when click to hyperlink. it show empty content.

![Screenshot 2024-07-08 150125](https://github.com/user-attachments/assets/a6d26a87-d855-4573-8466-59f3b391381b)
![Screenshot 2024-07-08 150141](https://github.com/user-attachments/assets/4b4891d7-a10d-4847-ad10-299ae5423fd1)
![Screenshot 2024-07-08 150211](https://github.com/user-attachments/assets/08d49359-3fae-4003-aebf-f5399e8473fd)

**Comment by Trongnguyen-IT** [comment]
And the URL same picture
![image](https://github.com/user-attachments/assets/12603803-1d39-4681-84ac-91c00a992280)

**Comment by sbwalker** [comment]
@Trongnguyen-IT the screen shot of code you shared above does not match the code provided in the answer. It appears that you commented out the code which loads the news item. And based on the yellow (!) icon it appears that you did not compile your code.

**Comment by Trongnguyen-IT** [comment]
Hi, let me try with new project and let you know the result. thank you!

**Comment by Trongnguyen-IT** [comment]
Hi @sbwalker ,
I have created new project and apply exactly code in View.razor. but It can not go to break point in View.razor. I don't understand why it can go to Edit.razor but can not go to View.razor. you can see the code implement in the picture below.
Could you please help me about that?
![Screenshot 2024-08-20 235753](https://github.com/user-attachments/assets/361d9a48-c495-460f-9e9a-1fede25bc927)
![Screenshot 2024-08-20 235731](https://github.com/user-attachments/assets/6d9d0c09-1bc5-44a1-80d6-4444a1606d69)
![Screenshot 2024-08-20 235512](https://github.com/user-attachments/assets/549a5de5-2ae0-4888-8e8b-4e768e06117e)
![Screenshot 2024-08-20 235446](https://github.com/user-attachments/assets/3222ded2-c70d-4721-adbf-73cb1d3e35ad)
![Screenshot 2024-08-20 235429](https://github.com/user-attachments/assets/7820f9b8-a33f-49d0-9063-6e796b58241d)
![Screenshot 2024-08-20 235948](https://github.com/user-attachments/assets/48648ed4-e36e-4b1b-989d-d4354512910a)

**Comment by sbwalker** [comment]
@Trongnguyen-IT I just followed my earlier instructions and the only issue I ran into was the reference to Localizer("Cancel") - which you had already resolved. After I build the code and run the application and click the hyperlink I see:

![image](https://github.com/user-attachments/assets/55615a45-0536-466f-a8b3-5df46469bef5)

The only thing I can suggest is that when you compile the module solution, use Build / Rebuild Solution:

![image](https://github.com/user-attachments/assets/b8a2c1c7-66db-48a2-ad54-d8988066a71f)

You should see the following in your console (note all of the files being copied to the appropriate locations)

![image](https://github.com/user-attachments/assets/ed3db012-c8be-494e-a433-6d04d363000e)

**Comment by Trongnguyen-IT** [comment]
Hi @sbwalker , I found out the problem, the namespace is wrong. I misunderstand between TrongNguyen and TrongNguyenIT.
Now it working fine. thank you for your support!
