### ISSUE TITLE
[BUG] ITenantService.GetTenantAsync() returns NULL after database change 

### ISSUE THREAD

**Issue by DiegelB** [oqtane/oqtane.framework#4539]
### Oqtane Info

Version - 5.2.1
Render Mode - Static 
Interactivity - Server
Database - Microsoft SQL Server

### Describe the bug
I have a simple module that inserts some data into a new table that I created, on a button press. I am using the ITenantService to grab the DBType and DBConnectionString to use in the sql service. I made the table in my database prior to writing the code. It will run fine and enter in the correct information. Now if the schema of the table changes, then GetTenantAsync() will return Null until I either delete the module and start over, or delete the bin and obj files (but that has only worked once). 

### Expected Behavior
I was expecting to add a new column in the table that I created and then update my sql query to insert data into that new column, but when I run it after making sql changes then the GetTenantAsync() comes back null. I make no other code changes. 

### Steps To Reproduce
```
@inherits ModuleBase
@using System.Security.Claims
@inject AuthenticationStateProvider AuthenticationStateProvider
@inject ITenantService TenantService
@inject Oqtane.Services.ISqlService SqlService

<button @onclick="InsertInto">Insert Into</button>

@if (tenantName > 0)
{
    <p>@tenantName</p>
    <p>@message</p>
}
else
{
    <p>Loading...</p>

}

@code {
    private int tenantName;
    private string message;
    private async Task InsertInto()
    {
        var tenant = await TenantService.GetTenantAsync(PageState.Site.TenantId);
        tenantName = tenant.TenantId;


        var sqlQuery = new SqlQuery
            {
                TenantId = PageState.Site.TenantId,
                DBType = tenant.DBType,
                DBConnectionString = tenant.DBConnectionString,
                Query = $"SELECT UserId FROM UserStats WHERE UserId = {userId}"
            };

        SqlQuery results = await SqlService.ExecuteQueryAsync(sqlQuery);

        if (results != null)
        {
            message = "User already exists";
            return;
        }
        else
        {
            message = "User does not exist adding record now";
            var sqlQuery1 = new SqlQuery
                {
                    TenantId = PageState.Site.TenantId,
                    DBType = tenant.DBType,
                    DBConnectionString = tenant.DBConnectionString,
                    Query = $"INSERT INTO UserStats(UserId, Strength, Dexterity, Constitution, Intelligence, Wisdom, Charisma) VALUES('{userId}', '5', '5', '5', '5', '5', '5')"
                };

            await SqlService.ExecuteQueryAsync(sqlQuery1);
        }

    }

    private ClaimsPrincipal user;
    private string userId;

    protected override async Task OnInitializedAsync()
    {
        var authState = await AuthenticationStateProvider.GetAuthenticationStateAsync();
        user = authState.User;

        if (user.Identity.IsAuthenticated)
        {
            userId = user.FindFirst(ClaimTypes.NameIdentifier)?.Value;
        }

    }
}
```

You can create a new module and use this code. Make sure you have a table in sql with the correct columns. After it runs the data will be inserted into the correct table UserStats. If you were to delete the table and add it again with all the same columns (or add a new column) and run the code again, then the ITenatService comes back as null. 

### Anything else?

I could be doing something wrong and this could be intended. I am new to this framework and im trying to figure out all the pieces.

**Comment by sbwalker** [comment]
@DiegelB this is not the recommended way to implement your desired functionality...

1. Oqtane is a client/server application which means there is a public API which the client application calls using Service classes (which internally use HttpClient) to get information. Since the API is public, the various endpoints are secured so that only authorized users can access them. 
2. The TenantService can only accessed by host users - so unless you are logged in as a host user, these API calls will fail. The TenantService is only intended for allowing a host user to manage sites/tenants within the Oqtane Admin UI.
3. The SqlService can only accessed by host users - so unless you are logged in as a host user, these API calls will also fail. The SqlService is only intended for allowing a host user to access the Sql Management feature within the Oqtane Admin UI.
4. You do not need to reference the AuthenticationStateProvider or ClaimsPrincipal to determine the UserId - you simply need to reference PageState.User.UserId

Based on your requirements and code example, it appears that you want to run this component on the Server as an Interactive component and you want to use dynamic SQL for data access. Here is an example:

*Note that you will need to include a package reference to Oqtane.Server in your modules's Client project (the reference does not exist because the default module template is designed to keep the Client and Server concerns separated from one another):

```
<PackageReference Include="Oqtane.Server" Version="5.2.0" />
```

and here is the Index.razor:

```
@inherits ModuleBase
@using Oqtane.Repository
@inject ITenantRepository TenantRepository
@inject ISqlRepository SqlRepository

<button @onclick="InsertInto">Insert Into</button>

@if (tenant != null)
{
    <p>@tenant.Name</p>
    <p>@message</p>
}
else
{
    <p>Loading...</p>
}

@code {
    private Tenant tenant;
    private string message;

    protected override void OnInitialized()
    {
        tenant = TenantRepository.GetTenant(PageState.Site.TenantId);
    }

    private void InsertInto()
    {
        var dr = SqlRepository.ExecuteReader(tenant, $"SELECT UserId FROM UserStats WHERE UserId = {PageState.User.UserId}");
        if (dr.Read())
        {
            message = "User already exists";
            return;
        }
        else
        {
            message = "User does not exist adding record now";
            SqlRepository.ExecuteNonQuery(tenant, $"INSERT INTO UserStats(UserId, Strength, Dexterity, Constitution, Intelligence, Wisdom, Charisma) VALUES('{PageState.User.UserId}', '5', '5', '5', '5', '5', '5')");
        }
    }
}
```

Note that your razor component is running on the server in this example and therefore is able to access the server Repository methods directly. As a result this code would not run on WebAssembly or .NET MAUI - it will only work in a Server run-time scenario.

**Comment by DiegelB** [comment]
Man, you are awesome Shaun. Thank you so much for the explanation! Once I get all the knowledge down, I can't wait to start helping you all out with projects on this repo.
