### ISSUE TITLE
[BUG] Scroll position not kept after enhanced navigation

### ISSUE THREAD

**Issue by mdmontesinos** [oqtane/oqtane.framework#4666]
### Oqtane Info

Version - 5.2.3
Render Mode - Static 
Interactivity - Server
Database - SQL Server

### Describe the bug

Enhanced navigation after a post request to the same page with different query, results in scrolling back to the top of the page. I believe in previous version this was working as expected.

### Expected Behavior

Scroll position should be maintained when enhanced navigating to the same page with different query.

### Anything else?

I believe this was caused by recent commit (https://github.com/oqtane/oqtane.framework/commit/be5df9c22a18fb5a0b7f6eb9033f2391b2695fb8)

**Comment by sbwalker** [comment]
#4653 was intended to fix the issue where you have a page with a lot of content and are scrolled to the bottom of the page... and you click a link for that same page which should reposition the browser scroll position to the top (ie. if you were on the Home page and clicked the Home link in the nav menu, the site logo, or perhaps had a button at the bottom of the page for "scroll to top"). This scenario was not working due to enhanced navigation and #4653 resolved it - however it sounds like it affects other enhanced navigation scenarios. Enhanced navigation is definitely a major challenge in Blazor.

**Comment by sbwalker** [comment]
I can rollback the fix in #4653 however it means that the other issue I described above will continue to be a problem. It was very easy to reproduce this issue in a default installation of Oqtane - simply add a bunch of content to one of the Home page HtmlText modules, scroll the browser to the bottom of the page and then click the Logo or the Home link in the nav menu and the scroll position would not change - it will remain at the bottom of the page.

One potential solution is to modify the scroll position script to be more targeted and use a convention to invoke the desired behavior ie:

```if (currentUrl !== newUrl || window.location.hash === '#top') ```

Then if you added a link at the bottom of the page :

```<a href="#top">Top</a>```

The script would recognize the convention and would position the scroll position at the top of the page.  However I am not sure if this would be a good approach for other scenarios such as the Logo or Nav menu as it would require a "#top" fragment to be added to the Url for the current page.

**Comment by mdmontesinos** [comment]
Well, it's either that or the opposite solution. Having a query parameter, i.e. ?keepScroll=true, that is also recognized by the scroll position script so it keeps the scroll when doing an enhanced navigation. This could be added from <a> tags or post requests.

Which one is the least bad option and requires fewer changes? Anyhow, Microsoft should really improve the scroll handling with enhanced navigation in Blazor.
