### ISSUE TITLE
BUG:  Role can not be saved

### ISSUE THREAD

**Issue by svreic** [oqtane/oqtane.framework#475]
Exception is thrown if a role is saved if a long description is entered.

## Expected Behavior
The role can be saved without an exception 

## Current Behavior
Exception is thrown if the description of the role exceeds 50 character. 

## Possible Solution
The description column type should be extended from varchar(50) to varchar(256). Also the maxlength of the textarea of the description should be limited to 256 characters. 

## Steps to Reproduce
1. Add or Edit a Role
2. Write a long description
3. Click the Save button

**Comment by sbwalker** [comment]
A few comments:

- currently none of the forms in any of the admin UIs validate or restrict field lengths - this is not limited to Role Management
- if we want to implement field length validation it needs to be implemented on both the client UI elements as well as the server API controllers
- role descriptions are not surfaced anywhere in the application currently and actually serve no purpose so I am not sure if the length needs to be expanded. 
- in order to modify the database schema a new tenant upgrade script needs to be added for the next releasable version

**Comment by svreic** [comment]
> if we want to implement field length validation...

I suggest to do it because of stability. The current implementation leads to an exception in the db-update/insert process.

> it needs to be implemented on both the client UI elements as well as the server API controllers

I haven't thought about the API controller in that context and of course, it needs to be implemented on both sides. 

> this is not limited to Role Management

If we decide to implement field length validation than this should be implemented in the whole framework. For that reason i suggest that we create an issue with a checklist for all admin UIs that needs field length validation. I can do it if we decide to do it. Than we can do this step-by-step.

> role descriptions are not surfaced anywhere in the application currently and actually serve no purpose so I am not sure if the length needs to be expanded.

The description field currently only supports 50 characters whereas the name field supports 256 character. Mostly the description of something will be more text than the name of something. In context of UX a user mostly expect that the description can be longer than the name. Currently the UI of the Role Management looks like you can have a longer description. The filed for the name is a single line input and the description field is a multi line textarea. Just my 2 cents.

**Comment by sbwalker** [comment]
I made a quick fix in #616 for this item. There is still a broader topic of form validation in general, but this addresses this specific bug which was reported.
