### ISSUE TITLE
[Question] how should we validate the Regex in Settings Page of the Module?

### ISSUE THREAD

**Issue by kolliLakshmaiah1219** [oqtane/oqtane.framework#4769]
### Oqtane Info

Version - 5.2.1

**Comment by zyhfish** [comment]
Hi @kolliLakshmaiah1219 , could you please provide the detail information of your question?

**Comment by sbwalker** [comment]
@kolliLakshmaiah1219 you will need to explain what you are trying to do... is this a new custom module you have created?

**Comment by kolliLakshmaiah1219** [comment]
We are developing custom module 
![IMG-20241023-WA0002](https://github.com/user-attachments/assets/91233781-de38-45bf-bf0c-2f56d59d7b01) when I am clicking on the save button, in the 
UpdateSettings() method in settings page
 I am validating the e-mail is valid format or not using Regex if it is not valid I am adding module warning 
The problem is if I am having the module error the Module settings popup is closed why?

**Comment by sbwalker** [comment]
The ISettingsControl interface is very limited currently as it only contains an UpdateSettings() method which does not support validation (ie. it does not return a boolean to indicate if the update was successful). Since this is an interface it cannot be changed... a new interface would need to be introduced however the old interface would still need to be retained for backward compatibility. The interface should probably also include a way to pass some arbitrary state to the method, as this limitation has also been raised previously. 

For the current version of the framework you can solve this by creating a standard module component ie. EditSettings.razor where you have full control to load, validate, and save settings.

**Comment by kolliLakshmaiah1219** [comment]
@sbwalker   can you please point me to a sample code where this is done?

**Comment by sbwalker** [comment]
If you created your module using the Create Module option in Module Management, simply copy the Edit.razor to create a new component called EditSettings.razor and implement the standard Blazor methods. Then add a button to your Index.razor:

<ActionLink Action="EditSettings" />

**Comment by kolliLakshmaiah1219** [comment]
i understood, Thank you
