### ISSUE TITLE
[BUG] Normal users do not login

### ISSUE THREAD

**Issue by enfJoao** [oqtane/oqtane.framework#4830]
### Oqtane Info

Version - 5.2.4
Render Mode - Static
Interactivity - Server
Database - SQL Server

### Describe the bug
Host user logs in with no issues.
Created a new user, logged out, filled the new user credentials, but it returns to the home page with no login.
The pages it has access to do not show and the login control still shows "login".
Log event shows the login was successful, so it's not a credential issue. Clearing cache and browser data and restarting the server does not solve it.

User management shows the timestamp on the last login (but the user details modal shows the last login empty, probably a separate issue).

**Comment by enfJoao** [comment]
45mins later, and this issue is no longer present. Not sure what changed...

**Comment by W6HBR** [comment]
I'm seeing this issue after a user initiated password change.  The password changes sucessfully and the user then logs in, but the protected content does not appear and the Login prompt still shows Login instead of changing to Logout.

After a period of time or an immediate restart of Oqtane, then the new password does work successfully for a proper login.  Seems as though something is getting cached on the server preventing a newly changed credential from working.
