### ISSUE TITLE
[BUG] Add Language

### ISSUE THREAD

**Issue by MauroG63** [oqtane/oqtane.framework#4855]
### Oqtane Info

Version - 6.0
Render Mode - Static 
Interactivity - Server
Database - SQLite

### Describe the bug
Exception, when i try to add a new language: name is null.

### Anything else?
Investigating i noticied that in the module LanguageEntityBuilder the 'name' field is created also.
Removed from module, with a new installation, everything is ok.

**Comment by sbwalker** [comment]
Please explain the steps to reproduce. I just tried adding a language to a site in new installation of 6.0 and it worked fine.

**Comment by sbwalker** [comment]
Name was originally a field stored in the Language table in the database.... however it was dropped in version 5.2.4:

Oqtane.Server\Migrations\Tenant\05020401_RemoveLanguageName.cs

Perhaps this is causing a problem in SQLite (as not all data providers handle migrations the same)

**Comment by sbwalker** [comment]
Ahh yes... I see this logic in the SQLite Database provider

```
        public override void DropColumn(MigrationBuilder builder, string name, string table)
        {
            // not implemented as SQLite does not support dropping columns
        }
```

**Comment by sbwalker** [comment]
This issue is a bit confusing....

The official SQLite documentation says that DROP COLUMN is support:

https://www.sqlite.org/lang_altertable.html

However when you attempt the operation through EF Core you get an exception:

SQLite does not support this migration operation ('DropColumnOperation'). See https://go.microsoft.com/fwlink/?LinkId=723262 for more information and examples. at Microsoft.EntityFrameworkCore.Migrations.SqliteMigrationsSqlGenerator.Generate(DropColumnOperation operation, IModel model, MigrationCommandListBuilder builder, Boolean terminate) 

Which is why the Oqtane SQLite provider has an overload for the DropColumn() method which does nothing (to avoid this exception)

**Comment by MauroG63** [comment]
Yes, i checked.
For now my solution is to delete the name field by a database manager, or, 
Alternatively use MS SQL database
Thank you for your support.

**Comment by sbwalker** [comment]
The only way to resolve this is to add the column back via a migration in 6.0.1 - however that column will not actually be used by the framework - it is deprecated. We had to do something similar in the past in the 3.3.1 release related to the Folder IsDeleted field for the same reason (ie. to support SQLite's technical limitations).
