### ISSUE TITLE
[ENH] Oqtane ControlPanel component forces edit button unto page

### ISSUE THREAD

**Issue by iJungleboy** [oqtane/oqtane.framework#4883]
### Oqtane Info

Version - 5.x up to 6.0
Render Mode - all
Interactivity - Server
Database - SQL Server

### Describe the bug

The razor component `ControlPanel` should be responsible for making the control panel available.
But it also forces a visible edit button unto the page, which is not desirable, because this makes it impossible to create your own.

Here's an example: in both cases there is a customized toolbar (custom languages, custom buttons) but the forced edit still appears (languages could be disabled).

![image](https://github.com/user-attachments/assets/ffd33a11-350f-4dc2-9895-32a47252f22c)

![image](https://github.com/user-attachments/assets/5202e370-7e31-44fb-95ff-0e0fbb2902c6)

### Expected Behavior

Either

1. The edit button is a separate control which can be added as needed
2. or the ControlPanel has a `ShowEditToggle` parameter (just like `ShowLanguageSwitcher`) to allow not having that button

My recommendation _would_ be to keep concerns separate, and not combine these controls. But because I assume "the ship has sailed" we should probably just add the toggle. 

### Anything else?

I would be happy to contribute the fix, but must be sure that it would be accepted, and that the naming for this Parameter is according to your expectations.

**Comment by sbwalker** [comment]
This is not a bug... the Control Panel component has had this behavior since version 1.0 (ie. since 2020). If a developer does not like the default behavior of the Control Panel component, they have always had the flexibility to create their own custom Control Panel component. The ability to hide the Edit Mode toggle can certainly be added as an enhancement to the existing Control Panel component - as long as the default value is False (so that it does not affect existing installations).

**Comment by iJungleboy** [comment]
@sbwalker sounds good, I'll commit some code.

What would you like for a property name - just so I don't use a different naming convention?

**Comment by sbwalker** [comment]
There is already a ShowLanguageSwitcher property so I would suggest a ShowEditMode property (default to True). However please be very careful when adding this enhancement so that the current behavior is not affects. The EditMode button supports both static and interactive render modes, is displayed based on a number of different business rules, and is also used as part of page personalization (ie. the ability to create a custom page for an individual user).

**Comment by tvatavuk** [comment]
## Summary
- Introduced `ShowEditMode` parameter in `ControlPanel`.
- Default value is `true`; existing behavior remains unchanged.
- Tested with default and modified themes, across different users and render modes.
- Confirmed that the Edit Mode toggle button can now be hidden when `ShowEditMode` is set to `false`.

## Tests

Here are the test cases for each combination of user type and render variation:

### Group 1: Default Themes Preserving Existing Behavior

#### Test Case 1
- Title: Anonymous User - Static Server Render - Oqtane Default Theme
- Expected Result: 
  The Edit Mode toggle button is not visible to the anonymous user. The page renders correctly using the Oqtane Default theme with static server-side rendering.
![image](https://github.com/user-attachments/assets/ff66a145-523a-4652-b062-0295cf41081e)

#### Test Case 2
- Title: Admin User - Static Server Render - Oqtane Default Theme
- Expected Result:
  The Edit Mode toggle button is visible to the admin user. The admin can toggle Edit Mode as expected. The page renders correctly using the Oqtane Default theme with static server-side rendering.
![image](https://github.com/user-attachments/assets/fd5ca2f4-6d83-4665-8408-37982aa8b95e)
   
#### Test Case 3
- Title: Anonymous User - Static Client Render - Blazor Default Theme
- Expected Result:
   The Edit Mode toggle button is not visible to the anonymous user. The page renders correctly using the Blazor Default theme with static client-side rendering.
![image](https://github.com/user-attachments/assets/3096aa67-5818-4423-92eb-35535787ccf0)

#### Test Case 4
- Title: Admin User - Static Client Render - Blazor Default Theme
- Expected Result:
  The Edit Mode toggle button is visible to the admin user. The admin can toggle Edit Mode as expected. The page renders correctly using the Blazor Default theme with static client-side rendering.
![image](https://github.com/user-attachments/assets/c8f16e01-9129-48ea-b477-474199591db8)

#### Test Case 5
- Title: Anonymous User - Static Auto Render - Blazor Default Theme
- Expected Result:
  The Edit Mode toggle button is not visible to the anonymous user. The page renders correctly using the Blazor Default theme with static auto rendering.
![image](https://github.com/user-attachments/assets/0c4e1da7-4666-4fb6-9bbb-249bd2623b13)

#### Test Case 6
- Title: Admin User - Static Auto Render - Blazor Default Theme
- Expected Result:
  The Edit Mode toggle button is visible to the admin user. The admin can toggle Edit Mode as expected. The page renders correctly using the Blazor Default theme with static auto rendering.
![image](https://github.com/user-attachments/assets/3410fdaf-f48d-424f-b401-38bf1240fe8b)

#### Test Case 7
- Title: Anonymous User - Interactive Server Render - Oqtane Default Theme
- Expected Result:
  The Edit Mode toggle button is not visible to the anonymous user. The page renders correctly using the Oqtane Default theme with interactive server-side rendering.
![image](https://github.com/user-attachments/assets/32cf11a8-7434-42d8-9bab-ab3346717df2)

#### Test Case 8
- Title: Admin User - Interactive Server Render - Oqtane Default Theme
- Expected Result:
  The Edit Mode toggle button is visible to the admin user. The admin can toggle Edit Mode as expected. The page renders correctly using the Oqtane Default theme with interactive server-side rendering.
![image](https://github.com/user-attachments/assets/2a32758e-8a98-4a58-aac2-4633b21c3e30)

#### Test Case 9
- Title: Anonymous User - Interactive Client Render - Blazor Default Theme
- Expected Result:
  The Edit Mode toggle button is not visible to the anonymous user. The page renders correctly using the Blazor Default theme with interactive client-side rendering.
![image](https://github.com/user-attachments/assets/0db21cac-bdbb-4704-8215-2e3f35f3dad9)

#### Test Case 10
-   Title: Admin User - Interactive Client Render - Blazor Default Theme
-   Expected Result:
The Edit Mode toggle button is visible to the admin user. The admin can toggle Edit Mode as expected. The page renders correctly using the Blazor Default theme with interactive client-side rendering.
![image](https://github.com/user-attachments/assets/9cc5996b-44cc-4eb7-aa9e-343202121c43)

#### Test Case 11
-   Title: Anonymous User - Interactive Auto Render - Blazor Default Theme
-   Expected Result:
  The Edit Mode toggle button is not visible to the anonymous user. The page renders correctly using the Blazor Default theme with interactive auto rendering.
![image](https://github.com/user-attachments/assets/033e46bd-7bd6-485e-9f32-227ad6d65c02)

#### Test Case 12
-   Title: Admin User - Interactive Auto Render - Blazor Default Theme
-   Expected Result:
  The Edit Mode toggle button is visible to the admin user. The admin can toggle Edit Mode as expected. The page renders correctly using the Blazor Default theme with interactive auto rendering.
![image](https://github.com/user-attachments/assets/172f5e20-5ee0-47bd-96c4-dc25b2768b08)

### Group 2: Test Themes Showing New Behavior with `ShowEditMode="false"`

#### Test Case 13
-   Title: Anonymous User - Static Server Render - Oqtane DefaultHideEditToggle Theme
-   Expected Result:
  The Edit Mode toggle button is not visible to the anonymous user. The page renders correctly using the Oqtane DefaultHideEditToggle theme with static server-side rendering.
![image](https://github.com/user-attachments/assets/436a882a-7e72-44c4-9f3b-8a37b735d034)

#### Test Case 14
-   Title: Admin User - Static Server Render - Oqtane DefaultHideEditToggle Theme
-   Expected Result:
  The Edit Mode toggle button is not visible to the admin user. Despite being an admin, the toggle is hidden due to the theme setting ShowEditMode="false". The page renders correctly.
![image](https://github.com/user-attachments/assets/e5900a62-c510-4c49-8a8f-1be200dbfbe8)

#### Test Case 15
-   Title: Anonymous User - Static Client Render - Blazor DefaultHideEditToggle Theme
-   Expected Result:
  The Edit Mode toggle button is not visible to the anonymous user. The page renders correctly using the Blazor DefaultHideEditToggle theme with static client-side rendering.
![image](https://github.com/user-attachments/assets/f9d65bb1-7a42-4bdb-98c7-8f4daabb1369)

#### Test Case 16
-   Title: Admin User - Static Client Render - Blazor DefaultHideEditToggle Theme
-   Expected Result:
  The Edit Mode toggle button is not visible to the admin user. The toggle is hidden due to the theme setting. The page renders correctly.
![image](https://github.com/user-attachments/assets/c7be6819-9a88-4644-be26-bb13bc88a7cd)

#### Test Case 17
-   Title: Anonymous User - Static Auto Render - Blazor DefaultHideEditToggle Theme
-   Expected Result:
  The Edit Mode toggle button is not visible to the anonymous user. The page renders correctly using the Blazor DefaultHideEditToggle theme with static auto rendering.
![image](https://github.com/user-attachments/assets/f07ce6ce-c135-483d-9d9e-056161aad7e4)

#### Test Case 18
-   Title: Admin User - Static Auto Render - Blazor DefaultHideEditToggle Theme
-   Expected Result:
  The Edit Mode toggle button is not visible to the admin user. The toggle is hidden due to the theme setting. The page renders correctly.
![image](https://github.com/user-attachments/assets/3e4d82f4-0958-46d5-ab79-982771f6e8a7)

#### Test Case 19
-   Title: Anonymous User - Interactive Server Render - Oqtane DefaultHideEditToggle Theme
-   Expected Result:
  The Edit Mode toggle button is not visible to the anonymous user. The page renders correctly using the Oqtane DefaultHideEditToggle theme with interactive server-side rendering.
![image](https://github.com/user-attachments/assets/6a8d458a-4e83-4c49-ab38-8e038178e33e)

#### Test Case 20
-   Title: Admin User - Interactive Server Render - Oqtane DefaultHideEditToggle Theme
-   Expected Result:
  The Edit Mode toggle button is not visible to the admin user. The toggle is hidden due to the theme setting. The page renders correctly.
![image](https://github.com/user-attachments/assets/1612c78f-ac64-4f5e-92e9-e5788624c2be)

#### Test Case 21
-   Title: Anonymous User - Interactive Client Render - Blazor DefaultHideEditToggle Theme
-   Expected Result:
  The Edit Mode toggle button is not visible to the anonymous user. The page renders correctly using the Blazor DefaultHideEditToggle theme with interactive client-side rendering.
![image](https://github.com/user-attachments/assets/e881ff5e-2511-4c4c-b8ac-1d101f1323aa)

#### Test Case 22
-   Title: Admin User - Interactive Client Render - Blazor DefaultHideEditToggle Theme
-   Expected Result:
  The Edit Mode toggle button is not visible to the admin user. The toggle is hidden due to the theme setting. The page renders correctly.
![image](https://github.com/user-attachments/assets/dea263f4-d07a-4947-a645-76c1caeb8b77)

#### Test Case 23
-   Title: Anonymous User - Interactive Auto Render - Blazor DefaultHideEditToggle Theme
-   Expected Result:
  The Edit Mode toggle button is not visible to the anonymous user. The page renders correctly using the Blazor DefaultHideEditToggle theme with interactive auto rendering.
![image](https://github.com/user-attachments/assets/7131dd4f-d546-4bf7-8509-ba9a83a7f62b)

#### Test Case 24
-   Title: Admin User - Interactive Auto Render - Blazor DefaultHideEditToggle Theme
-   Expected Result:
  The Edit Mode toggle button is not visible to the admin user. The toggle is hidden due to the theme setting. The page renders correctly.
![image](https://github.com/user-attachments/assets/a30cc53a-8766-4e95-a4a4-790d178fd439)

### Comment

Each test case ensures that the addition of the ShowEditMode parameter functions as intended, either preserving the existing behavior in default themes or demonstrating the new behavior in modified themes where the Edit Mode toggle button is hidden.

**Note**:
- In all test cases with the default themes (Test Cases 1-12), the existing behavior is preserved:
  - Anonymous Users: Edit Mode toggle button is not visible.
  - Admin Users: Edit Mode toggle button is visible and functional.
- In all test cases with the modified themes using `ShowEditMode="false"` (Test Cases 13-24), the new behavior is exhibited:
  - Both Anonymous and Admin Users: Edit Mode toggle button is not visible due to the theme configuration.

These test cases cover all combinations of user types and render variations, ensuring thorough validation of the enhancement implemented for issue #4883.

## Conclusion
All existing themes and functionalities remain unaffected unless `ShowEditMode` is explicitly set to `false`.
