### ISSUE TITLE
[BUG] Not possible to login when TwoFactor is enabled in UserSettings

### ISSUE THREAD

**Issue by beolafsen** [oqtane/oqtane.framework#4947]
### Oqtane Info

Version - 6.0.1

### Describe the bug
System hang on login after keyin TwoFactorCode.

### Steps To Reproduce
Activate TwoFactor in User Settings

### Solution?
When changing this code it works for me:
![image](https://github.com/user-attachments/assets/7a90675e-8c53-4f32-ab41-f57a5786c9b0)

but maybe it should be like this:
![image](https://github.com/user-attachments/assets/26d44370-f89a-4333-90d1-1665206558bc)

**Comment by sbwalker** [comment]
@beolafsen were you able to confirm that this is a new problem in 6.0.1 (ie. it worked in prior versions)?

**Comment by sbwalker** [comment]
It appears this could be related to PR #4861 - @zyhfish are you able to take a look?

**Comment by zyhfish** [comment]
Hi @sbwalker , submitted PR #4948 to handle this.

**Comment by sbwalker** [comment]
There are 3 options for Two Factor Authentication (2FA) in User Settings:

Disabled (false) - means that 2FA is disabled for the Site
Optional (true) - means that 2FA is enabled for the Site but is controlled by the setting on each individual user account
Required (required) - means that 2FA is required for all users in order to login to the Site

@beolafsen when you say that you "activated TwoFactor in User Settings" which option did you choose - Optional or Required?

**Comment by beolafsen** [comment]
I set ‘required’. Mvh BEO23. des. 2024 kl. 21:02 skrev Shaun Walker ***@***.***>:﻿
There are 3 options for Two Factor Authentication (2FA) in User Settings:
Disabled (false) - means that 2FA is disabled for the Site
Optional (true) - means that 2FA is enabled for the Site but is controlled by the setting on each individual user account
Required (required) - means that 2FA is required for all users in order to login to the Site
@beolafsen when you say that you "activated TwoFactor in User Settings" which option did you choose - Optional or Required?
