### ISSUE TITLE
Module Actions Dropdown Menu Styling

### ISSUE THREAD

**Issue by sbwalker** [oqtane/oqtane.framework#523]
The text in the module action dropdown menu is gray when it should be white. 

![image](https://user-images.githubusercontent.com/4840590/82602468-2446e800-9b7f-11ea-8789-512b70708338.png)

This makes the links difficult to read. I am not sure why this is happening as the Bootswatch Cyborg theme has white text:

https://bootswatch.com/cyborg/

![image](https://user-images.githubusercontent.com/4840590/82602523-36c12180-9b7f-11ea-9046-5dddea3bb217.png)

**Comment by thabaum** [comment]
I believe we need to a CSS style class here.  This color is inherited from bootstrap _reboot.scss

`a:not([href]):not([tabindex])`

If you set this in CSS File it will set to color.

This is an inherited color so I believe it is using the color that is used for text.

A CSS class is needed in the framework here for that area of the app that can be controlled by themes instead of bootstrap if desired.

possibly `app-dropdown` css class.  I can create a PR for this if desired.

I will put together a PR tonight to make this white for the theme.

I will set the color overriding bootstrap or if I can add the class I will do it using the app-dropdown class in the theme css file.

**Comment by sbwalker** [comment]
The goal is to utilize standard Bootstrap as much as possible, so we should avoid the creation of custom CSS classes as much as possible. If your diagnosis is correct it sounds like a targeted color override is needed in the theme.css file. I wonder why the Bootswatch site does not need it - is it because the Bootswatch page does not reference Bootstrap as the base style sheet? Or is it using a different version of Bootstrap 4?

**Comment by thabaum** [comment]
Here is the code:

`div.app-moduleactions a.dropdown-toggle, div.app-moduleactions div.dropdown-menu {
    color:#ffffff;
}`

**Comment by thabaum** [comment]
that in theme.css fixes but the  hover is only question can that stay?

**Comment by thabaum** [comment]
You want to make the toggle bright yellow ?

**Comment by thabaum** [comment]
where to put this in the file towards the top or bottom as well?

**Comment by thabaum** [comment]
> I wonder why the Bootswatch site does not need it - is it because the Bootswatch page does not reference Bootstrap as the base style sheet? Or is it using a different version of Bootstrap 4?
I re-thought the proper way of dealing with this and looked closer at the framework as it already had a class app-moduleactions

so the fix is above...

**Comment by thabaum** [comment]
To find out the difference I would have to spend some time comparing so I don't have an answer there.

I am guessing maybe Bootswatch does not use the darker color?  Or possibly they have another class?

**Comment by thabaum** [comment]
Looks like line 18 is where i should put it...

 div.app-moduleactions a.dropdown-toggle, div.app-moduleactions div.dropdown-menu, app-moduleactions show {
     color:#ffffff;
 }

I will change line 14 area to this

**Comment by thabaum** [comment]
Created a PR I put my fix at end of selectors
