### ISSUE TITLE
RFC: Move all Admin features away from Theming influences.

### ISSUE THREAD

**Issue by iJungleboy** [oqtane/oqtane.framework#565]
In old DNN and Oqtane 1, the administration behaves like portal content. 

Because of this, it also requires portal themes to work etc. which is related to #560. It also means that if a theme is buggy, the site administration can completely fail, or look so bad that people cannot really work with it. This is what used to happen in DNN 1-7 and was how 2sxc started in 2012. In ca. 2014 2sxc switched over to a standalone iframe based UI and Dnn 8+ also used the IFrame-Overlay approach which completely decoupled the Admin-functionality from the page.

So to clarify: It's not the iframe that I'm trying to promote here - it's the fact that the admin UI should be stable and reliable no matter what happens to a theme, CSS or whatever. So irrespective of the form (iframe, layer, etc.) I would strongly suggest that the entire admin experience - though visually well embedded in a site, should be completely inert and not be exposed to the risks of a live site and it's ongoing changes. 

Your thoughts?

**Comment by sbwalker** [comment]
This topic will need some consideration. I can fully understand how someone coming from a DNN background would come to this conclusion. DNN is a CMS and especially in versions 7+ DNN began to focus more on its CMS capabilities. Oqtane is not a CMS - it is a modular application framework. As a result the theming aspect is supposed to be better than the standard Blazor Layout concept but not nearly as powerfully as any of the hundreds of site builders or CMS’s that already exist today.

**Comment by sbwalker** [comment]
Further to this topic, as understanding the philosophy of the product is important. Oqtane is a modular application framework. It's purpose is to help people develop highly responsive web applications in a modular manner. They do this by creating pages which allow them to dynamically organize their modules. Because Oqtane is not a CMS there is no concept of a front-end UI for content management and a back-end UI for administration. A site contains functionality which represents a composite web application that should have a consistent user experience. There are certain default modules which are included in every site so that you can manage assets. Although there are some default modules it is important to note that a developer can create their own modules and include them in the Admin Dashboard as well simply by creating them as children as the Admin page.

I realize that people are going to try to use Oqtane as a CMS. But I am not really sure why someone would choose to use Oqtane as a CMS when there are so many amazing CMS's which are already available - both open source and commercial. I realize it is an interesting technical challenge but I do not see the value in creating "yet another CMS" - in fact this is contrary to the entire philosophy of Oqtane of helping developers avoid "re-inventing the wheel".

**Comment by iJungleboy** [comment]
Actually @sbwalker I believe almost all of Oqtanes users + many more will will say "I need a website solution that is built on Blazor" 😉. Everybody that runs any online system / application ends up wanting more and more of cms, blog, articles, showcase, gallery etc. features simply because these tools end up complementing each other. And because you have to communicate/market your tool in a professional manner, and you want to keep it all in one solution, possibly sharing data between the tool, users-logins, etc.

**Comment by thabaum** [comment]
Oqtane is CAP = Component Application Framework... needs to be something new ;)

**Comment by thabaum** [comment]
>I need a website solution that is built on Blazor" 😉. Everybody that runs any online system / application ends up wanting more and more of cms, blog, articles, showcase, gallery etc. features simply because these tools end up complementing each other.

Homerun!  you can do this ALL with Oqtane... you just need to dev, brand, promote, sell!  But I would wait for MVP.  You can make your dream with Oqtane down the road, even if you dont want bootstrap I think once you get a groove with it you will be able to easily mod it out yourself following someone's tutorial that did it.

**Comment by sbwalker** [comment]
Closed as the Oqtane philosophy was explained above
