### ISSUE TITLE
BUG: Error in log when logging in

### ISSUE THREAD

**Issue by louyo** [oqtane/oqtane.framework#595]
Sort of a nit, but I get what seems to be an invalid error log entry when I log in. When I first run a new install (initial log in setting password),  I then log out as host and log back in. The event log shows error, UI, "Page Does Not Exist Or User Is Not Authorized To View Page {Path}"
![oqtanelog2](https://user-images.githubusercontent.com/6570793/83980357-026d9500-a8e3-11ea-8168-f69d0ccf84e1.PNG)
![oqtanelog](https://user-images.githubusercontent.com/6570793/83980359-0699b280-a8e3-11ea-9804-ba1b41a6202e.PNG)

**Comment by sbwalker** [comment]
Are you able to provide the steps to reproduce? This error happens if you tried to navigate to a page which you do not have access to. In this case it appears to be related to the Event Log page. So if you installed the application, browsed to the Event Log page, and then clicked logout... the application would remove your auth cookie and then try to redirect to the last page you were on - and if it was the Event Log then it would trigger this error because you need to be an Administrator to view that page.

**Comment by louyo** [comment]
Create a new user, role=registered user (not admin). While logged in as host, go to event log page. While on that page, log out. Log in as the new user, get the welcome page. Do nothing, just log out. Log in as host, check log. Maybe a "rainy Tuesdays only" kind of thing. I would also point out that the variables on that page (user name) are not filled in. Maybe events are still a work in progress.  Probably shouldn't mention this, but in Firefox I get an occasional blank screen when I do that log out.

**Comment by sbwalker** [comment]
Ok, so this is related to what I described above. You were on the Event Log page and you logged out. When you auth cookie was remove the system redirected you to the Event Log page however you are not authorized to view it so it logged an error related to security. Perhaps it should not log an error in this instance but it would need to be able to differentiate between someone logging out and someone trying to hack a url to get access to a page which they do not have access. I am not sure if this is a major issue?

**Comment by sbwalker** [comment]
Are you saying that the User field in the Event Log is never populated in your instance of Oqtane? I am not seeing that behavior in my instance - I see the username field in all events where it is applicable. In the specific Error event that you included a screen shot for above, you had already logged out and the system had tried to redirect to the Event Log page - and you did not have an auth cookie so the username would have been null at that moment.

**Comment by louyo** [comment]
Like I said, a nit.

Lou

**Comment by svreic** [comment]
Maybe we should consider to redirect the user to a defined page after logout to avoid redirecting to a page that is not public visible or needs specific rights. Maybe to the home page or the login page. Or we can implement the possibility that an admin can define wich page should be redirected to if a user logs out.

**Comment by louyo** [comment]
I would vote for a setting, set by the user,  like the home page setting for your browser.

**Comment by sbwalker** [comment]
The current behavior is by design. You do not want to disrupt a user by redirecting them to a completely different context than what they were expecting. For example, if I sent a link to the Event Log page to another user who helps me manage my site and said "check this out", when the user clicked that link they would be directed to the Event Log page. Now lets assume they did not have a persistent login cookie - you would want a seamless workflow where the user can authenticated and be redirected back to the context they requested.

The framework already handles the unauthorized page scenario:

1. If the user is not logged in, the framework redirects them to the login page and remembers the context of the page they were trying to access so that they can be redirected to that page once they login.
2. If the user is already logged in then it directs them to the home page

I think the only question is if it makes sense to include an entry in the event log in both of these cases. Perhaps it should only include the event for scenario 2.

**Comment by sbwalker** [comment]
So should we remove the log entry under scenario 1 above and assume it is not actually a security error?

**Comment by louyo** [comment]
Well, I find it hard to advocate ignoring errors. I think, if it is clear that one user logging in to the same page after another user logs out, then an error will occur if there are permission differences between the 2users. Logging that error makes sense. I had assumed (we all know what that means), that the different user would be taken to his/her home page, not the same page. If that is not the case, I think logging the error helps the admin figure out why that next user can't go to that page. Not sure if this all makes sense. Bottom line, keep it like it is if you are not going to prevent trying to access that page. Just my $0.02. I felt like it was somewhat of a nit.
