### ISSUE TITLE
Missing File Manager Feature: Unable to "Move" a file

### ISSUE THREAD

**Issue by thabaum** [oqtane/oqtane.framework#604]
## Issue

In the Oqtane File Management system I wanted to move a file after uploading and only way is to delete and upload again.
A "Move" action button is needed.

## Desired Results
Select the folder at the top and click a primary color button "Move" to move the item to that folder.

## Additives

Maybe a popup asking if I am sure I want to move similar to asking if I wish to delete?  
Undo actions would be nice as well.

Also to put checkbox's next to items so provide actions on item(s) in the header.  The top header bar needs to be static and allow scrolling items under it so you can hit the delete or move at anytime.

**Comment by sbwalker** [comment]
@thabaum I am not sure if this item is a high priority missing feature or not, but if you would like to work on it I would suggest the following...

It would be best to follow the current UX patterns for consistency. Therefore I would suggest adding an additional button column to the left of the File Manager grid which was titled "Edit". This Edit button could be linked to a razor control called Details.razor ( because Edit.razor is already being used for Folder management in this module ). The Details.razor file would display a form containing details about the specific file - you can look at the File model class for ideas on which properties may be helpful to users ( ie. Size, CreatedBy, CreatedOn, etc... ). The form fields would be readonly except it would have a dropdown field for Folder - with the current folder that it is assigned to selected by default. The user could change the Folder to a different Folder - however the list of folders must only contain folders that the user has Edit rights to ( there are plenty of examples on how to load folders and check permissions in other razor components in this module ). There would be a Save button and if the user selected it, the FolderId for the file would be updated ( ie. moving it to another folder ) and the user would be redirected to the File Manager view. There would be a Cancel button to return to the main File Manager view.

**Comment by sbwalker** [comment]
One other item related to above... Oqtane uses its own abstraction for Folders and Files but the abstraction is only used for permissions currently. The physical files are still stored in a secure location but in a structure which matches the Folder/File hierarchy. So if a file is moved from one folder to another, the FileController Put() method would need to be modified to physically move the file from one directory to another using System.IO.

Note that this enhancement could be expanded to allow a user to rename a file as well within the Details modal popup UI. Then when the user selected Save the FileController Put() method would need to deal with renaming the physical file to match the filename in the model.

**Comment by thabaum** [comment]
I will give this some thought if I feel I can come up with a workable solution I will share it.  I was just thinking about working with system and Oqtane a bit so this would be good practice.

**Comment by sbwalker** [comment]
Yes if you follow the current pattern it should be straightforward.

In the Admin/Files/Index.razor add a column:

            <td><ActionLink Action="Detail" Text="Edit" Parameters="@($"id=" + context.FileId.ToString())" /></td>

Copy the Admin/Roles/Edit.razor file and paste it into Admin/Files/Detail.razor. Modify the Detail.razor to include the logic for a file rather than a role.

**Comment by thabaum** [comment]
I will give this a go next week.

**Comment by thabaum** [comment]
sorry been swamped... it is on my to-do list.  Hoping next week I have a bit more time.

**Comment by sbwalker** [comment]
@thabaum I am guessing you do not have time to work on this item... would you prefer if someone else picked it up?

**Comment by thabaum** [comment]
If anyone can do this up just put a note here you are working on it, I will do the same.  I am clearing up my work schedule now I have one more thing to get off the burners and I should be able to push forward again.  My apologies it has been very long days...

**Comment by sbwalker** [comment]
I actually implemented this today and will submit the PR tonight

**Comment by thabaum** [comment]
awesome! thank you.  I will review it when I see it.
