### ISSUE TITLE
Separate Namespace required for Module Components with OqtaneIgnore Attribute 

### ISSUE THREAD

**Issue by PoisnFang** [oqtane/oqtane.framework#650]
Attaching the OqtaneIgnoreAttribute to a component in an external module does not prevent the system from finding it via the action property when it is inherited from ModuleBase.

**Comment by PoisnFang** [comment]
I believe I figured out how this works. The `OqtaneIgnoreAttribute `only prevents the `ModuleDefinitionRepository.cs` from adding a specified namespace as a Module. Therefore ALL the components in that namespace need to have the `OqtaneIgnoreAttribute` for it to work properly. 

That being said, is there a way to have the system ignore specific components in a namespace?

**Comment by sbwalker** [comment]
I am not sure what you are trying to accomplish, but OqtaneIgnoreAttrubute has a very specific purpose related to assembly loading and it is working as expected. It is not intended to be used for enabling or disabling components within a module. There is already a security model in place for controlling access to components within a module - it is the SecurityAccessLevel property that is part of the IModuleControl interface. SecurityAccessLevel has a variety of settings which can be used to restrict and deny access to components based on permissions and roles. In addition, if you need to enable or disable access to entire modules, there are Utilize permissions which can be managed in the Manage Modules UI in the Admin Dashboard to control their availability in each site. 

One of the topics which I meant to raise in our previous discussion about Url parameters is that although there is some flexibility in the framework which allows you to follow your own module development approach, by going down this path you will not be able to take advantage of a variety of the core functionality which has been designed around the default module development approach. My suspicion is that although the framework may appear to support your approach on the surface, you will soon run into a variety of scenarios which are not suported - in particular, security, resource management, etc... all come to mind. To be clear, I am not saying that you need to change your approach - however I am saying that you have to aware that you will have to assume responsibility within your own module for many capabilities which Oqtane already provides. And since one of the most important overarching principles in Oqtane is to keep the architecture simple, we will continue to focus on the default module development approach in the core framework as it makes the core less complex, more intuitive, and less difficult to manage in the long term.

**Comment by PoisnFang** [comment]
Sorry, I did not make this clear, but this has nothing to do with User Permissions. I am talking about how Modules are found and added to the system and then how it determines which components it can route to when a user puts in a specific Action into the url of the Module. 

I realized that it is working in its intended way. What I am saying is that if one of the Components in Oqtane.Modules.Controls inherited from `ModuleBase` instead of `ModuleControlBase` then the system would register "Controls" as a Module and you would be able to route to every Component in Oqtane.Modules.Controls, whether it inherited from ModuleControlBase or not, as it would assign them all a default action name. Let me know if that makes sense.

What i had originally though that the `OqtaneIgnoreAttribute` did was make it so that Components did not receive an Action therefore could not be routed to within a module. That is not the case.

I am actually very aware of the limitations of the base framework in regards to what I am trying to accomplish and I am developing my own security and a variety of other things. I also realize that I could have built my Module as a separate application, but I wanted a CMS (Like I said I had almost finished my own before I found Oqtane)

I better understand the direction you have taken with Oqtane and I plan to continue contributing, but I will make sure to only try and contribute things that will add to the overall simplicity of the framework.

**Comment by sbwalker** [comment]
The components in the Oqtane.Modules.Controls namespace are not Modules - they are reusable components ( ie. Controls ) which are intended to be used by Modules. This is why they have their own base class - and also why their base class is flagged as [OqtaneIgnore]. Components should never be created in Oqtane.Modules.Controls which inherit from ModuleBase as it would confuse the framework into thinking they are Modules - which they are not. 

I hope my previous post did not come across poorly. I was merely trying to point out that when you try to use a framework in a different manner than it was intended, you usually run into situations which require a bit more creativity. I appreciate the fact you are pushing boundaries, and your approach has already resulted in a positive benefit to the framework in the form of Url parameters.

**Comment by PoisnFang** [comment]
@sbwalker 
>The components in the Oqtane.Modules.Controls namespace are not Modules - they are reusable components ( ie. Controls ) which are intended to be used by Modules.

I understand that, I have reusable components in my Module. 

>This is why they have their own base class - and also why their base class is flagged as [OqtaneIgnore]. Components should never be created in Oqtane.Modules.Controls which inherit from ModuleBase as it would confuse the framework into thinking they are Modules

I am not sure what you mean here... All the Module Controls Inherit from `ModuleControlBase` which inherits from `ModuleBase` and has the OqtaneIgnore Attribute, which is no different than it from inheriting ModuleBase and having the OqtaneIgnore Attribute on it which is the way it was two weeks ago. They do not really have their "own base class"

I do not mean to sound rude, and I agree with you on how the Ignore attribute works. That's why I closed the issue.

Your post did not come across poorly. I fully intend to push the framework to its boundaries. I appreciate the opportunity to work on the framework, it is fantastic. I will try to articulate myself better, I am not the best at written communication.

**Comment by sbwalker** [comment]
You are correct that every Module Control could inherit directly from ModuleBase and explicitly declare [OqtaneIgnore] - ModuleControlBase is just a more convenient mechanism for accomplishing this as it reduces the chances of someone forgetting to flag a component as [OqtaneIgnore]. Module Controls rely on many of the same state properties, resource management, etc... which Modules rely on as well - which is why ModuleControlBase inherits from ModuleBase. However in the future Module Controls May also have some of their own helper methods, etc...
