### ISSUE TITLE
Unable to Initialize Module Database from Module Manager in C# code

### ISSUE THREAD

**Issue by PoisnFang** [oqtane/oqtane.framework#666]
I am unable to initialize my Module database using the ModuleDbContext when the ModuleManger Installation function is called. The DbContextBase throws a null reference exepction on the Tenant because it cannot be resovled. Any idea on how to fix this?

**Comment by sbwalker** [comment]
When you say you are trying to initialize your "module database" are you referring to provisioning the database tables for your module in the tenant database, or something different? I am asking because there is typically not a "module database" but a tenant database which can either contain the the data for a single site or multiple sites ( which can be comprised of many different modules ).

**Comment by PoisnFang** [comment]
Dang I need some serious practice when it comes to written communication... 

> are you referring to provisioning the database tables for your module in the tenant database

Yes, that. Specifically using C# code and not SQL files.

**Comment by sbwalker** [comment]
I have a suggestion for you to try... but its a bit of a hack....

In your module's Manager class you will need to pull in SiteState via dependency injection. Then in your Install method, you will noticed that the details about the the Tenant are being passed in. However the TenantResolver in the repository relies on either the Url ( in this case there is none because it is being called during startup ) or SiteState service. However the SiteState service supports only an Alias object - so you will need to construct a "fake" Alias object using the tenant: ( ie. sitestate.Alias = new Alias { TenantId = tenant.TenantId }; ). Then you can include your module migration logic. When this code executes it should allow the TenantResolver to resolve the tenant without throwing a null exception.

Let me know how it goes...

**Comment by sbwalker** [comment]
@PoisnFang any luck with the suggestion I provided above?

**Comment by PoisnFang** [comment]
> @PoisnFang any luck with the suggestion I provided above?

@sbwalker Unfortunately I have not yet, I have gotten bogged down with some other things. But I am hoping to get to it in the next few days!

**Comment by PoisnFang** [comment]
@sbwalker I am finally getting around to trying this hack out. It seems it wont work because in DBContextBase get initialized before my ModuleManager gets called, so when I use DI to inject the ModuleDbContext the tenant is already null, and its it a private field in DBContextBase so there is no way to set it.

**Comment by PoisnFang** [comment]
I found a way to do it!

**Comment by PoisnFang** [comment]
You can see what I did you the [DbConext](https://github.com/PoisnFang/PoisnFang.Todo/blob/master/Server/Repository/Context/TodoContext.cs) and the [ModuleManager](https://github.com/PoisnFang/PoisnFang.Todo/blob/master/Server/Manager/TodoManager.cs)
