### ISSUE TITLE
backup/restore content folders in admin UI

### ISSUE THREAD

**Issue by markdav-is** [oqtane/oqtane.framework#730]
I find myself re-deploying content that I work with locally and need to deploy to the server.  it could be nice to be able to zip up the content or upload a zip of a content folder.

**Comment by bakes82** [comment]
Not sure if this follows the same request or not, but is there a "staging" option where maybe the page isnt published but if you know the link and have a certain access you can "review" it before its published out.

**Comment by sbwalker** [comment]
Note that Oqtane is not a CMS - it is a modular framework for building web applications. The concept of "staging" content is a CMS feature which will not be part of the Oqtane framework.

**Comment by nohorse** [comment]
I'm not really looking for staging per-se, but I've been manually backing up the contents like Images.  It might be nice to add a backup/restore feature that would contain images, modules, and any other content that gets physically added to site.  I'd be happy to work on such a feature if you think it's needed.  Otherwise, I'll be researching what files get added for different activities and making some backup scripts.  so far I'm seeing things added to :
- client/themes
- server/wwwroot/themes
- server wwwroot/modules
- server/content/tenants

**Comment by sbwalker** [comment]
Personally I think it would be best to rely on existing solutions for synchronizing content from one environment to another, rather than trying to build something into Oqtane. Solutions like RoboCopy, etc... were designed for this purpose. In regards to content, one of the philosophical goals of Oqtane was encapsulation however technically there are still some static assets which need to be managed separately.

    client/themes - I am not sure why content would be created at this location - it is not used by Oqtane?
    server/wwwroot/themes - any static assets related to themes ( not content )
    server wwwroot/modules - any static assets related to modules ( not content )
    server/content/tenants - the location where any user generated content assets should be stored

**Comment by nohorse** [comment]
thanks for the details!  I'll have to look and see why my client/themes has stuff in it.  I'm planning on starting over with a new dev environment today anyway.

**Comment by sbwalker** [comment]
I am reopening this item as I have some additional context to add. Currently the framework uses an abstraction over the file system to provide an extra layer of security. Files are stored in a multi-tenant aware folder structure under the ContentRootPath to ensure that they are not publicly accessible via Url. This works fine however the standard VS Publish process does not deploy this folder automatically when publishing an app - it only deploys assets in the WebRootPath ( ie. wwwroot ). If a folder allowed the user to specify the root path it would allow the system to support both locations.
