### ISSUE TITLE
Extending Tenant Settings

### ISSUE THREAD

**Issue by bakes82** [oqtane/oqtane.framework#731]
What would the preferred way be to extend Tenant settings?  Ideally would like to just have them when you create a new tenant.  But want to make upgrading easy too :)

I see a GetTenantSettings Async and update, When you call GetSetting("NewTenantSettingValue1", ""); will it return a tenant setting or would I need to parse it out of the TenantSettings dictionary?

EX: Most of our tenants have azure storage accounts and other settings unique per client and will be used across modules so rather than set it in each module (we will allow for override @ module level) most people who will be making pages wont know these values, but the person making the tenant will.

**Comment by sbwalker** [comment]
A "tenant" in Oqtane is synonymous with a physical database where you want to store your information. It does not relate to Azure or any other type of infrastructure. I think the grouping you are looking for in Oqtane is called a Site. Each Site can be related to an isolated Tenant or you can manage multiple Sites within a single shared Tenant. Sites can have Settings - ie. the core framework currently allows you to define SMTP settings per Site.

**Comment by bakes82** [comment]
Correct, in "OUR" land a tenant = Client = 1 db.  That Tenant could have multiple sites/domains.  But all of the "tenant" data is central to 1 db.  So I still that "WE" want settings per tenant since I assume a tenant can have multiple sites.   Our code might pull the tenant storage account, and then each site we would put the data in to a specific container for that tenant, maybe that makes sense for what Im saying?

**Comment by hishamco** [comment]
>  a tenant = Client = 1 db.

Tenant = website but it doesn't necessary has its own database, because we can have database per tenant or database for all the tenants. It depends on the use cases

**Comment by bakes82** [comment]
@hishamco Im saying in OUR org a Tenant would be a client and a client only has 1 db, they can have multiple sites.  Im not saying how Oqtane is setup.  But I dont want to have to set the same value 5x at the site level because that tenant has 5 sites, Id rather set it 1x at the tenant level.

**Comment by hishamco** [comment]
I see, sorry for misunderstanding

**Comment by sbwalker** [comment]
The framework supports Tenant settings in the SettingService class:

        Task<Dictionary<string, string>> GetTenantSettingsAsync();
        Task UpdateTenantSettingsAsync(Dictionary<string, string> tenantSettings);

Settings are simply name/value pairs which are associated to a type of entity and id ( however in the case of a Tenant there is no id as it is global to that database ). The API utilizes a standard Dictionary so it is straightforward to work with. There are also a few helper methods to simplify interaction ( ie. so you dont need to verify if a key exists and you can set a default value ):

        string GetSetting(Dictionary<string, string> settings, string settingName, string defaultValue);
        Dictionary<string, string> SetSetting(Dictionary<string, string> settings, string settingName, string settingValue);
 
Usage:

    _value = SettingService.GetSetting(settings, "key", string.Empty);
    SettingService.SetSetting(settings, "key", _value)

**Comment by bakes82** [comment]
Yeah I saw those, so I can just use the GetSetting and it will pull a value if it was in the tenant side?   My question is more around how do we extend the UI to have a "Tenant" settings tab like the module settings w/out having to modify the base code.

**Comment by sbwalker** [comment]
You need to create an external module for your custom settings. In your external module you would be able to implement the user experience you desire, with any field validation you need, etc... The framework provides the APIs for saving/retrieving the settings.

**Comment by bakes82** [comment]
Right but then the settings are configured at module time and not tenant time correct?  Shouldnt there be a way for us to override the tenant process, can we make a new "tenant" module lol?  Im trying to keep them separate they are two different users doing these operations.

**Comment by kevind2000** [comment]
Just had a quick and the first look at the Oqtane Core Entity: Tenant, Alias, and Site. Here is my understanding from reading Shaun's blog/diagram, youtube, and the code: Tenant is a database connection, Site is a top URL, and Alias are the joint many-to-many table between Tenant and Site, which represents site and sub-site URLs.

So one site could have multiple Alias (subsites), which may share the same Tenant (DB) or have different Tenant (DB). On the other side, one Tenant (DB) may host multiple Sites or Sub-Sites through Alias. 

I did a quick runtime check for the first time: run Oqtane from VS and create the first Tenant and Site, through Control Panel created another subsite (in terms of URL) into second Tenant (DB). The very first Tenant(DB) is the master database, which has Tenant and Alias table while the second Tenant(DB) doesn't have these two tables. Noticed both DB have Setting table.

As for the question, the Client (business account/azure tenant) may or may not related to a Oqtane Tenant as one-to-one, if the client's sites and sub-sites (Alias) all uses the same DB, then The Tenant record would be correspond to the client record. otherwise, it's not. 

Following with Shaun's answer, you may implement module (Client/Azure Tenant) and link it to either Tenant, or Site, or Alias, depends on how your hosting Oqtane for your clients. 

I'm jumping on this; I may be on the right path or missing something important. Let me know!

**Comment by sbwalker** [comment]
@bakes82 I do not understand what you mean by "module time" and "tenant time"? In Oqtane there are different permission levels. Only users with "host" permissions are allowed to create new tenants or sites - it is essentially the super user and has full access so you should not give these rights to anyone except owners of the system. I do not know anything about your business so I have no idea what permissions your "clients" may need. My guess is that you might want to make them Administrators for specific Sites. This would allow them to manage any entities within a Site.

**Comment by bakes82** [comment]
It seems like Shaun knows what Im talking about I thank.

On this screen: 
![image](https://user-images.githubusercontent.com/3197191/92164357-3cc3d100-ee03-11ea-828a-2fec2fef4049.png)
I want there to be another tab that says Settings. And a way for me to add a field that says "Color", or "Azure Storage Account Name" or "Max contacts".  Things specific to a tenant (In our case a client)

**Comment by sbwalker** [comment]
Who specifically do you envision accessing that UI in the screen shot? If your answer is your clients then there is a problem because it would mean you want to give "host" rights to your clients - which will not work because it would mean clients would have root access to each others environments.

**Comment by bakes82** [comment]
Someone in our "Client" setup team who would also be configuring the DB, making azure storage accounts, and IIS sites, not lets say HTML/site person.   The HTML/Site people would be adding modules to pages and tweaking that stuff, but they have no idea about all the back end things like storage account names.

**Comment by bakes82** [comment]
When I say client Im saying "Microsoft"   Microsoft is a client of OURS, they have 1db, thus will be 1 tenant.   They can have multiple sites in octane I understand that.  But we have specific tenant/client settings that maybe only the higher level up setup teams know and then when the site is up, the lower down creative/marketing folks will be maintaining the pages and modules on those pages, they wont have the backend info and honestly they have no reason to know it or should even know it.

**Comment by sbwalker** [comment]
Ok, so you could create a "Tenant Settings" module with your specific settings. Since you want this module available in every Site your create I would suggest creating a custom site template ( https://blazorhelpwebsite.com/ViewBlogPost/41 ) which includes all of the standard pages as well as an Admin "Tenant Settings" page with the "Tenant Settings" module. Then when your "client setup team" creates a tenant/site, this page will be automatically created. When the "client setup team" goes to www.client1.com they can browse to the "Tenant Settings" page and manage the config values. And when they browse to www.client2.com they can browse to the page and manage different config values. Note that access to a specific tenant is controlled by site alias' ( ie. domain names ) like @kevind2000 described above.

**Comment by bakes82** [comment]
Okay sounds good.  We finally got there!

**Comment by sbwalker** [comment]
The solution I described above will work. But I think what you were hoping for is something a bit different. Something more along the lines of how the current User Profile works - where you can define arbitrary profile properties and the User Profile dynamically builds a form to collect those properties. The challenge with dynamic forms is that there are so many edge cases... you may need a select control based on data from a different table or data source, or you may have fields which are dependent on one another for input, or you have advanced validation rules... all of these scenarios currently exist in Oqtane which is why the current approach of creating a custom module is better as it offers total flexibility.

**Comment by bakes82** [comment]
Yeah, or something like on how you do it in the modules settings.   Maybe you could let us do with the understanding it for basic things strings, int, bool ;)
I assume I can put the page in the "Admin Dashboard" might be les
