### ISSUE TITLE
The type or namespace name 'RenderTreeBuilder' does not exist ....

### ISSUE THREAD

**Issue by lanthonyneville** [oqtane/oqtane.framework#77]
Using: 
VS Community 2019 Preview 16.3.0,
.NET Core 3.0 Preview 8 SDK (3.0.0-preview8-013656). Also tried updating to preview9-014004 with same result. These are the latest versions available as of today (14 Sep).

Build fails with error:
_The type or namespace name 'RenderTreeBuilder' does not exist in the namespace 'Microsoft.AspNetCore.Components.Rendering'_

in ~50 generated code files (e.g. Oqtane.Client\obj\Debug\netstandard2.0\RazorDeclaration\Modules\Counter\Index.razor.g.cs)

I did note the compatibility requirements mentioned on https://github.com/oqtane/oqtane.framework however, it does not seem possible to download 3.0.0-preview8.19405.7 now.

**Comment by ADefWebserver** [comment]
@sbwalker Do you want me to do the upgrade to Preview 9?

**Comment by lanthonyneville** [comment]
FYI, after updating the Blazor nuget packages to preview9, there are a lot of breaking changes to deal with ... 
IUriHelper has gone (now NavigationManager?)
AuthenticationState & AuthenticationStateProvider have gone
UIChangeEventArgs has gone

I don't know the code and Blazor well enough and gave up!

**Comment by sbwalker** [comment]
Yes, there have been a lot of breaking changes in every Blazor release, and I have not had time to upgrade to Preview9 yet. If Michael ( @ADefWebserver ) would like to to attempt the upgrade and submit a pull request, it would be very appreciated.

**Comment by ADefWebserver** [comment]
I will try to get it upgraded by Tuesday.

**Comment by VladAndHanna** [comment]
It doesn’t start either (preview9).
But, I think, you need to be understanding and wait a bit for the update.
The project is impressive and interesting.
Well done!

**Comment by sbwalker** [comment]
It works great in Preview8 ;) And I don’t expect it will be difficult to upgrade to Preview9 - just a bit tedious as it has many components and demonstrates many aspects of Blazor.

**Comment by fileman** [comment]
I have started migration to preview9, but since there are some breaking change, to build successfully all proj, I to change:
1. IUrihelper no more has GetAbsoluteUri() method so I've set temporary to BaseUri;
2. Client proj:
- a mono linker issue require BlazorLinkOnBuild to false;
- change to netcore classlibrary instead of netstandard;

**Comment by fileman** [comment]
[Here](https://github.com/fileman/oqtane.framework/pull/1/files) you can view edited files

**Comment by ADefWebserver** [comment]
@sbwalker I saw the PR by @fileman at https://github.com/fileman/oqtane.framework/pull/1 Not sure what to do here. Should I still do a PR? Let me know your desire.

**Comment by ADefWebserver** [comment]
@sbwalker I think it is best to accept this PR because it makes the changes we would have had to do anyway. Let me know if you desire any further work.

**Comment by sbwalker** [comment]
Yes, this looks excellent! Thank you so much for your efforts to migrate to Preview9. I will accept the PR as soon as I am able to upgrade my system to Preview9 and test the changes locally.

**Comment by sbwalker** [comment]
I found some additional compatibility issues in my testing and merged the changes. I really appreciate your assistance!!

**Comment by fileman** [comment]
I havent completed, because I'm expecting your request to change something before merge.
Thanks for the framework!

**Comment by fileman** [comment]
I'm interested to use azure b2c users, @sbwalker or @ADefWebserver are you looking for this? 
If not I can try to find a way to use it with oqtane.

**Comment by sbwalker** [comment]
Currently the framework is using .NET Core Identity for Users - primarily for password management and authentication. I have not explored if it is possible to override .NET Core Identity with other implementations. If Azure B2C were to be supported in Oqtane then it would need to be architected as a provider model so that it is possible to easily plug in alternative implementations.

**Comment by sbwalker** [comment]
After the changes to move to Preview9 the framework does not work client-side anymore... we will need to diagnose. @fileman why did you change the project file configuration TargetFramework - I did not see anything in the Preview9 release notes which mentioned anything about this requirement?

**Comment by sbwalker** [comment]
Oh... I see your comment now:

- a mono linker issue require BlazorLinkOnBuild to false;

>> I need to look into this further.

- change to netcore classlibrary instead of netstandard because Microsoft.AspNetCore.Components.Authorization namespace is required for AuthenticationState* classes and with Microsoft.AspNetCore.App was not recognized;

>> this was because a new package needed to be added to the client project as Microsoft separated Authentication. I think the project file needs to be reverted back to netstandard to work in client-side Blazor. I will make the changes.

**Comment by sbwalker** [comment]
Ok I reverted the changes to csproj files and client-side Blazor is working now

**Comment by fileman** [comment]
Sure Microsoft.AspNetCore.Components.Authorization nuget package was the simplest solution, but in my research in VS and nuget.org ([now I found it at page 7](https://www.nuget.org/packages?page=7&q=Microsoft.AspNetCore.Components.Authorization)) instead of show only searched pkg show all Microsoft.AspNetCore.* ... a waste of time for all of us, sorry.

**Comment by lanthonyneville** [comment]
> Sure Microsoft.AspNetCore.Components.Authorization nuget package was the simplest solution, but in my research in VS and nuget.org ([now I found it at page 7](https://www.nuget.org/packages?page=7&q=Microsoft.AspNetCore.Components.Authorization)) instead of show only searched pkg show all Microsoft.AspNetCore.* ... a waste of time for all of us, sorry.
> Update: There is an open [issue](https://github.com/NuGet/NuGetGallery/issues/4124) about this problem, as [workaround](https://github.com/NuGet/NuGetGallery/issues/7463) add packageid: prefix is required.

Yeah, searching Nuget can be a PIA. Enter exact package name => no results (or package is on page 10 of 20) !
