### ISSUE TITLE
Module Creator Localization

### ISSUE THREAD

**Issue by hishamco** [oqtane/oqtane.framework#774]
After supporting localization, the module creator should respect the localization assemblies and naming conventions to avoid collision without impact the user as @sbwalker mentioned [here](https://github.com/oqtane/oqtane.framework/discussions/749#discussioncomment-86850)

**Comment by hishamco** [comment]
> @hishamco this project was initially created using the Module Creator: https://github.com/oqtane/DNF.Projects

> Assembly Name: DNF.Projects.Client.Oqtane ( specified in *.csproj in AssemblyName attribute )
> Default Namespace: not specified globally
> Razor Namespace: @namespace DNF.Projects

> If we need to modify some of these default specifications in order to support localization, we just need to determine the impact.

@sbwalker in `Oqtane.Blogs.Client.Oqtane` the default namespace is different it's `Oqtane.Blogs.Client` and that's on of the big issues I suffered a lot because I thought it's similar to the assembly name

my question is from where that value is come from

**Comment by sbwalker** [comment]
@hishamco I would suggest you try out the Module Creator yourself. You can do this by logging into Oqtane, click the [*] icon in the upper right to open the Control Panel, in the Module Management section change the "Common Modules" category to "Developer Modules" and select the Module Creator module from the dropdown beneath it. Then click "Add Module To Page". Once the Module Creator module is added to the page, provide some basic information about the module you are creating and choose the External option for the Template. This will scaffold an entire module for you which you can open in Visual Studio and build independently from Oqtane. There is a Package project in the module solution with a few batch files that are created automatically which handle the copying of assets to the appropriate locations so that Oqtane can see them after build.

**Comment by sbwalker** [comment]
I would still encourage you to try out the Module Creator.... but I am actually thinking that localizing the Blog module ( https://github.com/oqtane/oqtane.blogs ) may be a better example to start with. It would allow you to fully implement localization for at least 1 additional culture and allow you to identify any challenges which may exist.

**Comment by hishamco** [comment]
@sbwalker I already tried the Module Creator twice while I'm doing localization, after that I selected `Oqtane.Blog` coz I was afraid of the generated namespaces and I don't wanna miss anything ;)

I can try to localize `Oqtane.Blog` first then come to this issue because we need to closed before V2
