### ISSUE TITLE
Policy (Permissions) instead of Role

### ISSUE THREAD

**Issue by fileman** [oqtane/oqtane.framework#79]
In some controller you are using only AdminRole, why you don't use a framework built-in policy?
With policy even another role with specific policy (permission) can delete, add, edit, etc...

As example in UserController something like:
```
        // DELETE api/<controller>/5?siteid=x
        [HttpDelete("{id}")]
        [Authorize(Roles = Constants.AdminRole, Policy = Constants.DeleteUser)]
        public void Delete(int id, string siteid)
```
instead of
```
        // DELETE api/<controller>/5?siteid=x
        [HttpDelete("{id}")]
        [Authorize(Roles = Constants.AdminRole)]
        public void Delete(int id, string siteid)
```

**Comment by sbwalker** [comment]
The goal in Oqtane is to make the framework as dynamic as possible and allow the security configuration to be performed by an end-user rather than by a developer.

If you look in \Oqtane.Server\Modules\HtmlText\Controllers\HtmlTextController.cs you will see that Oqtane does have some support for policies:

        [Authorize(Policy = "ViewModule")]

Policies are dynamically integrated with the security model. When you add a module to a page you can view the Module Settings in the UI and it contains a permissions grid which allows you to dynamically specify the roles and/or users which are either granted or denied "View" or "Edit" permissions to that module. The policy declaration in the Controller then cross references the permission information provided with the current user at run-time.

Currently, most of the "core" controllers do not follow this approach and simply assume that only an Administrator should be allowed to manage "core" entities. This could certainly be enhanced in the future - as long as it aligns with the "dynamic" goals I outlined above.
