### ISSUE TITLE
Login UI issue

### ISSUE THREAD

**Issue by hishamco** [oqtane/oqtane.framework#794]
After the latest changes the login textboxes become wide which not suited from UI/UX perspective, I suggest to resize and place them into the center

**Comment by sbwalker** [comment]
The correct way to do this in Oqtane is to include a CSS file with custom styles for the Login module ( in the standard location ), link the CSS file as a Resource in the module, and associate your CSS styles to the markup in the razor file. I am mentioning this because there seems to be a lot of confusion about how to style modules, and I don't want you to waste your time making changes to the default app.css or the default themes.

**Comment by hishamco** [comment]
So can I add a resource to login to fix this issue?

**Comment by sbwalker** [comment]
yes, the CSS file should be created in the \Oqtane.Server\wwwroot\Modules\Oqtane.Modules.Admin.Login folder

**Comment by hishamco** [comment]
Sure, hope to fix it ASAP

**Comment by sbwalker** [comment]
resolved in #864
