### ISSUE TITLE
Module Creator : Creating External Module (Running from install on IIS)

### ISSUE THREAD

**Issue by leigh-pointer** [oqtane/oqtane.framework#902]
(**Running from install on IIS**)

After creating an external module trying to compile for release does not work.

4>The system cannot find the path specified.
4>File not found - *.nupkg
4>0 File(s) copied
========== Rebuild All: 4 succeeded, 0 failed, 0 skipped ==========

The Release.cmd file has a bad reference to nuget.exe

**Comment by sbwalker** [comment]
When running from install on IIS, the Oqtane release package does not contain the nuget.exe file in the /Package folder. And I would argue that it shouldn't as you generally would not want an EXE file to be published to a web server, And since you cannot rely on a web environment to have an updated version of nuget.exe or an environment variable defined, I am not sure if there is a solution?

**Comment by leigh-pointer** [comment]
Could it be better to remove the External option when running compiled/live/ or on the webserver.  The files are created on the server, so the files would not be available in a live situation.

**Comment by sbwalker** [comment]
So there is a scenario where a developer may want to do local development using a release version of Oqtane. They would download a release version and set it up on IIS locally. And they may still want to use the Module Creator to scaffold the initial files to create a module. In this scenario they are not running a source version of Oqtane in Visual Studio.

**Comment by sbwalker** [comment]
Another possible solution is that the Module Creator template includes nuget.exe in the /Package folder that is created
