### ISSUE TITLE
Oqtane 2 Bug updating Module Title

### ISSUE THREAD

**Issue by jiggyswift** [oqtane/oqtane.framework#904]
I installed Oqtane 2 and tried editing page module titles (the heading section on each module).  But it looks like there is a caching issue where the title does not update unless you navigate away from the page and back to the page.  Even if you edit it, hit save, and edit again, the values does not appear to update.

Obviously critical bug that would impact every single person using it (I assume introduced in the rush to get to .NET 5).  

It impacted both WebAssembly and Server version.

**Comment by hishamco** [comment]
Thanks for reporting this @jiggyswift we will have a look, if you planned to push a PR for this will be great

**Comment by sbwalker** [comment]
Thank you for reporting this issue. There were some performance optimizations done in Oqtane 2.0 to reduce the number of calls from the client to the server and take advantage of the information stored in the PageState. Obviously in order to do this effectively you also need the ability for the framework to recognize when a change has been made which requires elements of the PageState to be reloaded. This is handled by the SiteRouter and SyncEvent service - both of which have existed since Oqtane 1.x. However it appears that the performance optimizations in Oqtane 2.0 did not handle this specific use case for modifying the module title.

**Comment by jiggyswift** [comment]
Thanks for your response Shaun.  It is funny that editing the title was about the first thing I tried after installing v2 :-)  It was obvious a caching issue.  BTW: I know you are targeting Oqtane as an application framework and not a CMS, but do you have any plans to ever use Oqtane for the actual Oqtane.com website?

**Comment by sbwalker** [comment]
Yes, I do plan to use Oqtane for oqtane.org. Community websites usually have a lot of interactive features - so they are more web applications than websites ( ie. think of Github itself )

**Comment by sbwalker** [comment]
fixed in #913 and will be in 2.0.1
