### ISSUE TITLE
Amazon Aurora support

### ISSUE THREAD

**Issue by m-ratnikov** [oqtane/oqtane.framework#943]
Hi there! 

As I figured out, now oqtane framework supports MS SQL database only (#942, #851). Due to migrations issue. 
Can you please clarify two moments?

1) When EF migrations support will be implemented. Will this automatically enable the ability to use the Amazon Aurora cloud DB solution as an underlying oqtane database?

2) Can you give an approximate date of the release when oqtane will become database-agnostic?

Thanks!

**Comment by sbwalker** [comment]
Based on the feedback from users, I believe that multiple database support and EF Core migrations should be the main feature for the upcoming 2.1.0 release. There will be a lot of work and testing required in order to get it working. The feature is not even designed at this point but it will most likely rely on the native EF Core ability to support multiple relational databases. Amazon Aurora is a MySQL and PostgreSQL compatible relational database so in theory it would be supported. It is hard to provide a timeline as the technical analysis and impact assessment have not been done but I would think 2-3 months may be a reasonable time frame.

**Comment by m-ratnikov** [comment]
I see. Thanks for the answer.
