### ISSUE TITLE
Module Development. Module.css not not available in the settings control

### ISSUE THREAD

**Issue by leigh-pointer** [oqtane/oqtane.framework#957]
I have added the code:
public override List<Resource>...... to include my module.css
in my settings control, but the module.css is not visible in the page head tag, and obviously no styles are rendered

**Comment by sbwalker** [comment]
Good catch Leigh! This is a bug... I tracked it down to some logic in the SiteRouter which does some custom processing for Settings components. It treats these components differently because it actually renders a common Oqtane.Modules.Admin.Modules.Settings component and then embeds your custom Settings component inside of it. This will be a tricky one to test.
